### ISSUE TITLE
Elixir typespecs

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1163]
Add [typespecs](https://hexdocs.pm/elixir/1.12/typespecs.html) to all functions.

**Comment by ssaunderss** [comment]
This is another issue I could help out with but might take some time. Do you also want to add some enforcement checks to the CICD pipelines so that typespecs are required for all public functions?

**Comment by AndrewDryga** [comment]
@jamilbk I think we should not add them to *all* functions:
1. For Phoenix/Ecto-related code there is almost no sense to do it, they all are based on structs like Conn or Changeset, and Phoenix doesn't have type specs there, so Dialyzer would guess the type as `map(...)` anyways. String-keyed maps (like controller `params`) are also not type-checked.
2. Dialyzer can work without any typespecs at all, they are needed more for documentation purposes.

So I would only write them to functions that are side-effects free (eg. don't work with DB) and dense enough so that we want to have extra careful there.

**Comment by usmailaabdoul** [comment]
Picking up this issue @AndrewDryga

**Comment by AndrewDryga** [comment]
Hey @usmailaabdoul. Honestly, I don't even know which functions we should cover at this point, most of the non-web-related code is going to be rewritten here: #1479. For the web app type specs won't make any sense because everything is binary there and they won't bring any value

**Comment by usmailaabdoul** [comment]
ok @AndrewDryga are you suggesting there is no need to work on this since there is already a rewrite going on?

**Comment by AndrewDryga** [comment]
@usmailaabdoul yeah, you will simply have too many merge conflicts and will need to redo everything twice

**Comment by usmailaabdoul** [comment]
yeah that's true.
