### ISSUE TITLE
Cannot access wireguard client that is installed on Kubernetes cluster

### ISSUE THREAD

**Issue by seungbaeji** [CloudFire-LLC/cloudfire#1188]
I tried exposing kube api server in a private network to a public network through ec2 instance.
The wireguard client was connected well but it didn't make a handshake with the Firezone server.
And I cannot send a packet form the ec2 instance Firezone server installed to wireguard clinet.

There's some way to connect my kube api with Firezone server?

**Comment by jamilbk** [comment]
We haven't tested Firezone too much in Kubernetes just yet, so YMMV, but:

If the client is not handshaking, that means there is no connectivity from it to Firezone. I'd double-check you can reach the exposed WireGuard listen-port from your client. Activating the tunnel in the client app may show a green indicator, but since WireGuard is a connectionless protocol, this doesn't necessarily mean the client is connected.

**Comment by jamilbk** [comment]
@seungbaeji Thinking about this a bit more -- try setting the `PersistentKeepalive` in the client's configuration to something like `25`. That should keep the UDP session open so you can tunnel back in.

**Comment by seungbaeji** [comment]
@jamilbk I just saw your comments. Thanks, I will try!!
