### ISSUE TITLE
Client IP couldn't be determined! / x_forward_for_header_issue

### ISSUE THREAD

**Issue by tengzl33t** [CloudFire-LLC/cloudfire#1201]
x_forward_for_header_issue problem appears in /settings/account when log in from local network device, with devices from other networks everything is ok.
Latest Docker Firezone + standalone nginx proxy

Container console output:
`
firezone-firezone-1  | 15:14:32.479 [warning] Client IP couldn't be determined! Check to ensure your reverse proxy is properly sending the X-Forwarded-For header. Read more in our reverse proxy docs: https://docs.firezone.dev/deploy/reverse-proxies?utm_source=code
firezone-firezone-1  | 15:14:32.479 [warning] [peer_data: %{address: {10, 105, 0, 1}, port: 38434, ssl_cert: nil}, uri: %URI{scheme: "http", authority: "10.105.0.2", userinfo: nil, host: "10.105.0.2", port: 13000, path: "/socket/websocket", query: "token=SFMyNTY.g2gDYQFuBgAZraYghQFiAAFRgA.exG0gkmL1NwcxBjQpbL8k_v4gUIUb0f8-bXhx4PihH8&vsn=2.0.0", fragment: nil}, x_headers: [{"x-forwarded-for", "192.168.0.102"}, {"x-forwarded-proto", "https"}]]
`

![1](https://user-images.githubusercontent.com/10462726/208248855-c7689f0b-cb87-4b57-a61b-ee5227b1960e.PNG)

**Comment by tengzl33t** [comment]
Nginx config:
![2](https://user-images.githubusercontent.com/10462726/208248923-40de8893-ad10-4096-a166-67c6c7e18d51.PNG)

Firezone container is assigned to static IP: 10.105.0.2, so it is connecting directly to it.

**Comment by jamilbk** [comment]
Thanks for the report! Hmmm. I'm not 100% clear on the IP address you're expecting to show up in that table. When you say "connecting directly", do you mean connecting from an address in the `192.160.0.0/24` range? If so, have you tried adding the nginx proxy IP to the `EXTERNAL_TRUSTED_PROXIES` env var?

Another possible fix may be adding your IP to the `PRIVATE_CLIENTS` var so that it is parsed as a final IP from the `X-Forwarded-For` header. But this *shouldn't* be necessary since our parsing library treats RFC1918 addresses as trusted clients anyhow.

More docs if it's helpful:

https://docs.firezone.dev/reference/env-vars/

**Comment by tengzl33t** [comment]
> I'm not 100% clear on the IP address you're expecting to show up in that table.

I'm expecting to see 192.168.0.2, it is IP of my PC in local network, from where I'm connecting to firezone.
It's is providing with headers from Nginx correctly ({"x-forwarded-for", "192.168.0.102"}), but Firezone itself thinks that it is incorrect.
But, when i'm using some other device which is not from my local local network, connecting from internet, everything works fine.

> nginx proxy IP

For firezone IP of the nginx is 10.105.0.1 (gateway/host), firezone ip is 10.105.0.2. 


> Another possible fix may be adding your IP to the `PRIVATE_CLIENTS` var so that it is parsed as a final IP

Works with: PRIVATE_CLIENTS=["192.168.0.0/16"]

**Comment by jamilbk** [comment]
Ah yes, PRIVATE_CLIENTS should contain any RFC1918 addresses you want to consider as client IPs. By default Firezone will assume them to be hops / proxies.
