### ISSUE TITLE
WireGuard device MTU not in sync with value in sites table

### ISSUE THREAD

**Issue by toreanderson** [CloudFire-LLC/cloudfire#1210]
If you change the default WireGuard device MTU in the `sites` table (i.e., what's configured in the *MTU* field in `/settings/site`), then the new value is not synchronised with the actual WireGuard device MTU on the Firezone server. It is instead left at `1280`.

This can lead to blackholes, as the WireGuard client might receive legitimate packets from servers that are larger than `1280` bytes, causing the Firezone server to send an ICMP fragmentation needed / packet too big to the server. If PMTUD does not work (ICMP is not reliable and is often subject to overzealous filtering), the connection will be hanging until it times out.

I believe this code is to blame,  specifically lines 10 and 23:

https://github.com/firezone/firezone/blob/ec3c075c6715f721f42175c2e71f63699c3707d1/rel/overlays/bin/server#L10-L24

If `WIREGUARD_MTU` is not set, then the device will be set up to use a default MTU of `1280`. As mentioned above, this does not take into account that the Firezone administrator might have changed this default in the `sites` table, which leads to the mentioned inconsistency between the client configuration files and the WireGuard device MTU.

I believe #1207 / a40da198ea88ae1cbde15e49f8131729f235ee01 have made this situation even worse, as it removes `WIREGUARD_MTU` as a documented way of configuring the WireGuard MTU. Nevertheless, the now undocumented `WIREGUARD_MTU` environment remains the *only* way to change the actual configured device MTU on the Firezone server.

**Comment by jamilbk** [comment]
@toreanderson This is great — thanks for the detailed report! [There are cases where you may want them to differ](https://gist.github.com/nitred/f16850ca48c48c79bf422e90ee5b9d95). We’re actually moving the interface management and firewall implementation to a dedicated `gateway` service so that these may be decoupled (coming in 0.8) but the fix for this today would be to keep the server MTU documented as an ENV var and leave the client MTU configurable as you’re seeing in that PR. Client MTU would then be configurable over the REST API in 0.7.

I’ll fix it up this morning with some notes in the docs added.
