### ISSUE TITLE
Remove Hammer.Plug

### ISSUE THREAD

**Issue by ssaunderss** [CloudFire-LLC/cloudfire#1216]
Hey FZ team,

Started looking through some of the tech debt issues in the codebase and came across this one that seems like a good one to get familiar with the codebase/setup: https://github.com/firezone/firezone/blob/ed6784d5986b681d9262f0b5241513c12dfd3b9b/apps/fz_http/lib/fz_http_web/router.ex#L19-L20

Looks like it's just adding support to make the hammer plug configurable - the only question I have is whether you wanted this to be end-user configurable or just another app config val in `config.exs`?

@jamilbk feel free to assign me to this one and I'll get started on it!

**Comment by jamilbk** [comment]
Curious to hear @AndrewDryga's input. Part of me thinks this is a better job for a proxy / load balancer, making the firezone upstream app as lean as possible, while part of me feels like it's good to have these safety fallbacks in the upstream app in case someone's deploying in production without a proxy (eek)

**Comment by jamilbk** [comment]
If this does stick around, it should be a runtime configuration I would think so users can change it in the UI or from the REST API.

**Comment by AndrewDryga** [comment]
I agree that I think it's a job for the load balancer, most of our Enterprise customers would deploy it behind their own ingress controller, proxy, or something like that. Using it also adds potential maintenance: if you deploy Firezone behind Kubernetes and don't set an `externalTrafficPolicy=local` option to Service, then all IPs would be the same and large instances can rate limit legitimate requests. The same can happen with any reverse proxy (HAProxy, Nginx) because Hammer [doesn't actually look into `X-Forwarded-For` header](https://github.com/ExHammer/hammer-plug/blob/master/lib/hammer_plug.ex#L180) and even if fork it and change then proxy should still be configured properly.

**Comment by AndrewDryga** [comment]
Changed the issue title to reflect what we actually need to do: remove the plug and unlock the dependency (`mix deps.unlock hammer` and `mix deps.unlock plug`).

**Comment by jamilbk** [comment]
@ssaunderss Yeah, looks like we'll want to remove it in favor of using an approach in the load balancer or proxy. It doesn't look like Caddy supports this built-in, but it'd probably come in a k8s Helm chart or similar.

- [ ] Remove hammer.plug and traces of it in codebase
- [ ] Remove any mention of it in `docs/*`
