### ISSUE TITLE
Always build a container and run a sanity check on it during CI process

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1229]
We should have a separate docker build pipeline that doesn't push anything (or a conditional in the existing one) which runs in every PR. After the container is built we need to `docker run` it and make sure it doesn't crash right away, which would be an additional confirmation that `.env.sample` is valid.

This will allow us to early catch code changes that work locally but would crash the release pipeline, like this one: https://github.com/firezone/firezone/pull/1200/commits/e50647ad3e59c11e0c7e26d8f1e1ae44d4c9c808

**Comment by jamilbk** [comment]
We've had some variation of this over the past year and settled on building when the branch starts with `build/` because the Omnibus builds can't run concurrently due to them being self-hosted runners.

With Docker we can build in parallel so that should alleviate the issue. Just noting this here for reference.

https://github.com/firezone/firezone/blob/master/.github/workflows/docker_build.yml#L6

**Comment by jamilbk** [comment]
I believe this is complete.
