### ISSUE TITLE
How set own CA ?

### ISSUE THREAD

**Issue by ihard** [CloudFire-LLC/cloudfire#1284]
I configure openid "Discovery Document URI" with own certificate CA and get error 
```is invalid. Reason: %HTTPoison.Error{reason: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:2098 generated CLIENT ALERT: Fatal - Unknown CA\n'}}, id: nil}```

I mount ca-certificates.crt with my CA to
   volumes:
      - ${FZ_INSTALL_DIR:-.}/firezone:/var/firezone
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /etc/ssl/certs/ca-certificates.crt:/app/lib/certifi-2.9.0/priv/cacerts.pem:ro
      - /etc/ssl/certs/ca-certificates.crt:/app/lib/castore-0.1.20/priv/cacerts.pem:ro

but keep getting the same error

**Comment by jamilbk** [comment]
Hi there! This will be supported with the `HTTP_CLIENT_SSL_OPTS` env var in Firezone 0.7.0 (coming soon)!

**Comment by AYDEV-FR** [comment]
Hi ! I am also very interested in this feature. When is the release of version 0.7.0 planned?
Because I tried to use the HTTP_CLIENT_SSL_OPTS variable, I went to read the code and I understood that it was not yet implemented. Maybe for a potential 0.6.17 ?

Thank you for your work ! 
Your project is very interesting!

I open the subject, why did you go to Elixir? For my culture, I am curious about the choice. Vis-a-vis Go or Rust?
