### ISSUE TITLE
Autologin

### ISSUE THREAD

**Issue by ihard** [CloudFire-LLC/cloudfire#1298]
As a suggestion to add the ability to enable autologin (redirect) to the configured idp if the user is not authorized and local login is disabled.
I configured this in the webserver config, but it may be more correct in the service.
```
    location = / {
	return 301 https://$server_name/auth/oidc/sso;
    }
```

**Comment by AndrewDryga** [comment]
@ihard hello 👋, thanks for using Firezone! 

What is the use case for it? Is this so that users don't need to click an IDP login button on the login form?

**Comment by ihard** [comment]
Yes, skip one screen

**Comment by AndrewDryga** [comment]
It won't be an easy feature to implement: we allow adding multiple  OIDC providers and then if you select one of them for default redirect others will be unusable. Also, users should be aware why they redirected to OIDC (click that button themselves), otherwise you go to some site and land on google.com which is confusing..

**Comment by ihard** [comment]
The proposed option is relevant only for one idp, for example, when used in an organization. If this is difficult to implement, I will continue to use the redirect in the web server.

**Comment by jamilbk** [comment]
For now it would be better to link directly to the IdP in question, e.g. `https://firezone.example.com/auth/oidc/google` for OIDC or `https://firezone.example.com/auth/identity` for local email/password. Those URLs shouldn't change.

I'm not sure there's a good way to do this now without too much added complexity. We can revisit when #1123 is underway.
