### ISSUE TITLE
0.7.2 - No authentication providers

### ISSUE THREAD

**Issue by gbe0** [CloudFire-LLC/cloudfire#1313]
After upgrade to 0.7.2 it seems like I have lost the ability to login via the web interface.

The login screen shows this:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/47361208/212461517-2f58f8c9-8de3-4dd2-b007-3e3c3f585392.png">

My login configuration is this:

```ruby
default['firezone']['authentication']['local']['enabled'] = true
default['firezone']['authentication']['oidc'] = {
  azure: {
    discovery_document_uri: "https://login.microsoftonline.com/xxx/v2.0/.well-known/openid-configuration",
    client_id: "xxx",
    client_secret: "xxx",
    redirect_uri: "https://xxx/auth/oidc/azure/callback/",
    response_type: "code",
    scope: "openid email profile offline_access",
    label: "Azure Active Directory"
  }
}
```

If I directly hit the redirect URI I can see this in the logs:

```
2023-01-14_07:28:46.69355 15:28:46.683 [error] GenServer :openid_connect terminating
2023-01-14_07:28:46.69359 ** (KeyError) key "azure" not found in: %{}
2023-01-14_07:28:46.69359     :erlang.map_get("azure", %{})
2023-01-14_07:28:46.69359     (openid_connect 0.2.2) lib/openid_connect/worker.ex:31: OpenIDConnect.Worker.handle_call/3
2023-01-14_07:28:46.69360     (stdlib 4.1) gen_server.erl:1149: :gen_server.try_handle_call/4
2023-01-14_07:28:46.69360     (stdlib 4.1) gen_server.erl:1178: :gen_server.handle_msg/6
2023-01-14_07:28:46.69360     (stdlib 4.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2023-01-14_07:28:46.69360 Last message (from #PID<0.512.0>): {:discovery_document, "azure"}
```

**Comment by AndrewDryga** [comment]
Hello,

All the configuration has moved to database, looks like migration did not pick up the data to insert. Its late night already for us, someone will take a look in a bit. 

Sorry for inconvenience.

**Comment by AndrewDryga** [comment]
@gbe0 can you please re-add the identity providers config using the UI by temporarily enabling local auth? Or using REST API? For now, that will unlock you while we look into the migration script.

**Comment by jamilbk** [comment]
What’s happened here is the old `AUTH_OIDC_JSON` env var was picked up in a previous version and moved to DB there, but not in a persistent migration script.

@gbe0 could I ask which version you migrated from?

Will have a fix out soon. These env vars will be restored to take precedence over DB config if present in #1162

Lots has been changing in this area — apologies for the issue.

**Comment by gbe0** [comment]
Hi,

I upgraded from 0.6.16 to 0.7.0 which had a migration problem. I then downgraded back to 0.6.16 and up to 0.7.2 once it was released.

In the above config I had temporarily enabled local auth already:

```ruby
default['firezone']['authentication']['local']['enabled'] = true
```

However, the login options are blank as per screenshot with no option to login at all.

**Comment by jamilbk** [comment]
Refs #1162 -- Namely, read `AUTH_OIDC_JSON` from Omnibus installs to override DB config and perhaps populate DB with updated config.

**Comment by jeldriks** [comment]
I experienced a similar issue as @gbe0: no login methods were shown, and Firezone/phoenix restarted every couple of seconds.

I was able to fix the issue by manually inserting an updated OICD configuration into the database.

```bash
sudo /opt/firezone/embedded/bin/psql -U firezone -d firezone -p 15432 -h localhost -c "UPDATE configurations SET openid_connect_providers = '[{\"discovery_document_uri\":\"https://login.microsoftonline.com/xxxxxxxx/v2.0/.well-known/openid-configuration\",\"client_id\":\”xxxxxxxxxxx\",\"client_secret\":\”xxxxxxxxxxx\",\"redirect_uri\":\"https://xxxxxxxxxxx/auth/oidc/azure/callback/\",\"response_type\":\"code\",\"scope\":\"openid email profile offline_access\",\"label\":\"Microsoft\",\"id\":\"azure\"}]'"
sudo firezone-ctl restart phoenix
```
Change placeholders accordingly and make sure to change the id (in my case `azure`) and part in the redirect_uri to the missing key from the error log: `(KeyError) key "azure" not found in: %{}`

-----------------
**Explanation**
It appears that the scheme of the OICD configuration has changed between versions 0.6.x and 0.7.x of firezone.
Previously it was:
```json
{
  "openid_connect_providers": {
    "<provider key / id>" : {
      "dummy": "xxxx"
    }
  }
}
```

Now it appears to be:
```json
{
  "openid_connect_providers": [
    {
      "dummy": "xxxx",
      "id": "<provider key / id>"
    }
  ]
}
```

I followed the upgrading guide and still, it was not migrated automatically. Maybe due to an error.
The relevant command on the [troubleshooting page](https://github.com/firezone/firezone/blob/547b3bbf65befa3055c3341293ae55b09ca2c7e5/docs/docs/administer/troubleshoot.mdx?plain=1#L36) is also not valid anymore for versions higher than Firezone 0.7. I tried changing `{}` to `[]`, similar to my example from above, but this didn't help. Actually, when using `{}`, it results in an internal server error. When using `[]`, only the restart loop occurs.

In the end, the only way to fix it for me was to put the JSON configuration string directly in the database, as described above.

**Comment by jamilbk** [comment]
Thanks for the detailed workaround @jeldriks. We've identified an edge case with the Omnibus install that would be causing this. Working on a fix, likely part of 0.7.4.

I've opened #1338 for the docs fix.

**Comment by gbe0** [comment]
> I experienced a similar issue as @gbe0: no login methods were shown, and Firezone/phoenix restarted every couple of seconds.
> 
> I was able to fix the issue by manually inserting an updated OICD configuration into the database.
> 
> ```shell
> sudo /opt/firezone/embedded/bin/psql -U firezone -d firezone -p 15432 -h localhost -c "UPDATE configurations SET openid_connect_providers = '[{\"discovery_document_uri\":\"https://login.microsoftonline.com/xxxxxxxx/v2.0/.well-known/openid-configuration\",\"client_id\":\”xxxxxxxxxxx\",\"client_secret\":\”xxxxxxxxxxx\",\"redirect_uri\":\"https://xxxxxxxxxxx/auth/oidc/azure/callback/\",\"response_type\":\"code\",\"scope\":\"openid email profile offline_access\",\"label\":\"Microsoft\",\"id\":\"azure\"}]'"
> sudo firezone-ctl restart phoenix
> ```
> 
> Change placeholders accordingly and make sure to change the id (in my case `azure`) and part in the redirect_uri to the missing key from the error log: `(KeyError) key "azure" not found in: %{}`
> 
> **Explanation** It appears that the scheme of the OICD configuration has changed between versions 0.6.x and 0.7.x of firezone. Previously it was:
> 
> ```json
> {
>   "openid_connect_providers": {
>     "<provider key / id>" : {
>       "dummy": "xxxx"
>     }
>   }
> }
> ```
> 
> Now it appears to be:
> 
> ```json
> {
>   "openid_connect_providers": [
>     {
>       "dummy": "xxxx",
>       "id": "<provider key / id>"
>     }
>   ]
> }
> ```
> 
> I followed the upgrading guide and still, it was not migrated automatically. Maybe due to an error. The relevant command on the [troubleshooting page](https://github.com/firezone/firezone/blob/547b3bbf65befa3055c3341293ae55b09ca2c7e5/docs/docs/administer/troubleshoot.mdx?plain=1#L36) is also not valid anymore for versions higher than Firezone 0.7. I tried changing `{}` to `[]`, similar to my example from above, but this didn't help. Actually, when using `{}`, it results in an internal server error. When using `[]`, only the restart loop occurs.
> 
> In the end, the only way to fix it for me was to put the JSON configuration string directly in the database, as described above.

Thanks, confirmed that it worked for me too. There is a couple of quotes that are in the wrong format so if anyone else tries this they would need to be fixed.

**Comment by AndrewDryga** [comment]
@jeldriks is there any chance that you can share table `schema_migrations` and check if you have any errors during migrations for the upgrade? I'm asking because we have [a migration that should do this](https://github.com/firezone/firezone/blame/master/apps/fz_http/priv/repo/migrations/20221229154115_migrate_providers_configs.exs#L7) for you but somehow it's skipped.
