### ISSUE TITLE
0.7.5 loop redirect after upgrade

### ISSUE THREAD

**Issue by ihard** [CloudFire-LLC/cloudfire#1358]
I get loop redirect in Safari browser after upgrade from 0.7.3 to 0.7.5

```
19:35:50.873 [info] Migrations already up
19:35:55.346 [info] Password for user specified by ADMIN_EMAIL reset to DEFAULT_ADMIN_PASSWORD!
19:35:58.747 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
19:35:58.755 [info] Access FzHttpWeb.Endpoint at https://firezone.example.com
19:36:03.081 request_id=FzxqDGz2-LZGD5cAAAJh [info] GET /users
19:36:03.635 request_id=FzxqDGz2-LZGD5cAAAJh remote_ip=myip [info] Sent 302 in 554ms
19:36:03.697 request_id=FzxqDJINHCxRg-UAAAKR [info] GET /
19:36:03.721 request_id=FzxqDJINHCxRg-UAAAKR remote_ip=myip [info] Sent 302 in 23ms
19:36:03.773 request_id=FzxqDJaZLMigQ0wAAAKh [info] GET /users
19:36:03.776 request_id=FzxqDJaZLMigQ0wAAAKh remote_ip=myip [info] Sent 302 in 2ms
19:36:03.833 request_id=FzxqDJolE6qaVooAAALB [info] GET /
19:36:03.835 request_id=FzxqDJolE6qaVooAAALB remote_ip=myip [info] Sent 302 in 1ms
19:36:03.891 request_id=FzxqDJ2kNC30BMIAAALR [info] GET /users
19:36:03.895 request_id=FzxqDJ2kNC30BMIAAALR remote_ip=myip [info] Sent 302 in 3ms
19:36:03.945 request_id=FzxqDKDcff0z2t4AAALx [info] GET /
19:36:03.948 request_id=FzxqDKDcff0z2t4AAALx remote_ip=myip [info] Sent 302 in 2ms
19:36:04.006 request_id=FzxqDKRzwrDoyxgAAAMB [info] GET /users
19:36:04.008 request_id=FzxqDKRzwrDoyxgAAAMB remote_ip=myip [info] Sent 302 in 2ms
19:36:04.065 request_id=FzxqDKf8TWZn0MQAAAMh [info] GET /
19:36:04.066 request_id=FzxqDKf8TWZn0MQAAAMh remote_ip=myip [info] Sent 302 in 1ms
19:36:04.123 request_id=FzxqDKt1MQKnCRQAAAMx [info] GET /users
19:36:04.126 request_id=FzxqDKt1MQKnCRQAAAMx remote_ip=myip [info] Sent 302 in 2ms
19:36:04.177 request_id=FzxqDK6jhru6lWgAAANR [info] GET /
19:36:04.178 request_id=FzxqDK6jhru6lWgAAANR remote_ip=myip [info] Sent 302 in 1ms
19:36:04.235 request_id=FzxqDLIhB5zas_sAAANh [info] GET /users
19:36:04.237 request_id=FzxqDLIhB5zas_sAAANh remote_ip=myip [info] Sent 302 in 1ms
19:36:04.288 request_id=FzxqDLVOCqcsV5IAAAOB [info] GET /
19:36:04.290 request_id=FzxqDLVOCqcsV5IAAAOB remote_ip=myip [info] Sent 302 in 1ms
19:36:04.348 request_id=FzxqDLja9bKSuNMAAAOR [info] GET /users
19:36:04.350 request_id=FzxqDLja9bKSuNMAAAOR remote_ip=myip [info] Sent 302 in 2ms
19:36:04.407 request_id=FzxqDLxb_uQlz_wAAAOx [info] GET /
19:36:04.408 request_id=FzxqDLxb_uQlz_wAAAOx remote_ip=myip [info] Sent 302 in 1ms
19:36:04.467 request_id=FzxqDL_wKKcOC70AAAPB [info] GET /users
19:36:04.469 request_id=FzxqDL_wKKcOC70AAAPB remote_ip=myip [info] Sent 302 in 2ms
19:36:04.518 request_id=FzxqDML8zNUQCZcAAAPh [info] GET /
19:36:04.520 request_id=FzxqDML8zNUQCZcAAAPh remote_ip=myip [info] Sent 302 in 2ms
19:36:04.578 request_id=FzxqDMaSOBbuYbIAAAPx [info] GET /users
19:36:04.580 request_id=FzxqDMaSOBbuYbIAAAPx remote_ip=myip [info] Sent 302 in 1ms
```

before the update, I was logged in as a user who has configured 2fa

if open other browser - all good, run new login process 

Deleting cookie _fz_http_key in developer mode fixed the problem, but it doesn't look like a slick upgrade option and usually isn't what the average user would expect.

**Comment by AndrewDryga** [comment]
@ihard I'm sorry that your faced this issue, this is due to some changes in session storage. A simple fix, for now, is rotating your cookie encryption secret which will invalidate them for all users.

@jamilbk the issue is [here](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/live/hooks/live_mfa.ex#L10). 

I'm thinking about how we can make a fix that will make sure that something like this would never happen and an idea is to add a Firezone version as a suffix to all cookie encryption secrets. It means that on the release of a new version, all users will be unauthenticated. This is the most viable option because LiveView can't affect user sessions, so from that place where the bug lives we don't have a lot of options, even redirecting to `/sign_out` won't work because it's a `DELETE` method. 

That might be even good from a security perspective because if we fix something with authentication (eg. make it stronger) the users will need to follow a new login flow instead of staying authenticated.

WDYT?

**Comment by jamilbk** [comment]
@AndrewDryga sgtm. Have hit this once or twice before.

Maybe the session key could include some random hardcoded suffix string we could choose to update in PRs that affect sessions. But could be a pain to remember to update it… version works too.
