### ISSUE TITLE
0.7.5 - Next problems with SAML auth (Google) 

### ISSUE THREAD

**Issue by Insidek** [CloudFire-LLC/cloudfire#1362]
1. All users gets error 404 with response:

not_found

2. When you use icon from google apps list (default google page - right up corner 9 dots)- All users gets error 403 with response:

access_denied :idp_first_flow_not_allowed

**Comment by jamilbk** [comment]
Hi @Insidek, the `:idp_first_flow_not_allowed` is expected -- our SAML connector isn't configured to allow login initiated from the IdP. We're considering enabling / exposing that option, however. See #1117 

As for the `not_found` error: that will happen if you have `auto_create_users` disabled in the SAML connector configuration and the user does not currently exist in Firezone. Try either manually creating the user so that the email is found upon logging in, or enabling `auto_create_users` in your SAML connector config.

**Comment by Insidek** [comment]
Hi @jamilbk I have "Auto-create users" enabled.
![image](https://user-images.githubusercontent.com/22748563/214065012-ec148502-e56a-4c99-8715-8c8e9a1db84d.png)

**Comment by AndrewDryga** [comment]
@Insidek can you please reboot the Firezone and confirm that the issue persists? Just run `docker-compose down` and then start it again

**Comment by Insidek** [comment]
After docker-compose down and docker-compose up still gets error 404 "not_found".

**Comment by AndrewDryga** [comment]
At least that removed one of the suspects from my list, I'm investigating this further.

**Comment by AndrewDryga** [comment]
I was able to reproduce the issue, a fix is coming.

**Comment by AndrewDryga** [comment]
@Insidek just to confirm is the ID of your SAML provider `saml`? What happens if you change it to anything else?
