### ISSUE TITLE
Allow creating permit rules for OTP

### ISSUE THREAD

**Issue by basaran** [CloudFire-LLC/cloudfire#1366]
Would you consider adding a feature, so that users will be required to enter an OTP after peering to the wireguard server?

Under the rules category, a new section could be added as OTP rules. Here's an example flow:

1. When the user peers, they are given access to the local IP of the wg interface.
2. They visit the local wireguard ip, then they are shown to enter their OTP if they haven't already done so..
3. After the OTP is entered, they are permitted / denied according to how the OTP rules are configured. (allow access to management subnet xyz)

**Use case:**

This could help as it would prohibit anyone getting access to critical resources in case a user's wireguard configuration is leaked. On remote access and administration scenarios, this could be a valuable feature.

**Example**

There is already a project called [wag](https://github.com/NHAS/wag) that does something similar for OTPs.

**Comment by AndrewDryga** [comment]
Hey @basaran, I think this feature is viable but will be approached in a slightly different way. We are working on shipping our own apps for most of the platforms and once we have them we could add something like this to the app UI.

**Comment by basaran** [comment]
Entering the OTP via native applications will be great too, but for limited environments it might still be beneficial to have an option to visit a URL.

It might also possible to insert some shell scripting to `dispatcher.d` to pop the OTP browser tab.

**Comment by jamilbk** [comment]
@basaran See https://github.com/firezone/firezone/issues/689 for more discussion on a similar feature -- captive portal.

If the config leaks you'll want to invalidate it and generate again, otherwise the peer using the leaked config would be able to essentially cause a DoS for the legitimate peer. This is because WireGuard updates the peer's `Endpoint` (as seen by the server) dynamically based on the peer's remote IP. Two valid peers with different remote IPs attempting to handshake with the server will cause neither to complete.

We do have a VPN session expiration feature but it suffers from the same issue outlined above.

<img width="723" alt="Screenshot 2023-02-01 at 4 18 23 PM" src="https://user-images.githubusercontent.com/167144/216199227-d921b646-6986-45d7-957b-9e6e58dd4c09.png">

I've opened #1236 for making this a config expiration feature.

Client apps will be a better place for handling authentication factors. In this case, WireGuard configs will be ephemeral and persist only for the lifetime of the authentication session from your IdP.
