### ISSUE TITLE
[Request]: Can add postgresql backup tool?

### ISSUE THREAD

**Issue by linuxperf** [CloudFire-LLC/cloudfire#1380]
I want to backup firezone data. Can add this feature? Thank you.

**Comment by AndrewDryga** [comment]
Hey @jinqinghui, since you have a PostgreSQL in your docker-compose you can do pretty much anything with it directly, but we don't handle backups for self-hosted instances - it's a lot of work and there are a lot of options on how backups should work depending on the deployment environment.  Here is a good guide on how to do that: https://www.enterprisedb.com/postgresql-database-backup-recovery-what-works-wal-pitr

However, we do help to set them up for Enterprise customers, you can reach our sales here - https://www.firezone.dev/contact/sales.
