### ISSUE TITLE
Network IPs address range documentation

### ISSUE THREAD

**Issue by lgpasquale** [CloudFire-LLC/cloudfire#1429]
There is no mention in the documentation of what the default network address range is and how to change it.

The `.env` file created by `gen-env` creates the following snippet:
```
# The ability to change the IPv4 and IPv6 address pool will be removed
# in a future Firezone release in order to reduce the possible combinations
# of network configurations we need to handle.
#
# Due to the above, we recommend not changing these unless absolutely
# necessary.
WIREGUARD_IPV4_NETWORK=100.64.0.0/10
WIREGUARD_IPV4_ADDRESS=100.64.0.1
WIREGUARD_IPV6_NETWORK=fd00::/106
WIREGUARD_IPV4_ADDRESS=fd00::1
```
which makes it seem like these are the default values.

These env variables, however, are not documented in the [Environment Variables docs](https://docs.firezone.dev/reference/env-vars/).

Judging by the comment in the snippet and the lack of documentation for these variables, you would assume they are no longer supported (even though the still work).

Surprisingly, if you don't specify these variables, the default network used is `10.3.2.0/24` (and not `100.64.0.0/10`). Addresses mentioned in the [Reverse Tunnel use case](https://docs.firezone.dev/user-guides/use-cases/reverse-tunnel/) seem to imply this is the network range, but make no mention of it explicitely.

If you want to assign a static *Tunnel IPv4 Adress* to a client, the documentation leaves you with no clue as to what the valid range is.

It would be nice if the documentation mentioned what the default network is and how to change it.
Can there be separate ranges for addresses assigned automatically and static addresses (to prevent clashes)? I can create a separate issue for this if needed.

As a side note, I find it worrying that we won't be able to set the network range in the future.

**Comment by AndrewDryga** [comment]
Hello @lgpasquale, thanks for a very detailed issue 👍. 

The configuration options are removed from the docs because we are going to change the range moving to a CGNAT, old values (that you will get if you don't set `WIREGUARD_*` variables) are for backward compatibility so that we won't break installation for people that are already relying on the old range.

I will keep the issue open to change the docs and mention CGNAT range explicitly and that it can't be changed to make it less ambiguous in the future.

**Comment by ap-andersson** [comment]
Just a question out of curiosity. What is the reason to use CGNAT (which is the 100.X ips right?) instead of any random local configured IP range? Can there be any problems by using those always? Will the subnet etc be configurable within the range or will everything to do with IPs be set in stone? I assume since it's inside docker the ips doesn't really matter?

**Comment by bob3000** [comment]
Hi @AndrewDryga 
currently I have to configure the WG network in firezone. As you mentioned it still works with the `WIREGUARD_IPV4_NETWORK` environment variable. I was wondering though what the future proof way to configure the network would look like in practice. Could you give me a hint?

**Comment by jamilbk** [comment]
The reason we're using CGNAT for peer IPs is because it greatly reduces the chance for collision with end-users local networks. In 1.0 (which features a cloud-managed portal and leverages our own custom clients) this is not configurable -- we issue CGNAT IPs to all connected clients automatically, and their routing table will be updated with granular `/32` entries in the off-chance that the device is actually on a CGNAT network itself.
