### ISSUE TITLE
IP CIDR Lists instead of Single IP Address in Tunnel IPv4/6 Address Field

### ISSUE THREAD

**Issue by JakeFrosty** [CloudFire-LLC/cloudfire#1548]
**Is your feature request related to a problem? Please describe.**
It seems like firezone only supports single addresses at the moment as I've observed in the database schema
The problem with this is with special use cases where people might want to create configs that will turn a wireguard peer into a subnet router AKA a site to site vpn configuration

**Describe the solution you'd like**
If it's possible, maybe take into consideration a cidr list instead of inet?

**Describe alternatives you've considered**
An example solution I used temporarily is using https://github.com/ngoduykhanh/wireguard-ui since it allows me to add CIDR lists
instead of being limited to a single IP address

**Additional context**
ngoduykhanh/wireguard-ui:
![image](https://user-images.githubusercontent.com/55770933/231106628-8cdfe297-4d6e-4bb2-b98c-4a15b2a3a851.png)

Firezone:
![image](https://user-images.githubusercontent.com/55770933/231105702-017ef454-4055-4de0-a7af-710c0528e1f2.png)

**Comment by jamilbk** [comment]
Thanks for the request. We're undergoing lots of restructuring at the moment so not sure when we'll get to this, but see https://github.com/firezone/firezone/issues/567

**Comment by jamilbk** [comment]
Closing as not planned. With 1.0 this use case will largely be fulfilled via multiple Gateway instance groups and custom clients.

**Comment by lanrat** [comment]
I also have this use-case.

Will firezone 1.0 gateways work with vanilla wireguard clients as the gateway?

I use the same [/wireguard-ui](https://github.com/ngoduykhanh/wireguard-ui) mentioned above with routers that support acting as wireguard clients as my gateways. All vanilla wireguard which is a hard requirement for me.

So many new networking products support plain wireguard, it would be important to ensure they can act as gateways too.

**Comment by jamilbk** [comment]
@lanrat Thanks for the input. We're focused on the remote access use case for now. All WG keys in 1.0 are ephemerally generated _not written to disk_, and are authenticated by a user (via IdP) or service account (via token). We made an architectural decision to drop support for static WireGuard configs due to the difficulty in managing / rotating them.

**Comment by lanrat** [comment]
I understand the difficulty in changing and rotating configs. Wireguard does not handle this well.

That being said, I especially like firezone because it is plain wireguard with a GUI for making firewall rules. There are already lots of other services built on top of wireguard but require custom clients in this space (tailscale, headscale, netmaker, etc..) This was a good differentiator for firezone and why I am considering migrating to it.

Just sharing for you to consider for your roadmap. Either way its a great product.

Thanks.
