### ISSUE TITLE
The TLS_OPTS variable is missing

### ISSUE THREAD

**Issue by T-baby** [CloudFire-LLC/cloudfire#1620]
When using the following command to generate the.env file, the TLS_OPTS variable is missing. And https will be automatically enabled in docker-compose file, which will result in https access blocked forever.

```shell
docker run --rm firezone/firezone bin/gen-env > .env
```

The following variables can be used when configured in the.env file.

```
TLS_OPTS="tls {
on_demand
}"
```

**Comment by laweschan** [comment]
this is not a bug.
I think you should read the install.sh carefully, the function promptACME has asking about the parameter, and it will use in TLS_OPTS.

if you require manually update .env file and include default TLS_OPTS , you can simply rewrite the script and assign the value you want

running a command without follow the logic in script, of course you won't get the result.

**Comment by T-baby** [comment]
Hi, I installed it according to the manual installation steps in the documentation, which does not explain this step in the documentation, suggest to modify the documentation.

**Comment by laweschan** [comment]
agree but it also very hard to explain each function in documentation, it should be in development rather than deployment,.

I can confirm that running the script (up to 0.7.29) by default can get firezone up and running, and I also suggest dig in the install script to found out the deployment option, it can help to understand much more control.

I have rewrite it since I am using podman container instead of docker, it is a difficulty path but also an interesting path
you can provide your understanding to documentation in future, just like I also share the change in podman deployment script.

or you can change the bug to suggestion tag

**Comment by T-baby** [comment]
I can't change the bug to suggestion tag, lol.
