### ISSUE TITLE
Support user IDs other than `1000` for containerized deployments

### ISSUE THREAD

**Issue by moan0s** [CloudFire-LLC/cloudfire#1642]
**Describe the bug**

**To Reproduce**
Start firezone as docker container with `--user998:1000`, watch the log, container crashes

**Expected behavior**
Firezone starts

**Screenshots / Logs**
```
May 31 19:42:53 s3 systemd[1]: Starting Firezone VPN (mash-firezone)...                                                    May 31 19:42:53 s3 mash-firezone[1762203]: b733030e2a8af144803ecc966835f696434c343bfb445c235fbf9c2ccd3f73f7                May 31 19:42:53 s3 systemd[1]: Started Firezone VPN (mash-firezone).
May 31 19:42:54 s3 mash-firezone[1762221]: Creating WireGuard interface wg-firezone
May 31 19:42:54 s3 mash-firezone[1762221]: ip: RTNETLINK answers: Operation not permitted

```

**Platform (please complete the following information):**
 - Firezone Versio: `0.7.30`
 - OS: Linux
 - Distro: Ubuntu
 - Kernel version:  5.15.0-71
 - Deployment method: Docker

**Additional context**
This issue is heavily related to #1506 and hinders some users in deploying firezone securely https://github.com/mother-of-all-self-hosting/ansible-role-firezone/issues/1

**Comment by jamilbk** [comment]
Thanks for the report! We haven't tested running the Firezone container as a different user. I suspect user `998` doesn't have the necessary permissions to run the `ip` bootstrap commands. I'm not sure this is a bug in Firezone per se.

The fix would likely involve either adding that user to the appropriate group on the host system or otherwise enabling the user to add interfaces and modify routes. I'm not sure the `cap_add` in `docker-compose.yml` helps with that.

We probably won't have a chance to deep dive on this soon but happy to review/accept a PR if it comes along.

**Comment by jamilbk** [comment]
The 1.0 portal will be cloud-managed, so this issue would only pertain to the data plane components (Gateways and Relays) going forward. I'll modify the title a bit to stay relevant.

**Comment by jamilbk** [comment]
Will not be able to prioritize in the near term
