### ISSUE TITLE
Can't seem to install

### ISSUE THREAD

**Issue by thecrazytech1** [CloudFire-LLC/cloudfire#1657]
**Describe the bug**
when I run the automatic docker install script, Its unable to create the network because of this error: `failed to create network firezone_firezone-network: Error response from daemon: Pool overlaps with other one on this address space`

**To Reproduce**
Try to install firezone

**Expected behavior**
It should be able to make the network

**Screenshots / Logs**
N/A

**Platform (please complete the following information):**
 - Firezone Version [latest - 0.7.30]
 - OS: [Linux]
 - Distro: [Debian GNU/Linux 11 (bullseye)]
 - Kernel version: [5.15.84-v8+]
 - Deployment method: [Docker]

**Additional context**
N/A

**Comment by jamilbk** [comment]
Thanks for the report @thecrazytech1.

Is this a fresh Debian 11 install? Do you have other Docker containers running on the machine? If so you may have a network conflict and need to change the firezone network from in your `$HOME/.firezone/docker-compose.yml`. You'll need to make changes in the following places:

- https://github.com/firezone/firezone/blob/edee0726f93f5b483015c63662d6bd5d252fab8a/docker-compose.prod.yml#L34
- https://github.com/firezone/firezone/blob/edee0726f93f5b483015c63662d6bd5d252fab8a/docker-compose.prod.yml#L68
- https://github.com/firezone/firezone/blob/edee0726f93f5b483015c63662d6bd5d252fab8a/docker-compose.prod.yml#L99

**Comment by thecrazytech1** [comment]
> Thanks for the report @thecrazytech1.
> 
> Is this a fresh Debian 11 install? Do you have other Docker containers running on the machine? If so you may have a network conflict and need to change the firezone network from in your `$HOME/.firezone/docker-compose.yml`. You'll need to make changes in the following places:
> 
> * https://github.com/firezone/firezone/blob/edee0726f93f5b483015c63662d6bd5d252fab8a/docker-compose.prod.yml#L34
> * https://github.com/firezone/firezone/blob/edee0726f93f5b483015c63662d6bd5d252fab8a/docker-compose.prod.yml#L68
> * https://github.com/firezone/firezone/blob/edee0726f93f5b483015c63662d6bd5d252fab8a/docker-compose.prod.yml#L99

It's not a fresh install, I am fairly new to networking in general. what would I change those to?

**Comment by jamilbk** [comment]
You should be able to use any [RFC1918](https://en.wikipedia.org/wiki/Private_network) pool that doesn't conflict with another subnet on that host. Perhaps try `10.99.99.0/24` instead of `172.25.0.0/16` and `10.99.99.100` instead of `172.25.0.100`.

**Comment by thecrazytech1** [comment]
I will try that and get back to you

**Comment by UncleJ4ck** [comment]
Hi, i don't wanna start a new issue based on a stupid newbie question, it seems the issue here is kinda similar to mine, im trying to install firezone and deploy the web ui on localhost, my situation is im using an external server connected to it using ssh and i used the automatic installation, i used https://www.duckdns.org/ for a DNS record, but it's not working, i read the docs, i found out that firezone enforce HTTPS, i tried to create a self hosted certificate for this domain but it's not working also, can you help me or give me a documentation about deploying firezone in localhost please ?

**Comment by jamilbk** [comment]
@UncleJ4ck Your issue is unrelated -- I'd recommend asking on in our community [Slack](https://join.slack.com/t/firezone-users/shared_invite/zt-19jd956j4-rWcCqiKMh~ikPGsUFbvZiA) or [forum](https://discource.firez.one), and if it's not solved there, opening an issue here with more details and steps to reproduce so we can troubleshoot. Caddy will should provision a cert on-demand for you if you're using accessing Firezone at the same `EXTERNAL_URL` as you entered upon installation.
