### ISSUE TITLE
Force user or group of user to setup an MFA 

### ISSUE THREAD

**Issue by TOMCO984** [CloudFire-LLC/cloudfire#1696]
The feature is quite simple to explain.
Add the possibility to force user to setup and use a MFA.
Admin can configure it in user setting on in group settings if groups were added to firezone.

**Comment by merclyn** [comment]
This is crucial for any kind of business use case without using external 2FA service. 
Most end users will not activate 2FA for access to corporate resources unless they are forced to.
firezone doesn't even provide view of if users have 2FA enabled in the rest interface which makes any external enforcement difficult or impossible. Would be nice to show last password change timestamp too so this can be enforced as well.
The lack of this is what is stopping many from deploying in any corporate environment. its great for home use though.

**Comment by jamilbk** [comment]
We are moving away from implementing local password-based authentication flows ourselves in order to avoid storing passwords and handling the all of the complex logic required to perform secure local auth with MFA. This is notoriously difficult to get right, so rather than and try and reinvent the wheel here, we recommend using an external identity provider instead to enforce authentication policies.

There are self-hosted, open source options that work well with Firezone, like [Keycloak](https://keycloak.org), [Authentik](https://goauthentik.io), and [Zitadel](https://zitadel.com/)

**Comment by TOMCO984** [comment]
Hi @jamilbk,
Yes but if we have Keycloak behind the VPN we cannot access Keycloak to connect to Firezone :/
If you setup the ACLs by device/group it can be a solution to allow access only to keycloak and when we are connected to Keycloak we can switch vpn tunnel.
Or adding the possibility to access somes IP when isn't connected and when the session start it give full access to configured ACLs
