### ISSUE TITLE
Switch to `main` as main branch

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#1726]
With the announcement of 1.0, it might be a good idea to get back to working off our main branch to reflect our new direction.

- [x] Rename `master` to `legacy`
- [x] Rename `cloud` to `main`
- [x] Update README.md to reflect 1.0 with updated content and Under Construction™ status
- [x] Update CI workflows, scripts to use `legacy` vs `master`
- [x] Update CI workflows, scripts to use `main` vs `cloud`
- [ ] Update component licenses
- [x] #1747
- [x] #1746
- [x] Remove dotfiles no longer relevant; general cleanup
- [x] Merge `cloud` into `master` (maintain website)
- [x] Re-enable Vercel Preview deployments

Fixes #1304 

Any thoughts/objections @AndrewDryga

**Comment by AndrewDryga** [comment]
I think there are two more tasks to merge it:
- [ ] Copy the new website folder to `cloud` before merging.
- [ ] Configure release drafter for the `cd` pipeline to start building containers with tags.

I would name the legacy branch `0.7` for transparency rather than `legacy` so that people can find it if they want to. Other than that, we should be good.

**Comment by jamilbk** [comment]
> I would name the legacy branch 0.7 for transparency rather than legacy so that people can find it if they want to

Was thinking this too. K. I may take a stab at this over the weekend since it'll be a big blocker for everyone.

**Comment by jamilbk** [comment]
Ended up going with `legacy` since that will age better in case need to cut a 0.8.
