### ISSUE TITLE
Firezone container restarting indefinitely

### ISSUE THREAD

**Issue by SandeshSKrishnan** [CloudFire-LLC/cloudfire#1792]
**Describe the bug**
Firezone container restarting

**To Reproduce**
Install Firezone using the automatic script and follow the steps to complete the installation.

**Expected behavior**
Firezone should work as usual.

**Screenshots / Logs**
![image](https://github.com/firezone/firezone/assets/69599992/7cadbf7c-0f60-480f-a58d-e98b78b1b423)

Platform used:
 - Firezone Version: latest
 - OS: Linux
 - Distro: Amazon Linux
 - Deployment method: Docker

I've been trying to get Firezone to work under an nginx reverse proxy and succeeded using resources such as https://discourse.firez.one/t/caddy-in-reverse-proxy-and-nginx-as-front-end/523/2 and https://github.com/jitsi/infra-configuration/blob/main/ansible/roles/firezone/templates/docker-compose.yml.j2 but I had to remove it and start over once again for some reason.

Now while retrying, I had the above mentioned issue and I thought it was something regarding the nginx and I had a different ec2 instance with a valid DNS record so I thought of trying out the automatic install script on that instance. I faced the same issue there as well.

Now as we're using the latest version of firezone in the docker-compose, I even tried using the last stable version docker [firezone/firezone:0.7.32] in the docker-compose to check if that would change anything. But that too resulted in the same error.

**Comment by jamilbk** [comment]
Looks like you reset your `.env` vars containing the `DATABASE_ENCRYPTION_KEY` but kept the DB, so the encrypted fields are not decryptable anymore. See this:

https://www.firezone.dev/docs/administer/regen-keys#regenerate-secrets

If you backed up the old `DATABASE_ENCRYPTION_KEY`, simply restore that to `~/.firezone/.env`, otherwise, you'll most likely need to start with a fresh database.
