### ISSUE TITLE
How can we avoid requiring the local interface IP as a parameter?

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#1886]
Explicitly setting address is not an option for some of the environments, for example, in k8s it would be hard to extract that information. Even on VMs [we have hacks for that](https://github.com/firezone/firezone/blob/main/rust/docker-init.sh#L13).

@conectado you mentioned that you have an idea on how to solve it?

**Comment by thomaseizinger** [comment]
Several things to consider:

- We must separate listening on IP4 and IP6. Internally, the relay needs to be able to explicitly send a packet via IP4 or IP6. I think the only way to do this is to have two sockets.
- We should not listen on interfaces that are not externally reachable because traffic coming in via those is not relay traffic.

I believe it is not possible to reliably tell whether a socket will listen on both IP4 & IP6 or not when given a wildcard address. I think that is OS and kernel-configuration dependent.

What we do in libp2p is iterating all our network interfaces and getting each IP individually.

To make configuration easier, we can optimise for the case where we only have a single interface. Then the provided public IP address can be used to infer that we should listen on an interface for the given IP family.

For example, given a public IP4 address, we can iterate all interfaces and if we only find one, listen on that one with its IP4 address (assuming it is not loopback).

If we have two or more interfaces, we'd still have to require the user to pass us, which interface we should listen on.

Does that sound like a good improvement? It should make the case of deploying on GCP easier because I'd assume that we only have a single interface there.

**Comment by jamilbk** [comment]
@thomaseizinger Just chiming in on the assumption that there's only one interface -- on EC2 there is two I believe by default. Are we looking for the default egress interface? If so, we can [grab it like so](https://github.com/firezone/firezone/blob/legacy/omnibus/cookbooks/firezone/recipes/network.rb#L35):

```
ip route show default 0.0.0.0/0 | grep -oP '(?<=dev ).*' | cut -f1 -d' '
```

Then we can just pull the IPv4 and IPv6 off it, and maybe print a log statement to that effect. I agree that we should allow the user to explicitly set these to override this logic.

**Comment by thomaseizinger** [comment]
> @thomaseizinger Just chiming in on the assumption that there's only one interface -- on EC2 there is two I believe by default. Are we looking for the default egress interface? If so, we can [grab it like so](https://github.com/firezone/firezone/blob/legacy/omnibus/cookbooks/firezone/recipes/network.rb#L35):
> 
> ```
> ip route show default 0.0.0.0/0 | grep -oP '(?<=dev ).*' | cut -f1 -d' '
> ```
> 
> Then we can just pull the IPv4 and IPv6 off it, and maybe print a log statement to that effect. I agree that we should allow the user to explicitly set these to override this logic.

Thanks for the input! Are there two default that are not loopback interfaces?

**Comment by conectado** [comment]
@thomaseizinger 
> Several things to consider:
> 
> * We must separate listening on IP4 and IP6. Internally, the relay needs to be able to explicitly send a packet via IP4 or IP6. I think the only way to do this is to have two sockets.

Using the flag `IPV6_V6ONLY` we can bind to `0.0.0.0` and `::` the ipv4 socket and the ipv6 socket correspondingly (we area already using this flag). 

> * We should not listen on interfaces that are not externally reachable because traffic coming in via those is not relay traffic.

I don't think we care if we get irrelevant traffic, it'll be just discarded.

> I believe it is not possible to reliably tell whether a socket will listen on both IP4 & IP6 or not when given a wildcard address. I think that is OS and kernel-configuration dependent.

I reefer to [ipv6](https://man7.org/linux/man-pages/man7/ipv6.7.html) `IPV6_V6ONLY`  flag documentation.

**Comment by thomaseizinger** [comment]
> @thomaseizinger 
> > Several things to consider:
> > 
> > * We must separate listening on IP4 and IP6. Internally, the relay needs to be able to explicitly send a packet via IP4 or IP6. I think the only way to do this is to have two sockets.
> 
> Using the flag `IPV6_V6ONLY` we can bind to `0.0.0.0` and `::` the ipv4 socket and the ipv6 socket correspondingly (we area already using this flag).

Okay, so you are suggesting to bind to wildcard using this flag and just ignore all other traffic?
