### ISSUE TITLE
connlib: client log file uploader

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2020]
Timer-based system to do the following every X seconds (default to hourly since that is our rotation interval):

1. Request `log_url` from portal over the control plane connection to the portal. This is a GCP storage url that can be used for a limited time to POST log files to. See #2019  -- this will require a new control plane message type.
2. Upload any log files found in `log_dir`, and remove them upon successful response.
3. Sleep

X should be a build-time parameter

**Comment by thomaseizinger** [comment]
The current version of this in #2103 has a custom appender that can roll over on-demand and not just time-based. Currently, it is triggered in a time-based way by requesting the URL using a timer from the portal.

Why don't we flip this around and have the portal actively push a message a la "Upload your logs now"? Whether or not the portal triggers this on a timer or using a button click doesn't matter, right? I think this could be a cool feature to add. Instead of having to wait for the configured interval to trigger on some user's device, we could just request them instantly.

Thoughts @jamilbk @AndrewDryga @conectado?

**Comment by jamilbk** [comment]
@thomaseizinger Yeah we had discussed quite a few approaches initially (including requesting from portal like @AndrewDryga originally suggested) and settled on letting the client determine when to send logs for a couple reasons:

- The portal's timers aren't necessarily stable and might often reset, i.e. if we continuously deploying
- We may want to factor in device battery life, storage space, or number / severity of failures, or connectivity environment triggers to determine when to send logs
- #2018 and #2017 implement an on-demand option (and serves as backup if the user's device cannot reach GCP object storage)

I think it could be useful for active debugging sessions with high-profile or enterprise customers, but let's stick with this implementation for v1 and add a pin in this to iterate on later. I'm sure we'll have other improvements to make to logs after seeing how this approach works.
