### ISSUE TITLE
User device limit and/or disabling user logging in

### ISSUE THREAD

**Issue by NekoiNemo** [CloudFire-LLC/cloudfire#2049]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to limit the amount of devices a single user can create, nor is there a way to make a user who is unable to login themselves and only receives their configs through an administrator. This creates a security issue as should the account be compromised - the malefactor could create large amounts of devices under the compromised user. This is particularly troublesome with the IT-illiterate (such as family members in domestic use) or untrusted (contractors in enterprise environment) users.

**Describe the solution you'd like**
* A per-user setting controlling the maximum amount of devices they are allowed to have (possibly ignored when device is created by an administrator rather than an unprivileged user?)
* An account flag allowing to disable the login and recovery/magic link features for the user (ideally it should be a flag that can be changed at runtime and not a type of an account assigned at creation only)

**Describe alternatives you've considered**
The current alternative is to either create a user with long password (or break the password hash in the DB), which gets bypassed via the recovery, or to use an invalid fake email address as the username, which is less than ideal for user identification in absence of name/comment fields on user accounts.

**Comment by jamilbk** [comment]
Thanks for the report! We likely won't get to this for the 0.7 release, and 1.0 makes this largely irrelevant because it uses our own Firezone clients which require user authentication on each device.

Creating and saving static configurations is inherently problematic as they are static -- the keypairs must persist on both sides of the tunnel for long periods of time to be usable. With our custom clients we generate keypairs on the fly for each authentication session, making this issue largely irrelevant going forward.
