### ISSUE TITLE
Add `Sunset` and `Deprecation` headers to portal endpoints

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2203]
Deprecated endpoints should return some kind of Deprecation header (see https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-deprecation-header). Clients should parse that and render an appropriate message to the user that they are using a client version that appears to be outdated.

We can announce removal of endpoints with Sunset headers: https://www.rfc-editor.org/rfc/rfc8594#section-1.4. Similarly to deprecations, clients should parse that and issue appropriate messages to the user.

Refs #2041

**Comment by AndrewDryga** [comment]
This is applicable to REST API, for websockets there is no "deprecated endpoint" since it's only one of them (WSS) and there is no point in waiting for a client to hit some deprecated message either. We know the client version from the User-Agent when can broadcast "outdated_client: bool" as part of the `init` response message proactively.

For some time, I would try to force users to upgrade more often so that we don't need to come up with creative ways to make WebSockets backward-compatible, it won't be as trivial as doing so for REST endpoints.

**Comment by jamilbk** [comment]
👍
