### ISSUE TITLE
Update sign in page for clients

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2299]
When a client signs in, the copy and links on the page don't quite make sense:

![pixel_phone_auth](https://github.com/firezone/firezone/assets/167144/a5bf7f43-7389-4ad7-aa8e-9e20bdce0bbd)

It might be better to show "Sign into `account.name`"

**Comment by AndrewDryga** [comment]
Alternatively, we can roll back recent changes to it and redirect users depending on their role either to the admin portal or to some "user area" which will explain that they need to use an app if they accidentally got there. I think it will be a simpler one because we won't need to have two sign-in forms to maintain.

**Comment by AndrewDryga** [comment]
Adding to my point above: the reason to design it like it in the first place was that we will have some unprivileged user zone anyway. At the very least we will have to show active clients and sessions and allow users to terminate them.

**Comment by jamilbk** [comment]
> we can roll back recent changes to it and redirect users depending on their role either to the admin portal or to some "user area" which will explain that they need to use an app if they accidentally got there.

Could you give an example of a user arriving at the dashboard page by accident? I guess I'm not understanding how this removes the need to have two styles of the sign in page.

> we will have some unprivileged user zone anyway.

That's not on the roadmap, and I wouldn't feel comfortable adding it unless requested by customers just in order to keep our unprivileged portal surface as small as possible.

Perhaps it makes sense just to have two signin paths as well, since sessions will be segregated. Also makes setting segregating the Admin dashboard and Connlib session cookies easier, since you could scope them to the path. And we could prevent unprivileged users from authenticating to the admin portal sign in page altogether.

**Comment by AndrewDryga** [comment]
> Could you give an example of a user arriving at the dashboard page by accident?

It's very common that links to the login form will be shared in some docs or via Slack, or they can just copy-paste their tenant URL into a browser.

> I guess I'm not understanding how this removes the need to have two styles of the sign in page.

We should remove recently added content:
```
Don't have an account? [Sign up here.](https://app.firez.one/sign_up)
Meant to sign in from a client instead? [Read the docs.](https://firezone.dev/docs)
```

1. It's incorrect to point from a sign-in page of a tenant (where the user logs in) to a sign-up page of the Firezone (where a company will create an account);
2. "Meant to sign in from a client instead?" kind of message can be shown after logging in as a regular user, this will only require a simple page for now.

So all we really have to do is rollback one commit and make a page for a regular signed-in user look a little bit better, which later we can improve if needed.

And if you really want to keep "Meant to sign in from a client instead?" message then we can conditionally hide it if `client_platform` parameter is set.

> That's not on the roadmap, and I wouldn't feel comfortable adding it unless requested by customers just in order to keep our unprivileged portal surface as small as possible.

I don't suggest adding it now, but seeing and closing other active sessions is a very common security best practice, so I feel like we will end up implementing it sooner than later.

> Perhaps it makes sense just to have two signin paths as well, since sessions will be segregated. Also makes setting segregating the Admin dashboard and Connlib session cookies easier, since you could scope them to the path. And we could prevent unprivileged users from authenticating to the admin portal sign in page altogether.

First of all, we can't easily split sessions by cookie path right now. It's pretty complex because for each tenant you can either use UUID or account slug in the URL, and there can be only one path for a cookie. We can maintain two cookies but this will make everything just much more complicated.

We can't remove one of them: for IdP callback URLs we use UUID (so that if the tenant ever changes you won't need to reconfigure all IdP connections) and the rest are using account slug (for usability).

If we support any kind of custom domain names this will make the matter even more complicated.

Second, we will prevent unprivileged users from authenticating the admin portal anyway, splitting cookies by path is not a security measure - malicious actors can always edit those and try to reuse user sessions for the admin portal path. We will have all our tokens color-coded for that and we simply won't allow sessions access something they are not intended for.

Third, having two sign-in flows will increase maintenance costs (more code to support, and if we hotfix something you kinda always have to check both places or at least tests for both flows) and make UX worse (we will need to add a link "want to log in as admin" and "want to log in as user" to the forms to deal with people trying to use a wrong form).

**Comment by jamilbk** [comment]
I see your points. The scenario I’m hoping to prevent would be:

- Admin logs in to admin portal
- Admin then logs into client app
- Portal session is now extended by (or otherwise influenced by) client app login

**Comment by jamilbk** [comment]
> > Could you give an example of a user arriving at the dashboard page by accident?
> 
> It's very common that links to the login form will be shared in some docs or via Slack, or they can just copy-paste their tenant URL into a browser.

You’re right — the link will be shared, but mostly among administrators some of which haven’t been granted admin role yet. In that case we will incorrectly tell them to log in via a client instead. Should just be “authentication incorrect” or “permission denied”.

This is why I think we can’t assume where a user is _trying_ to log into. They are two separate auth contexts, why not keep them segregated?

On that note, we’ll also need separate last signed in fields for each context as well. This will be required for #1983

**Comment by jamilbk** [comment]
@AndrewDryga let’s hop on a call tomorrow after standup to hash this out a bit more. Will be faster.
