### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2309]
- [ ] Add unit tests to the Android application to sanity check
- [ ] Add code coverage reporting

Related: #2310

**Comment by jasonboukheir** [comment]
According to the Android developer docs, here are some of there recommended dependencies:

```gradle
dependencies {
  // Required -- JUnit 4 framework
  testImplementation "junit:junit:$jUnitVersion"
  // Optional -- Robolectric environment
  testImplementation "androidx.test:core:$androidXTestVersion"
  // Optional -- Mockito framework
  testImplementation "org.mockito:mockito-core:$mockitoVersion"
  // Optional -- mockito-kotlin
  testImplementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlinVersion"
  // Optional -- Mockk framework
  testImplementation "io.mockk:mockk:$mockkVersion"
}
```

Mockito and Mockk are used for mocking.
Robolectric is used for UI testing and tests requiring Android Framework.

I think we should start with this list of references since that is what most Android developers will be comfortable with. Regarding Hilt, the android docs suggest using it for integration/e2e tests (more related to the sanity check tests). https://developer.android.com/training/dependency-injection/hilt-testing

**Comment by jasonboukheir** [comment]
Doing some more research and testing ...

There is a way we can do something called "Instrumentation Tests" using an Android emulator in Github Actions: https://github.com/marketplace/actions/android-emulator-runner. These are tests that run on an Android device. This is probably more useful for #2311 

However, we can do actual unit testing on the runner without an emulator by using the Robolectric library. This lib provides a usable stub of the Android Framework. Testing this way, is much faster since it doesn't require starting up an emulator.

For this Unit Testing issue, we're going to want Robolectric.

**Comment by jamilbk** [comment]
Roboelectric would be more appropriate for Integration Tests (tests all the user views navigate appropriately without crashing)
