### ISSUE TITLE
Cloud Dev environment

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2488]
Refs #2477 

If `staging` is going to closely follow `prod`, it would be good to have a dev environment that devs can build and run regression tests against.

E.g.

`dev.firezone.dev`

**Comment by jamilbk** [comment]
Per @bmanifold it would be good to get this up sometime before we grow too much as it might be a pain to migrate data / config from `staging` later on.

**Comment by AndrewDryga** [comment]
Why do we assume that staging will follow prod **closely**? What will be the difference between staging and development environments?

**Comment by jamilbk** [comment]
I think the thinking around this was that `staging` would be where production builds are tested, QA is performed, and generally remain a stable environment so that hotfixes could be rolled out in the clients, and `dev` would be where new features or potentially breaking things are built/tested, since we don't have a feasible offline/local dev env.

This issue was created from a discussion this morning around how much (if any) QA to perform on `prod`. I think the consensus was we can kick this can down the road.

**Comment by bmanifold** [comment]
Agree with what @jamilbk said.

What I had mentioned was that I had previously ran in to issues where the environment that started as my team's `qa` ended up being everyone else's `dev` instance, so we got stuck in a position where we weren't really able to do certain things in our `qa` environment, because it would then cause an outage for all of the other teams in the company and they'd have to halt development.

**Comment by AndrewDryga** [comment]
I don't mind having `dev` in the future (we can easily roll out it with Terraform) but I feel like having more environments than we have developers is a bit premature. I'd suggest running with staging for everything as long as we don't have serious issues with it, let time show us when the time is right to invest into it.

My experience with small teams is that everyone uses either staging or dev, whatever is more natural for a team to collaborate on. The other one dies and because nobody cares about it just becomes a source of confusion (something doesn't work when you push code there because it was broken for a while and nobody cared), so additional environments just become a maintenance routine.

**Comment by jamilbk** [comment]
I think we’re all in consensus, removing milestone to deprioritize
