### ISSUE TITLE
Select subset of Relays to return to client

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2499]
Based on RFC findings from @conectado, it appears that we only want to send 2-5 Relay candidates to clients. In the portal we need to select only a handful out of the total available Relays instead of sending them all down.

@AndrewDryga How do we document this? Should the selection be deterministic, or random? If deterministic, we probably need some UI controls, so maybe we stick with random to start with.

**Comment by AndrewDryga** [comment]
I think it will be more appropriate to have connlib to pick the relays. It won't save traffic but the protocol will not change and client later can implement something smarter than random candidate selection.

As for the algo, random is good for now 👍

**Comment by conectado** [comment]
@AndrewDryga I think right now the portal should select TURN servers. Since we can have some location information there.

**Comment by conectado** [comment]
I'll add some information to this issue so we can reference it later:

## The problem

[In firefox](https://searchfox.org/mozilla-central/source/dom/media/PeerConnection.sys.mjs#789-799) setting more than 2 servers leads to a warning:
> "Using five or more STUN/TURN servers causes problems"
For more than 5(the bug we're dealing with now) is:
> "Using more than two STUN/TURN servers slows down discovery"

The reason for this is [explained here](https://bugzilla.mozilla.org/show_bug.cgi?id=1322659#c11):
> It radically slows down ICE, due to the combinatorial explosion of candidate pairs, perhaps to the point of failure. 5+ STUN/TURN servers is pants-on-head crazy, so I'm ok with this being logged as an error.

So, basically, each local address must be paired with each server-reflexive candidate, peer-reflexive candidate and relayed candidate for each STUN/TURN server plus all the candidates with ipv4-to-ipv6 and ipv6-to-ipv4, then each of this candidates must be paired with all remote candidates and this can make finding working candidate-pair take too long, so long that it fails (specially with 10+ servers such as in our case!), even with ICE trickle.


## Possible solutions

First, to reduce the number of servers, @AndrewDryga we don't need any of the `stun` urls, webrtc automatically falls back to `stun` when `turn` allocation fails.

I tested filtering the `stun` urls but that alone doesn't help. Furthermore, having only 2 servers greatly increases the speed when starting new gateway connections.

Here are some recommendations on [load balancing with coturn](https://github.com/coturn/coturn/wiki/TURN-Performance-and-Load-Balance#load-balancing-among-multiple-systems). I think going for a geodns is the best way to pick the lowest latency TURN server.

To add to this and answer the conversation I had with @jamilbk earlier, right now candidates sorting is done by priority, this takes into account many factors, such as address family, and prefers peer-reflexive over server-reflexive over relayed candidates but not latency. So we need to implement something like geodns to improve latency for relayed connections.

I found a draft [expired RFC](https://datatracker.ietf.org/doc/html/draft-uberti-mmusic-nombis-00#section-5.4.1) that suggested how to do this but I'm unsure why work on this wasn't continued. So I think even in our own implementation, using a DNS-based solution is the way to go long-term

**Comment by AndrewDryga** [comment]
Unfortunately if we do anything DNS-based we will basically prohibit self hosted relays or greatly increase complexity because we will have to manage a geo-balanced DNS server over API with all the downsides

**Comment by conectado** [comment]
> Unfortunately if we do anything DNS-based we will basically prohibit self hosted relays or greatly increase complexity because we will have to manage a geo-balanced DNS server over API with all the downsides

@AndrewDryga 

We could have 2 urls:

1. Provided by us for managed relays
2. Provided by the admin for self-hosted relays

This way we offload that complexity to whomever wants to use self-hosted relays.

This means the user can host their own DNS-based solution or their own single relay. Or however they want to manage that.

**Comment by AndrewDryga** [comment]
It will be not fun for us too, not just for anyone else. I believe there are many more ways this can be solved:

1. We can use [Google Proxy Network LB](https://cloud.google.com/load-balancing/docs/proxy-network-load-balancer) that has a single Anycast IP address and can automatically route requests to the nearest relay.

2. We should design a new protocol that will replace WebRTC with that issue in mind. For example, we can have the client measure relay latencies in the background (and on the initial connection) and select one that works best for it, with a possibility of a connection upgrade later even when the channel is open.

I think for now we can limit the number of relays or use option (1), but long term since we already control and plan to redesign the protocol - better we do it ourselves than maintain critical third-party services.

**Comment by jamilbk** [comment]
I don't want to sway this discussion too much but wanted to jump in here with a +1 to this part:

> with a possibility of a connection upgrade later even when the channel is open

I think this will happen more often than we think, especially on laptops and mobile devices. It'll be a core part of our user experience. Maybe path rediscovery would work under the following scenarios

- **OS detects network change** (i.e. IP address change, default interface change, etc): reset all channels (maybe client just calls disconnect and connect?)
- **Single channel / gateway times out** (WireGuard 15s timeout): reestablish channel for that resource
- **Every ~5 minutes**: opportunistically reestablish channels for all resources. The problem with this one is it would need to remain sticky to a particular Gateway, otherwise the experience for a user would be worse since upper-layer connections would be interrupted if a new Gateway is selected -- do we interrupt your working video call to connect you to a faster Gateway?

**Comment by AndrewDryga** [comment]
I agree with Jamil that this is a pretty important feature to have, we need to figure out good ways to handoff and upgrade channels to provide a good experience while on the move. 

The only long-term alternative to that would be to generate policy files and authorize flows using cryptography, minimizing usage of the portal API. This will also affect some of our nicest current features (reliable flow logs, etc), hard to tell if they will be as feasible.

> remain sticky to a particular Gateway, otherwise the experience for a user would be worse since upper-layer connections would be interrupted if a new Gateway is selected -- do we interrupt your working video call to connect you to a faster Gateway?

Our API already has this feature: the client can pass a list of gateways it's already connected and then we will prioritize existing connections over connecting to new gateways. And I believe the client already using it for multiplexing.

**Comment by conectado** [comment]
Adding what we talked with @AndrewDryga and @jamilbk this morning:

Handing off connections is independent of finding the minimal latency, we can improve connection hand off using [ICE restart](https://datatracker.ietf.org/doc/html/rfc8445#section-9) today and we can build a similar mechanism for our hole-puncher.

Building a mechanism that measure the least latency between candidates can be quite difficult since we still have the combinatorics number of pairs and most users will only see hole-punched connections. Therefore we can get away as a first approach(as discussed above in this issue) with a load balancer.

Later on, the portal can send a sorted relay list, ordered by some criterion as the closeness of the server to the client. Given that, we can, in the background, test latency against the candidates each server, one by one, in the background in order. We can then stop given some condition, such as a measured increase latency and then hand off the connection to the best valid candidate pair.
