### ISSUE TITLE
Allow updating Policies and Resources

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2504]
We should consider the possibility a Resource's address should be updatable.

User flows that require this:

- I set up a resource, connected Gateways, configured Traffic filter, and created policies attached to it. Whoops! I typo'd the address and need to change it. It would be nice if I didn't have to back and do all that over again.
- DNS record update -- use case: My startup finally purchased our `.com` -- the Resource and its configuration should remain the same, but I need to update its address from `gitlab.firezone.dev` to `gitlab.firezone.com`
- I updated the VPC subnet my Resources live in, and their IP addresses changed.

Since Resources are attached to Authorizations, they'll need to remain consistent for audit purposes.

**Comment by jamilbk** [comment]
<img width="1322" alt="Screenshot 2023-10-25 at 12 01 25 AM" src="https://github.com/firezone/firezone/assets/167144/94e52845-529d-4a1e-b1dd-da8e9f398043">

**Comment by AndrewDryga** [comment]
> Since Resources are attached to Authorizations, they'll need to remain consistent for audit purposes.

This is why we don't allow updating them. 

This kind of stuff will be extremely hard to trace in the audit log, somebody can change an innocent resource to a production database, connect to it to dump all the records, and change it back, and nobody will ever notice that in the audit log because the flow will look normal from outside perspective. The only chance to catch that is to follow renames and warn when that happens, which is a separate alerting rule, that, I bet, most of the clients won't even think of. 

Also, what should happen when you change the address of a resource to which somebody is already connected (`connlib` must now make diffs and be intelligent about it?).

Honestly, I don't even think that you should be able to change traffic filters, because behind one IP there can be multiple resources on different ports.

I think this is a very complex feature to solve some most extreme edge cases (typos and new domains) that already can be solved by just creating a new resource and deleting an old one. If you feel that's a very important feature for `1.0-beta` we can implement a "replace" feature that will delete old resources and create a new one automatically, but I would argue it's not worth the effort.

**Comment by AndrewDryga** [comment]
> DNS record update -- use case: My startup finally purchased our .com -- the Resource and its configuration should remain the same, but I need to update its address from gitlab.firezone.dev to gitlab.firezone.com

You will want to have two resources running at least for some time during the transition, even if the old one just does a permanent redirect.

**Comment by jamilbk** [comment]
This is a question of "is a Resource its address?". Deprioritizing until we get feedback on this use case.

**Comment by jamilbk** [comment]
Have a customer that just hit this. Perhaps we shouldn't auto-populate the `name` field when typing the address? It might be confusing which one is the source of truth at a quick glance.

**Comment by AndrewDryga** [comment]
@jamilbk can we make it less ambiguous without forcing people to type it twice? I think for small setups most of names will be the same as address, especially for DNS resources

**Comment by AndrewDryga** [comment]
As a solution, I propose a few small changes:
1. We use `address` as a `placeholder` and default value of `name` (instead of setting it's `value` as user types);
2. When resource is edited we should be more clear that address can't be edited and new resource need to be created instead, we can also explain the docs why (if resource address is changed it messes up audit logs and allows malicious actions that will be much harder to track)

**Comment by jamilbk** [comment]
> We use address as a placeholder and default value of name (instead of setting it's value as user types);

Agreed, that works

> When resource is edited we should be more clear that address can't be edited and new resource need to be created instead

Sounds good

> we can also explain the docs why (if resource address is changed it messes up audit logs and allows malicious actions that will be much harder to track)

This one will be less convincing, because currently our UI shows "Activity" by Resource name, which we do allow changing. The audit log trail problem is a solved problem in this space (IPs change all the time on hosts) -- just cross-correlate the IP with timestamps. In fact if the admin has to create and delete a Resource each time the IP changes on a host, that might make the audit process harder, not simpler.

The real reason we don't support this today is technical complexity right? If that's the case I think we should just say "we're working on it" and then implement this properly along with #2024 when we ship portal Audit Logs.

**Comment by jameswinegar** [comment]
I have many things I've created automatically with names like IP/CIDR, and not being able to update means I am just going to make a new one and delete the old one. Can get pretty annoying.
