### ISSUE TITLE
Send an email on when user is added

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2598]
The goal is to show the `Account Slug` and provide setup instructions for configuring the client.

```[tasklist]
- [ ] Send an invitation email when a user is invited using create actor UI
- [ ] Allow admins to copy-paste or email setup instructions after completing the flow of creating a new actor on the actor page
```

**Comment by AndrewDryga** [comment]
Welcome email on IdP sync will be the hardest part of this issue, it should be triggered here: https://github.com/firezone/firezone/blob/main/elixir/apps/domain/lib/domain/auth/identity/sync.ex#L29 but email dispatching is currently in the web app, so we will have a chicken-egg problem (either have a primitive assets pipeline in the domain or add background jobs and dispatch jobs to `web` nodes).

Other solution can be having a long-poller and a field `welcome_email_sent_at` on the `identities` table.

**Comment by jamilbk** [comment]
I think it's reasonable to expect the Admin to send instructions for an IdP connecting, so no need for welcome email there. We could provide a template they can use for our docs.

**Comment by AndrewDryga** [comment]
@jamilbk I think this is a really nice feature to boost the adoption rate: provide a way to copy-paste templates (like Gmail does) and allow to send it when the user is invited right away. A lot of smaller users are used to have invitation emails and having nothing might be confusing.

**Comment by jamilbk** [comment]
Yeah I could see that. This came up a few times on customer calls for legacy and the feedback (from Bunq at least) was just to keep it simple and easy to edit, like a copy-paste template that admins could send from their email client with a link to (for example) https://www.firezone.dev/docs/user-guides/client-instructions. They just wanted more control over end-user coms, presumably to customize the recipients, add a PGP signature, or change other fields.

But I think a simple invitation email for magic link (manual group) is definitely useful since they Admin may not have that list stored elsewhere.
