### ISSUE TITLE
Wildcard SplitDNS

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2661]
Wildcard-match SplitDNS will require forwarding DNS queries to the Gateway so they can be matched on the client.

General flow:

1. Client tries to go to foo.bar.com
1. bar.com is one of the resources for connlib and it sees the DNS query, since bar.com is added as a splitdns domain
1. client connlib establish or reuse channel with gateway for resource bar.com, **as part of this message we send the DNS name**
1. gateway sees that bar.com is an allowed resource for client and resolves ip for foo.bar.com: it's 192.0.2.1
1. gateway sends answer to client through the **control plane**
1. client connlib saves response to memory as a mapping between 192.0.2.1 and a new ip in a reserved subnet let's say 100.126.0.1
1. 100.126.0.1 is added as a route
1. client connlib finally responds to client **crafting** the dns record with ip 100.26.0.1
1. Now when client connlib see packets with dest 100.26.0.1 from the tun interface, mangles them for 192.0.2.1 and sends them to the tunnel
1. Packets from the tunnel with dest 192.0.2.1 are mangled with 100.26.0.1 and the reverse happens at the gateway.
1. If at any point the connection expires, we still have the mapping in memory that `100.126.0.1` represents foo.bar.com
1. So at some point, Step (3) would happen again (that's how failover happens) and since we have `100.126.0.1` as resource foo.bar.com it would be part of the message to establish/reuse channel and we would just re-do steps 3. to 10.

Portal will need to be updated to preclude certain IPs from being used for IP allocation so that the client can use them without conflict.

@AndrewDryga, what do you think of this allocation structure?

| Purpose | CIDR Range | Start | End | No. of addresses | 
| --- | --- | --- | --- | --- |
| clients, gateways | `100.64.0.0/11` | `100.64.0.0` | `100.95.255.255` | `2,097,152` |
| resources (per client / gateway) | `100.96.0.0/14` | `100.96.0.0` | `100.99.255.255` | `262,144` |

**Comment by AndrewDryga** [comment]
Use cases:

Kubernetes has a internal DNS naming schema like `myapp.mynamespace.kubernetes.cluster.local`:
`*.mynamespace.kubernetes.cluster.local` = all pods in mynamespace
`*.kubernetes.cluster.local` = all pods in all namespaces

Public services like `*.meet.google.com`.
^ I don't know all subdomains to make some third-party service be fully tunneled

GCP / AWS: `api-xo12.c.firezone-staging.internal`:
`*.c.firezone-staging.internal` = all instances in VPC
`*.us-east-1.c.firezone-staging.internal` = all instances in VPC and region

**Comment by AndrewDryga** [comment]
As a consequence of our today's design there is an edge case we need to take in mind:

Imagine you added mysite.com which is hosted on webflow.com, it will be resolved to `52.206.163.162`. This IP will be used for ALL the sites hosted on Webflow, so by adding one resource you unintentionally start full-tunneling all traffic to the platform.

Also, do we care about multiple A records returned? I assume it will work just fine - as DNS cache expires on the client it will get a new IP and just redo the full flow of setting a route to fz tunnel. Alternatively, we can tunnel all A/AAAA results right away.

**Comment by bmanifold** [comment]
One other thought on a possible consequence of today's design, will the routing table for a client potentially become too large?  It's probably unlikely and I don't even know what "too large" even is in terms of a routing table, but just wanted to throw it out there.

Also, I had a thought/question when everything was being discussed and wanted to throw it out to see if I'm thinking about things correctly.  Would an alternative solution to the subdomain problem be the following:

* Client sends DNS query for a subdomain of a resource
* Gateway receives query, sees that it's a subdomain, does the external resolution
* Gateway then creates a temporary internal IP (i.e. wireguard network IP) for that subdomain and stores it locally
* Gateway returns the temporary internal IP to the client
* Client uses the returned IP
* Gateway sees a request to the temporary IP and is able to match that IP and proxy it to the external IP

I could be way off base though.  I was mainly just curious if that was even possible and/or if my mental model of what's happening in that data layer is correct.

**Comment by jamilbk** [comment]
@AndrewDryga Good catch. I think that edge would be unacceptable since it'd be so surprising and possibly security related.

@bmanifold Yeah, I think @conectado and @AndrewDryga were brainstorming something similar on the call. But then we would need some way to enforce uniqueness to prevent temp IP routing table collisions on the client. We'd have to request the temp IP from the portal I think.

Based on the above I it's becoming clear that any solution is going to require creating a new IP for each subdomain seen, otherwise we hit the edge case that @AndrewDryga discovered.

**Comment by conectado** [comment]
> Based on the above I it's becoming clear that any solution is going to require creating a new IP for each subdomain seen, otherwise we hit the edge case that @AndrewDryga discovered.

@jamilbk @AndrewDryga 
I'm thinking through this and just brainstorming. What if we do the flow proposed above but we create a translation on the client-side?

Meaning, after we get the response from the gateway with the real IP, we store an in-memory translation between a new IP (we can use a different CIDR range from our wireguard ips to prevent conflicts, if we could count on an ipv6 stack it would be even better!) and the response IP.
Then we just add the new "fake" IP to the routing table and respond with that and each time we see the IP we can do the reverse translation.

This way:
* Enforcing uniqueness becomes much easier
* We offload the whole translation process to clients instead of gateways

The open question I still have is how we enforce "allow" rules? Right now we prevent packets for a peer that are outgoing for a resource it doesn't explicitly have permission for.
We can just store DNS answers for each peer and enforce using an IP which we have seen in a DNS answer before and we only resolve IPs for allowed resources for each peer.

**Comment by jamilbk** [comment]
@conectado I may not be understanding, but I think that solution still suffers from the routing issue that @AndrewDryga brought up -- we would need to add the resolved IP to the routing table to be able to "see it", after which point we're back to routing packets for other domains that collide.

I spent more time thinking about this and came up with two possible solutions:


# Subdomain Architecture A 

In this architecture, the portal uses different CGNAT ranges for each type of entity, such that Resources get `100.64.0.0/12` for example (1 million addresses). Then, each DNS Resource would get a `/24` to allow subdomains to use IPs within that range without having to reserve them in the portal. Example:

Resource Address: `google.com`
Resource IP: `100.64.0.0/24`

1. Client requests `account.google.com`
2. `google.com` is matched as a resource; connlib opens channel to gateway
3. connlib requests subdomain lease from gateway (using channel metadata? we might need a client -> gateway message type)
4. gateway uses a mutex to reserve and respond with a subdomain IP for `account.google.com`, e.g. `100.64.0.1`
5. `100.64.0.1` is added to client routing table
6. Connlib responds to client application with `account.google.com -> 100.64.0.1`
7. Proceed as usual

### Pros
* Doesn't involve portal to reserve subdomain IPs and broadcast updates

### Cons
* Wasted IP space in the portal (needed to prevent collisions on gateways)
* Maximum of 256 subdomains per resource
* Requires out-of-band signaling between client and gateway that needs to be encrypted
* Allows state to drift between client and gateway: Need to handle the edge case where a client fails over to a new gateway that doesn't have the mapping in place

# Subdomain Architecture B

In this architecture, we use the portal to allocate subdomain IPs globally for a particular Resource. We could add some kind of `subdomains` child table to `resources` that stores subdomain leases requested by the client for that particular resource. Subdomain leases would be global per account, and included with `updateResources` broadcasts to all appropriate gateways and clients. Example:

Resource Address: `google.com`
Resource IP: `100.64.0.0`

1. Client requests `account.google.com`
2. `google.com` is matched as a Resource, send `LeaseSubdomain` message to portal for `google.com` Resource
3. Portal creates `Subdomain` record, broadcasts `updateSubdomains` to connected gateways and clients
4. connlib receives updated subdomain from portal, `account.google.com -> 100.64.10.10`
5. connlib responds to client app with `100.64.10.10` and adds it to routing table
6. Proceed as usual

Note that one benefit of the "eagerly broadcasting" model above is that subdomains only have to be leased once, after that each appropriate entity will have the subdomain cached in its Resources table. This will probably map well to subdomain access patterns, which should be roughly the same for each client that has access to the resource.

### Pros
* No wasted IP space
* Leverage the portal to cache subdomains, can truncate the table any time
* Minimal changes to connlib; high availability works as before since all entities have the same state

### Cons
* More portal broadcasts via `updateSubdomains`
* More global IP space usage

## Thoughts

From a management / maintenance perspective, I much prefer Architecture B since `connlib` is very complex already, harder to test, and resource-constrained (headcount-wise). I'm aware this creates more burden on the portal, but I think the broadcasting issue is a problem we're likely to hit anyway (just a matter of time), so it may make sense to resolve it sooner than later.

**Comment by conectado** [comment]
> @conectado I may not be understanding, but I think that solution still suffers from the routing issue that @AndrewDryga brought up -- we would need to add the resolved IP to the routing table to be able to "see it", after which point we're back to routing packets for other domains that collide.

That wouldn't happen because we wouls never add the resolved ip to the routing table.

This is how it would work:

1. Client tries to go to foo.bar.com
2. bar.com is one of the resources for connlib and it sees the DNS query, since bar.com is added as a splitdns domain
3. client connlib establish channel with gateway for resource bar.com
4. client connlib sends dns query for foo.bar.com in channel
5. gateway sees that bar.com is an allowed resource for client and resolves ip for foo.bar.com: it's 192.0.2.1
5. gateway sends answer to client through channel
6. client connlib see answer for foo.bar.com as 192.0.2.1 and it saves to memory a mapping 192.0.2.1 to a new ip in a reserved subnet let's say 100.126.0.1
7. 100.126.0.1 is added as a route
8. client connlib finally responds to client mangling the dns record changing its ip to 100.26.0.1
8. Now when client connlib see packets with dest 100.26.0.1 from the tun interface, mangles them for 192.0.2.1 and sends them to the tunnel
9. Packets from the tunnel with dest 192.0.2.1 are mangled with 100.26.0.1

**Comment by jamilbk** [comment]
@conectado Ah, thanks for the clarification, understood. So you're using the `100.x.x.x` address to route into the tunnel, at which point you mangle the `dest` to `192.0.2.1` and add it to `AllowedIPs`.

On the gateway, `192.0.2.1` was added to its `AllowedIPs` when the DNS query was approved, so you decapsulate and just send the packet through the stack.

I think that could work. We wouldn't even need reserved IP space for the clients, we'd just need a reserved block in the CGNAT range to handle all subdomains for a client. It could be for example `100.64.0.0/20`, allowing 4,096 possible subdomains for each client. The portal would then use the rest of the block as usual.

**Comment by jamilbk** [comment]
@conectado The one caveat with this approach is that you would need to do this each time the client resolves a new resource for a particular channel right? Otherwise you could fail over to a new gateway that doesn't have `192.0.2.1` in its `AllowedIPs`.

I.e. the mapping would be per-channel

**Comment by conectado** [comment]
> @conectado The one caveat with this approach is that you would need to do this each time the client resolves a new resource for a particular channel right? Otherwise you could fail over to a new gateway that doesn't have `192.0.2.1` in its `AllowedIPs`.
> 
> I.e. the mapping would be per-channel

@jamilbk 

Yeah, we need to somehow to communicate to the new gateway that we need access to that resource and it needs to find out the resource this can be quite complicated.

Also, another problem is that the channel is flaky and the dns message can be lost and we are not sure if the user-space application will resend the message or timeout.

Perhaps a way, combining your idea of using the control plane and I think will be the easiest solution to implement and maintain is sending the dns resource and response through the control plane instead of the channel, so the way it would work is:

1. Client tries to go to foo.bar.com
1. bar.com is one of the resources for connlib and it sees the DNS query, since bar.com is added as a splitdns domain
1. client connlib establish or reuse channel with gateway for resource bar.com, **as part of this message we send the DNS name**
1. gateway sees that bar.com is an allowed resource for client and resolves ip for foo.bar.com: it's 192.0.2.1
1. gateway sends answer to client through the **control plane**
1. client connlib saves response to memory as a mapping between 192.0.2.1 and a new ip in a reserved subnet let's say 100.126.0.1
1. 100.126.0.1 is added as a route
1. client connlib finally responds to client **crafting** the dns record with ip 100.26.0.1
1. Now when client connlib see packets with dest 100.26.0.1 from the tun interface, mangles them for 192.0.2.1 and sends them to the tunnel
1. Packets from the tunnel with dest 192.0.2.1 are mangled with 100.26.0.1
1. if at any point the connection expires, we still have the mapping in memory that `100.126.0.1` represents foo.bar.com
1. so at some point 3. would happen again (that's how failover happens) and since we have `100.126.0.1` as resource foo.bar.com it would be part of the message to establish/reuse channel and we would just re-do steps 3. to 10.

**Comment by jamilbk** [comment]
Note that for most websites, routing subdomains won't route all traffic for the website through the gateway even with the provisions here. Will need #2667 to be implemented for this to work for all tunneling.
