### ISSUE TITLE
OIDC provider form UX

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2674]
Suggestions for cleaning up the Add OIDC provider form.

<img width="1616" alt="Screenshot_2023-11-19_at_6_34_24_PM" src="https://github.com/firezone/firezone/assets/167144/2ddc346b-d348-4563-b106-a95cc3d2c91a">

<img width="1616" alt="Screenshot_2023-11-19_at_6_40_43_PM" src="https://github.com/firezone/firezone/assets/167144/137103d5-4c40-4e81-83c4-a9807350f42d">

**Comment by jamilbk** [comment]
@AndrewDryga We don't support JIT group provisioning from OIDC correct?

**Comment by AndrewDryga** [comment]
@jamilbk we don't support JIT provisioning, I think we should not support it at all - otherwise we will face the same issues as 0.7 did, or at least explain that we won't ever remove those actors automatically.

**Comment by AndrewDryga** [comment]
Sorry did not see @bmanifold was assigned, but needed to fix other issues I've found there anyways.

<img width="437" alt="Screenshot 2023-11-22 at 14 30 12" src="https://github.com/firezone/firezone/assets/1877644/ae58abf8-6b7d-4e13-8916-ad35c91f5c01">

We need to fix the URL but can't remove 2nd redirect URL, because we have two separate endpoints - to connect and IdP and to sign in with IdP.

**Comment by jamilbk** [comment]
> I think we should not support it at all - otherwise we will face the same issues as 0.7 did, or at least explain that we won't ever remove those actors automatically.

Well, sort of -- the big issue in 0.7 was that WireGuard configs don't expire and so sessions never expired. With 1.x users will be forced to reauth periodically so this problem is largely mitigated. Larger orgs and those with more strict requirements want more immediate deprovisioning which will come with #1437 

User/group provisioning features are pretty high priority tablestakes features, up there with high availability, so opened #2701 to track.
