### ISSUE TITLE
Match app and website button colors

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2682]
Firezone 0.7 and the website use a more purplish accent color for buttons, while the product uses a bluer tone. We should either change the website or change the product so that they're more consistent.

Will defer to @bmanifold's judgement here, don't feel too strongly which color we use

<img width="1173" alt="Screenshot 2023-11-20 at 8 34 13 AM" src="https://github.com/firezone/firezone/assets/167144/189e7880-a016-4852-bc27-0fed4fc9baa4">
<img width="422" alt="Screenshot 2023-11-20 at 8 34 24 AM" src="https://github.com/firezone/firezone/assets/167144/ab22ca2e-bae2-46b5-a83b-42232d526599">

**Comment by bmanifold** [comment]
Yeah, the shade is a bit off in the app.  I just realized that the buttons on the website are using a gradient.  @jamilbk, did you want to have the gradient in the app too?

**Comment by jamilbk** [comment]
@bmanifold Hmm, yeah they also increase in size slightly when you hover over them.

I'd say probably not necessary to have the gradient or other special effects. We could probably do another polish pass before 1.0 to tighten up the tiny little details like that

**Comment by bmanifold** [comment]
Since there is currently a gradient on the website buttons (`from-accent-700` `to-accent-600`)

<img width="352" alt="Screenshot 2023-11-22 at 11 39 53 AM" src="https://github.com/firezone/firezone/assets/2646332/b91092c9-18f2-40a7-bdd0-8d0bffe7a943">

which do you prefer for the app buttons
<br />

<hr />

1. `accent-600`
<img width="500" alt="Screenshot 2023-11-22 at 11 38 45 AM" src="https://github.com/firezone/firezone/assets/2646332/db5b4e17-e840-4097-b212-3b09c6af8663">

<hr />

2. `accent-700`
<img width="484" alt="Screenshot 2023-11-22 at 11 39 23 AM" src="https://github.com/firezone/firezone/assets/2646332/16e1bdb4-3262-4244-8d9e-28bcd4744af2">

**Comment by jamilbk** [comment]
@bmanifold I like the hover effect you have going on there. Could we do:

```
bg-accent-600 hover:bg-accent-700
```

on the app buttons and then I'll update the website buttons to remove the gradient and follow suit

**Comment by bmanifold** [comment]
Sounds good 👍
