### ISSUE TITLE
Clients MUST generate device_id

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#2697]
I've found this in Swift codebase:
https://github.com/firezone/firezone/blob/main/swift/apple/FirezoneNetworkExtension/Adapter.swift#L219. It will return empty string as `device_id` if it can't read `identifierForVendor` or mac address, but the connlib doesn't handle it: https://github.com/firezone/firezone/blob/main/rust/connlib/shared/src/lib.rs#L45 and will just hash on empty string creating all sorts of conflicts on the portal.

All clients MUST generate that ID, even if random as the last resort. There is no way how connlib or portal are supposed to know how to efficiently workaround with an empty string.

**Comment by jamilbk** [comment]
Thanks for the catch -- connlib _used_ to handle this via the SMBios helper and random UUID fallback but that was removed without this being fixed.

I'll have a randomized fallback out shortly.

Meanwhile, Apple is tightening device names in iOS 16+ so we'll need to specifically apply for an entitlement in order to show the user's device name in iOS: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name

**Comment by jamilbk** [comment]
For the record, I don't think we ever encountered a case where the Apple device ID was blank and an empty string used. The Android counterpart should never be blank as the [`deviceId()` function always returns a valid String](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java#L234).

The main violator here is probably the Linux client since the user passes `FIREZONE_ID` and will presumably copy commands to another host and duplicate it (or reused for testing). We _could_ hash the hostname and use that as fallback which should reduce collisions but not solve the problem entirely. #2651 will probably solve this for clients in addition to gateways.

cc @conectado
