### ISSUE TITLE
Windows client upstream DNS

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2713]
The Windows client will need to implement Split DNS so that requests for Firezone resources can be routed through connlib to be intercepted and mangled properly.

- When `dns_fallback_strategy` is `system_resolver`, the client should be in Split DNS mode. Requests for Firezone names should be routed to `100.100.111.1`, our DNS sentinel address (this should always be in the routing table destined for the tunnel interface)
- When `dns_fallback_strategy` is `upstream_resolver`, the client should configure the system resolver to use the `dns_address` from the `on_set_interface_config` callback. This is useful for example to allow an Admin to set an account-wide DNS resolver for all clients to use for internet security. (e.g. [Cloudflare's 1.1.1.2 resolver](https://developers.cloudflare.com/1.1.1.1/setup/#1111-for-families))
- See the [Name resolution policy table](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn593632(v=ws.11)) API for configuring Split DNS on Windows
- To set DNS resolvers, we can use the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{d7f2a7dc-ea23-44ef-8ebe-84bad862a9d8}` registry key to update the DNS resolver for the tunnel interface. This should be set to the DNS sentinel address at `100.100.111.1` so that connlib can mangle DNS requests to respond with our custom Resource mapping. See this for example: https://github.com/tailscale/tailscale/blob/82e067e0ffaa64434d1e08d318b682b1403f5c32/net/dns/manager_windows.go#L266

Use https://github.com/firezone/product/blob/main/architecture/connlib-client-ffi.md#callbacks for more reference

**Comment by jamilbk** [comment]
Update: It might be easier to just always set the Windows client to intercept all DNS queries by routing to `100.100.111.1`, then have connlib either forward non-Firezone names back to the system resolver (`system_resolver` mode), or forward to the upstream DNS configured by an admin in the portal (`upstream_resolver`). This is how the Android client's split DNS works.

**Comment by ReactorScram** [comment]
I started on routing / DNS today. Here's Firefox showing an exit IP that isn't mine, and curl accessing an httpbin instance with a local IP that isn't publicly routable. (Firefox can also access that httpbin)

![image](https://github.com/firezone/firezone/assets/13400041/2a7a46fd-7e85-4693-8a20-e3f2cc371fd2)

NRPT would work, but I'd need to parse the output of the commands, because otherwise it will be hard to clear out old rules after a restart. That might be a more thorough approach to replace the current placeholder.

For now I'm setting 100.100.111.1 as the DNS server for the wintun interface and then Windows seems to pick up the wintun interface without any prompting. It's a little weird that Windows is using the VPN interface without us telling it how to use it, and Windows doesn't actually see us as a VPN yet.

**Comment by jamilbk** [comment]
Nice work!

> Windows seems to pick up the wintun interface without any prompting

This is probably much easier than trying to get Split DNS working, and we benefit from having more control over DNS queries in general with a standard proxy across platforms. What you'll need to implement in this case is a `getSystemDnsResolvers` function similar to Android's FFI to get the fallback server to use for non-Firezone names.

**Comment by ReactorScram** [comment]
Yeah. It's not acting right with fast.com, I think it starts out on the VPN and then falls back to the physical network interfaces. (It'll get 80 Mbps with the console showing basically no packets moving, I think either Windows or Firefox gives up on the tunnel) So I'll see if there's a way to set ourselves as system-wide DNS, but let it fail-safe so when the client crashes it can forget our DNS settings.

**Comment by jamilbk** [comment]
@ReactorScram Keep in mind that when you load `fast.com` in your browser, the actual hosts that serve the speedtest data come from other domains, so it's not a good proxy to run quick tests with.

**Comment by ReactorScram** [comment]
I think this is working. When the tunnel is active, I see logs from hickory whenever I look up a domain, and the domains that are Firezone resources get CGNAT IPs.

And here are two tabs in Firefox loaded at the same time, DuckDuckGo isn't a resource so it shows one IP, and ifconfig is a resource, so it shows the gateway IP 

Previously I thought there were more issues with it, because curl requests were slow, but that was actually #2999 the MTU issue.

![image](https://github.com/firezone/firezone/assets/13400041/c305a9d2-6868-4b9f-809b-a70a0f0af09b)
