### ISSUE TITLE
Windows client boilerplate / CI

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2715]
- [x] Add appropriate Windows boilerplate in this repo to build a basic Windows application using the `windows-rs` crate. Ensure there's an appropriate README.md other devs can follow to build and run it themselves.
- [x] Add Windows CI configuration to build, package and publish our Windows application to this repo's [releases page](https://github.com/firezone/firezone/releases). Follow the example set by the gateway, relay, and linux clients for attaching artifacts to drafted releases.

**Comment by ReactorScram** [comment]
I'd like to make a case for FLTK, but I don't think it supports the system tray, so I will start with the [windows](https://crates.io/crates/windows) crate today. FLTK could be added later, if it can cooperate with `windows`.

The case would be:
- FLTK can be used from safe Rust, I didn't find a safe Windows API crate
- If you ever need a Linux GUI, all the FLTK code could be reused
- FLTK compiles statically by default, so no DLLs to package

The downsides would be that it adds maybe 7 MB to the release exe, I'm not sure how good its theming looks, and it's extra code if auditability is a concern.

**Comment by jamilbk** [comment]
@ReactorScram Oh interesting, yeah we can revisit later. I suspect we'll still need the `windows-rs` crate for interfacing to other Windows APIs but we should have a better idea how to go about that as we get further along.

**Comment by ReactorScram** [comment]
Just came across this which is Windows-only, supports systray, and has a safe API. https://github.com/gabdube/native-windows-gui

**Comment by jamilbk** [comment]
@ReactorScram My only request when picking a third party UI library would be to make sure there's some confidence it'll be well maintained and supported long into the future. Microsoft [seems all-in on Rust](https://learn.microsoft.com/en-us/windows/dev-environment/rust/rust-for-windows#introducing-rust-for-windows) so the risk seems low with `windows-rs`

I understand `windows-rs` probably scores low on the developer ease-of-use spectrum, but the risk of having to swap it out later seems low.

Open to @thomaseizinger and @conectado's input if they have experience with any windows UI Rust development?

I think we're a bit sensitive to reliance on third-party libs as a team after being bitten by webrtc-rs and its architectural and maintainability issues

**Comment by ReactorScram** [comment]
Yeah that's a good point. I figured if NWG is limiting, we can look at the code and see how they're calling into `windows`.

**Comment by conectado** [comment]
> Open to @thomaseizinger and @conectado's input if they have experience with any windows UI Rust development?

I haven't use any UI Rust library before.

I have taken a look before at https://github.com/gabdube/native-windows-gui and although it seems quite used it doesn't seem very well maintained. Also, it seems to be using [`winapi`](https://crates.io/crates/winapi) instead of the windows-rs official crate, which might have some issues long-term(it seems to be quite focused in windows 10 per its documentation) so I figure we might have incompatibilities.

I'm not so sure how easy it will be to swap it out in the future, though it does say it's just a safety wrapper but at that point we can handle the unsafety ourselves.

**Comment by ReactorScram** [comment]
Just did a CI run now for a PR and it still took 7 minutes to install `cargo-tauri` and 5 to build the Firezone client, even though the Tauri boilerplate was merged into main earlier 🤔 (We had thought sccache would speed it up once it landed in main)

**Comment by ReactorScram** [comment]
Go figure, there's an official Github Action for Tauri: https://github.com/tauri-apps/tauri-action

I'll try it Monday. It might be faster, and they list the dependencies for Ubuntu neatly, so I could just build the Windows client on Ubuntu with the Windows stuff stubbed out, instead of stubbing out all of Tauri, and it'll have better test coverage.

Edit: They also officially support installing tauri-cli via NPM, which just installs a binary package. Since we're trusting the Tauri project anyway I think this should be fine, and it shouldn't require our project to depend on NPM directly. And I think the Windows runners already have NPM - https://tauri.app/v1/guides/faq/#node-or-cargo

**Comment by ReactorScram** [comment]
also next time I touch CI I should move the Powershell stuff into a script that I can invoke locally to do the `cargo build; cp whatever.exe` steps. That would have caught the backticks syntax issue.

**Comment by ReactorScram** [comment]
This patch brings the temp-build-tauri step down from 13 minutes to 7.5 minutes, which is better than nothing - https://github.com/firezone/firezone/commit/3ba6df38166772a9e9d95c6d90b97034289c2767

**Comment by ReactorScram** [comment]
Okay after today's explanation I realized the CD was already working and attaching the artifacts to a draft release which Github makes. (I was not supposed to make draft releases manually)

I ran the exe and it's okay, it's just behind many commits because the last few GUI changes aren't in main yet.

![image](https://github.com/firezone/firezone/assets/13400041/4260e68e-ab1d-42c8-b4bc-5e016cebb1ba)
