### ISSUE TITLE
Update outbound email settings

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2732]
@AndrewDryga Was going through some email UX and found a couple things to fix:

- [ ] Update sender: `Firezone Notifications <notifications@firezone.dev>`. We can setup this alias to route to `support@firezone.dev` so that we still receive replies. This will help keep user's inboxes organized if they want to segregate actual support emails from automated emails (and help keep our inbox sane too)
- [x] Use [production Postmark server](https://account.postmarkapp.com/servers) for `firezone.dev` env
- [ ] Use [SendGrid](https://sendgrid.com) for outbound emails in staging/prod

**Comment by jamilbk** [comment]
Might be good for @bmanifold to pick this up to get some familiarity with our email infrastructure.

**Comment by AndrewDryga** [comment]
We already use prod Postmark server. So all we need is just to change reply-to email in terraform configs (we verified entire domain anyway).

**Comment by jamilbk** [comment]
Oh, then maybe something else is off?

<img width="1020" alt="Screenshot 2023-11-28 at 1 27 45 PM" src="https://github.com/firezone/firezone/assets/167144/73922814-9895-47b3-96e8-4651c2c6c18b">

**Comment by bmanifold** [comment]
I just tested this out.  I was able to get an email sent to me when I signed in on Prod via magic-link, but it ended up in my spam folder.  Is there something we need to do in Postmark to make sure this doesn't happen to users?

**Comment by AndrewDryga** [comment]
@bmanifold DKIM and SPF records should be aligned, you can try to see in gmail why it was classified as spam. One of reasons might be that you received an exact copy of our staging email for the first time, which can be seen as email spoofing.

**Comment by AndrewDryga** [comment]
> Oh, then maybe something else is off?

Nobody was sending anything for the last 30 days, that's why it doesn't show anything.

I just tested it on prod and works just fine for me:
<img width="1001" alt="Screenshot 2023-11-29 at 14 12 11" src="https://github.com/firezone/firezone/assets/1877644/80913988-7f77-4dac-af64-bb139b81be5c">
<img width="781" alt="Screenshot 2023-11-29 at 14 13 51" src="https://github.com/firezone/firezone/assets/1877644/cdaead10-c673-492e-88b0-02feec0be176">

**Comment by bmanifold** [comment]
@AndrewDryga, here's the reason google gave me for why it marked it as spam:

```
Why is this message in spam? Lots of messages from pm.mtasv.net were identified as spam in the past.
```

**Comment by jamilbk** [comment]
One nice security feauture in Sendgrid for example is IP allowlist -- @AndrewDryga can we make our portal IP range sticky so we can leverage this?

Would be useful for web logins too once dogfood is reliable.
<img width="959" alt="Screenshot 2023-11-30 at 6 22 11 AM" src="https://github.com/firezone/firezone/assets/167144/69720e0f-8a18-417e-9008-282adc664da9">

**Comment by AndrewDryga** [comment]
@jamilbk we can route outbound traffic through NAT IP but I'd say IP whitelisting is not worth it because it gives little to no advantages on top of the regular Sendgrid authentication that is secure by default, but costs a bit of maintenance because we will rotate our IPs even if once a few years and everything will break.
