### ISSUE TITLE
"Tunnel not initialized yet" crash on first launch

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2850]
Login to https://appstoreconnect.apple.com to view the crash log (attached here as well for convenience)

[DtZ2tgvpCLSCJvhLwGQWJ0.xccrashpoint.zip](https://github.com/firezone/firezone/files/13628151/DtZ2tgvpCLSCJvhLwGQWJ0.xccrashpoint.zip)

I suspect it's a race condition of some sort? Issue is most likely present on macOS as well if so.

Reported by customer

**Comment by roop** [comment]
@jamilbk  From looking at the crash log:
  - The app crashed because it hit an assertion [in TunnelStore.saveAuthStatus()](https://github.com/firezone/firezone/blob/b9cbc1786fe3d18a0761370e2f25c50e4efb1f66/swift/apple/FirezoneKit/Sources/FirezoneKit/Stores/TunnelStore.swift#L98)
  - The tunnel process never got started

I suspect this happened when the user didn't approve the app to create tunnels, but tried to save settings.

We should probably disable accessing settings when the user has not approved the app to create VPN tunnels. Is that okay to do?

**Comment by jamilbk** [comment]
Ah, that would make sense.

Yeah, let's just show them a screen with instructions on how to approve the tunnel or reset the approval, with a message like 

> Firezone requires the VPN tunnel permission. You may grant Firezone the ability to create VPN tunnels by `<insert instructions here>`. Until then, all functionality will be disabled.
