### ISSUE TITLE
"unmatched topic" when accessing `ifconfig.net` on staging

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2854]
Got this one just now. Documenting for completeness. Will update this issue if I'm able to reproduce.

<img width="768" alt="Screenshot 2023-12-10 at 9 19 57 AM" src="https://github.com/firezone/firezone/assets/167144/fcabb38b-a21f-4d67-a22c-aa5b396fad05">
<img width="1575" alt="Screenshot 2023-12-10 at 9 19 41 AM" src="https://github.com/firezone/firezone/assets/167144/c8ae03ed-cfac-4a66-8d69-efed5fef92ed">

**Comment by jamilbk** [comment]
Could have happened because Elixir topic process crashed (not Socket disconnect)

**Comment by AndrewDryga** [comment]
@conectado we should handle it on the conllib end, this happens because the client was inactive for a while so the socket was closed, when the device woke up I think the socket was reconnected automatically, but it wasn't joined to the topic anymore. The best way to handle this is to re-join the topic, slightly less efficient would be just to reconnect to the socket, but will also work.

**Comment by conectado** [comment]
> @conectado we should handle it on the conllib end, this happens because the client was inactive for a while so the socket was closed, when the device woke up I think the socket was reconnected automatically, but it wasn't joined to the topic anymore. The best way to handle this is to re-join the topic, slightly less efficient would be just to reconnect to the socket, but will also work.

Already working on it :) will tag you on the PR just in case
