### ISSUE TITLE
Stop and deinit packet tunnel provider when `path != satisfied`, and re-init tunnel adapter when `path == satisfied`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2945]
Hit an interesting bug while digging through the rabbit hole that is #2939.

When the packet tunnel provider is in the `reasserting` state, the adapter is set to a `stoppedTemporarily` state. However, it brings the `connlib` session down, which means dns is pointing to connlib's `100.100.111.1` still. It also means all of the routes added from `onAddRoute`  are still active and pointing to an unresponsive connlib.

What's worse, if I quit the application while it is `stoppedTemporarily`, the FirezoneNetworkExtensionmacOS forever hangs in a `Connecting...` state.

The more I think about the edge cases of detecting connectivity in *both* connlib and **each client**, the more my head hurts. Instead, I propose (as a long-term fix, see #2946) that we don't try to do anything fancy in the client to detect network connectivity changes at all, and just let connlib tell the clients what to do.

At the very least, in the Apple client, we need to tear down the tunnel **every time** we call `session.disconnect()`, and vice-versa with `connect()`. That should fix the bug seen in this issue.

<img width="827" alt="Screenshot 2023-12-17 at 8 31 31 AM" src="https://github.com/firezone/firezone/assets/167144/31f2c873-7d48-4acb-b5bd-b70d437d472d">

**Comment by conectado** [comment]
> The more I think about the edge cases of detecting connectivity in both connlib and each client, the more my head hurts. Instead, I propose (as a long-term fix, see https://github.com/firezone/firezone/issues/2946) that we don't try to do anything fancy in the client to detect network connectivity changes at all, and just let connlib tell the clients what to do.
 
@roop  I just talked with @jamilbk about this:

The problem is that we need to detect network changes to detect DNS changes. Each time we're going to start the tunnel, since #2947, we're going to read the current nameservers since that's the only moment the system's nameservers are exposed to us.

After that we can't find them out without depending on undocumented API and we don't want to do that.

Then whever the netwrok changes we need to tear down the tunnel, along with connlib's session, so that we get the new dns nameservers and we can use them from connlib.

**Comment by roop** [comment]
Whenever the network changes, if we bring down the tunnel (from inside the tunnel), we will not be able to bring it back up on iOS (because the app will not be running).

> What's worse, if I quit the application while it is stoppedTemporarily, the FirezoneNetworkExtensionmacOS forever hangs in a Connecting... state.

No, this can happen only if you force-quit (or stop the app from Xcode). If Quit normally, the tunnel should disconnect before quitting.

> When the packet tunnel provider is in the reasserting state, the adapter is set to a stoppedTemporarily state. However, it brings the connlib session down, which means dns is pointing to connlib's 100.100.111.1 still. It also means all of the routes added from onAddRoute are still active and pointing to an unresponsive connlib.

The Swift code in tunnel process can remember the DNS server we got when the tunnel was starting, and return that to connlib.
