### ISSUE TITLE
`resource_connection_intent` resource IP log doesn't match actual intent

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3015]
This may just be a logging bug or my misunderstanding, but it seems that the `resource_connection_intent` log is logging the multicast IP `224.0.0.22` for CIDR resources.

This is making it tricky to debug whether `resource_connection_intents` are actually happening properly for CIDR resources for this account.

```
{"time":"2023-12-24T16:52:39.72058Z","target":"firezone_tunnel::client","logging.googleapis.com/sourceLocation":{"file":"connlib/tunnel/src/client.rs","line":"401"},"severity":"DEBUG","message":"resource_connection_intent","resourceIp":"224.0.0.22"}
```

**Comment by conectado** [comment]
@jamilbk are we sure that the user hasn't added `224.0.0.22` as a resource?

**Comment by jamilbk** [comment]
@conectado Yep, the user in question only had a 10.x.x.0/24 resource.

**Comment by jamilbk** [comment]
Also this is a log from my local Apple client testing against `staging`.

**Comment by conectado** [comment]
@jamilbk just checked and the `224.0.0.22` is part of the IGMPv3 protocol and the interface can generate packets for membership reports, since it's not a resource packets like those will be dropped.

We can make it so that we don't log resource intents for packets that we will dropped, I've found it useful to debug before.
