### ISSUE TITLE
DNS isn't forwarded to upstream Resource

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3027]
Customer has DNS timeouts under the following setup (IPs changed for anonymity)

- Upstream DNS set to a 10.0.0.0/24 address in the portal, i.e. `10.0.0.36`
- `10.0.0.0/24` Resource exists and policy is created
- Firezone-managed Relays is selected for the Site (seems to be behind symmetric NAT)
- iPhone is on WiFi, local DHCP in 10.1.1.0/24 (non-overlapping range)

Troubleshooting steps taken:

- Tested manually resolving names directly against the DNS server, works (`dig @10.0.0.36 google.com` from iPhone)
- Tested using a different upstream with similar packet routing works:
  - Changed upstream to Cloudflare's `1.1.1.2` resolver
  - Added `1.1.1.2` as a resource in the site
  - Tested again, DNS resolves and uses Cloudflare's resolver

Based on the above, it seems that connlib is having issues forwarding the requests to the upstream `10.0.0.36` resolver only.

**Comment by jamilbk** [comment]
Needs further testing to ensure the packets aren't going out of the primary interface.

**Comment by conectado** [comment]
After testing with wireshark on for a bit, I can confirm the behavior if `1.1.1.2` is set both as upstream dns server and as a resource is that packets that are outbound from the network extension aren't routed back into it.

This makes sense, since macos doesn't seem to have `SO_MARK` neither namespaces as a way to have full routing.

**Comment by jamilbk** [comment]
Interesting, so this happens because the DNS requests are generated as fresh requests from the Network Extension?

I'm guessing this behavior will be the case for any type of packet generated from the network extension, just DNS.

Is this because they're forwarded using hickory? Would it make a difference if we mangle the destination of the packet to be the upstream DNS server so that the request behaves exactly like the `dig @` case?

**Comment by conectado** [comment]
> Interesting, so this happens because the DNS requests are generated as fresh requests from the Network Extension?
> 
> I'm guessing this behavior will be the case for any type of packet generated from the network extension, just DNS.
> 
> Is this because they're forwarded using hickory? Would it make a difference if we mangle the destination of the packet to be the upstream DNS server so that the request behaves exactly like the `dig @` case?

I need to do some more testing that I'm still in the midst of, I believe it's because it's indeed a new packet from a UDP socket that needs to be go into the network stack and follow the routing table.

To treat it like the `dig @` case we need to handle this edge case in particular by detecting when the upstream server is a resource and writing dns queries to the tunnel instead of using hickory(crafting a new packet or mangling it is the same).

**Comment by jamilbk** [comment]
@roop Would you happen to have an idea why these packets aren't routed through the tunnel?

**Comment by jamilbk** [comment]
For anyone stumbling across this thread, the issue turned out to be Apple's NECP (Network Extension Control Protocol). One of its primary goals is to prevent VPN packet loops, which means it prevents packets generated from Network Extensions from being routed through the tunnel.

[Read more about NECP here](https://developer.apple.com/forums/thread/725715).

Since we've verified that DNS requests to upstream Resources work fine when they're initiated by an application instead of the tunnel, the solution we're working on involves mangling the original request to get it through a holepunched channel and connected gateway instead of out the default interface.

**Comment by conectado** [comment]
As I'm working there are two things we need to consider wrt to multiple servers.

One is, if we have multiple upstream DNS servers and we want to function exactly as a stub resolver: we need to be able to keep track of the queries as we detect them and keep a copy of the packet before mangling it and sending it out to the gateway.
So that after a timeout condition we can query the next nameserver until one respond or we go through all the list of servers.

If we do that, also, when we detect a query and we have multiple upstream servers we need to consider that some of them might be resources some of them not, which makes thing a bit more complex.

Having a single upstream DNS would simplify this whole thing *greatly* but it might also be a huge limitation.

**Comment by conectado** [comment]
> As I'm working there are two things we need to consider wrt to multiple servers.
> 
> One is, if we have multiple upstream DNS servers and we want to function exactly as a stub resolver: we need to be able to keep track of the queries as we detect them and keep a copy of the packet before mangling it and sending it out to the gateway. So that after a timeout condition we can query the next nameserver until one respond or we go through all the list of servers.
> 
> If we do that, also, when we detect a query and we have multiple upstream servers we need to consider that some of them might be resources some of them not, which makes thing a bit more complex.
> 
> Having a single upstream DNS would simplify this whole thing _greatly_ but it might also be a huge limitation.

In the PR related to this issue we will assume a single upstream server and follow up with #3123
