### ISSUE TITLE
Sign Windows client with a valid EV code signing certificate

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3230]
- [ ] Procure certificate from a trusted party
- [ ] Sign app and msi in CI using `signtool`
- [ ] Verify that "Publisher: Firezone" is shown in the UAC dialog

**Comment by ReactorScram** [comment]
Is there a secret manager we'd use to get a private key into CI for signing?

**Comment by jamilbk** [comment]
@ReactorScram Yep! GH has a secrets store we use for the other clients. We actually already had a code signing cert that just lapsed, so I'll take this on as a todo and get the secret available in CI

**Comment by ReactorScram** [comment]
Tauri has _something_ in its config for this but I'm not sure how it works https://tauri.app/v1/api/config/#windowsconfig

**Comment by jamilbk** [comment]
I wonder if that just wraps `signtool`. If so, this could be as simple as getting the right certs, installing / registering them in the GA runner, and configuring Tauri to sign with the cert fingerprint.

**Comment by jamilbk** [comment]
^ That's the process we use for signing the Apple and Android clients in CI.

**Comment by ReactorScram** [comment]
I tried out SignTool with a self-signed cert and it doesn't seem too awful. Lots of GUI clicking in certmgr though. Key management will be annoying.

![image](https://github.com/firezone/firezone/assets/13400041/f3f4cde0-52e4-4b4a-9fa3-51aeece66aca)

But I didn't try anything else because all the providers want hundreds of dollars for a cert and have no free trials.

The Electron docs say that Windows code signing EV certs are bound to an HSM? https://www.electron.build/code-signing.html#windows

What a strange process. I don't know what to try next for this one.

**Comment by ReactorScram** [comment]
![uac](https://github.com/firezone/firezone/assets/13400041/a84d1961-c406-4d02-9e2e-f43530ad9ef4)

If I use certmgr to trust the self-signed cert, it looks correct in UAC. So maybe the process is feasible

**Comment by jamilbk** [comment]
Need to sign contained binaries not just the MSI
