### ISSUE TITLE
UX of Disable/Enable buttons

### ISSUE THREAD

**Issue by AndrewDryga** [CloudFire-LLC/cloudfire#3260]
For example, when you want to disable a Policy the button is in the Danger Zone on the bottom of the page, but to enable it the button is on the top. This is confusing as most users will expect Enable/Disable buttons to be in the same place.

**Comment by AndrewDryga** [comment]
@jamilbk you moved the button to the Danger Zone, do you mind If I move it back?

**Comment by jamilbk** [comment]
So the reason I moved the "Disable" buttons to the Danger Zone was because Disabling and deleting certain entities (Policies but also others) will both cause the same outcome -- network connectivity loss.

Maybe I can make this clearer with a `:help` text element in the Danger zone along the lines of `Performing actions here will result in immediate connectivity changes to connected clients"

**Comment by AndrewDryga** [comment]
@jamilbk it's a different issue - you just disable it and then don't know where the Enable button is (because it's in a different place).

**Comment by jamilbk** [comment]
Kk, sgtm
