### ISSUE TITLE
tauri build in CI doesn't seem to be using the Rust cache

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3456]
https://github.com/firezone/firezone/actions/runs/7729393371/job/21072455959#step:5:522

**Comment by ReactorScram** [comment]
No wonder it's taking so darn long

**Comment by ReactorScram** [comment]
I tried hiding the Windows client inside a lib crate, with a bin crate that just calls `firezone_windows_client_lib::entrypoint`, but it still had about 100 compiler calls that couldn't be cached because of crate-type.

So I'm not sure how the advice for splitting up crates would work https://github.com/mozilla/sccache?tab=readme-ov-file#rust

Maybe it means the pure Rust crates should be stuck in a lib, and kept apart from crates that need proc-macro or C linking.

Or maybe that advice is only usable for the maintainers of the dependencies, not of the top-level app.
