### ISSUE TITLE
The sign in token is expired. (bug)

### ISSUE THREAD

**Issue by gtjadsonsantos** [CloudFire-LLC/cloudfire#3603]
**Describe the bug**

When trying to log in to the application with the code sent in the email, the application reports an expired token

**To Reproduce**

Simply try to log in first using the link that arrives in your email

**Expected behavior**

Log in to my account

**Screenshots / Logs**
If applicable, add screenshots and log traces to help debug your problem with any sensitive data removed.

**Platform (please complete the following information):**
 - Firezone Version 1.0.0
 - Deployment method: Docker

**Additional context**

https://github.com/firezone/firezone/assets/42282908/2ade7e1d-004c-40da-9f82-258594be891b

**Comment by AndrewDryga** [comment]
This does not reproduce in our production, so it is likely a configuration issue you are hitting with the cookies, the error you see means that the auth cookie [is not found in the browser](https://github.com/firezone/firezone/blob/main/elixir/apps/web/lib/web/controllers/auth_controller.ex#L171). The cookie is set and fetched [here](https://github.com/firezone/firezone/blob/main/elixir/apps/web/lib/web/controllers/auth_controller.ex#L276-L289).

If you have a business case that needs support for self-hosted instances please get in touch with our sales team, otherwise, I would recommend you to self-host 0.7 and wait for managed 1.0 to hit GA as 1.0 has too many moving parts for a hobby project.

**Comment by AndrewDryga** [comment]
As a possible hint please make sure you use SSL for the hosted Firezone, `secure` is set to `true` for all auth cookies so auth won't work if it's not over `https://` protocol.
