### ISSUE TITLE
ci: flaky `dns-etc-resolv-conf` test

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#3666]
Flaky test run: https://github.com/firezone/firezone/actions/runs/7926850764/job/21642509280?pr=3663

After restart: https://github.com/firezone/firezone/actions/runs/7926850764/job/21642630025?pr=3663

**Comment by jamilbk** [comment]
I think I know what's happening here. It only happens for relayed connections.

The following sequence of events causes the test to pass:

1. API starts up first
2. relay starts up, receives `init` from portal with credentials
3. client / gateway start up, receive relay credentials to connect with, and TURN allocation succeeds.

The following sequence of event causes the test to fail:

1. API starts up first
2. relay starts up
3. client / gateway starts up, receives relay credentials
4. [relay restarts](https://github.com/firezone/firezone/actions/runs/7926850764/job/21642509280?pr=3663#step:8:13)
5. client / gateway have wrong TURN credentials and [cannot allocate](https://github.com/firezone/firezone/actions/runs/7926850764/job/21642630025?pr=3663#step:8:19)

Because the client and gateway cannot request new TURN credentials from the portal, any time we restart the relay after the client or gateway start, this test will fail.

I can refactor the test to enforce the correct start order, but the real issue here seems to be that restarting the Relay will break all connected clients relying on TURN to communicate until they themselves are restarted, correct?

I think this is an issue we've discussed before, curious if it's been solved if I have this wrong.
cc @AndrewDryga @thomaseizinger

**Comment by jamilbk** [comment]
Actually, yeah, I think this is the same bug [customers reported](https://github.com/firezone/firezone/issues/2143#issuecomment-1906179235)

**Comment by jamilbk** [comment]
It's strange because it looks like what's happening is that those tests aren't being forced through the relay, but TURN allocation failures look to be preventing any further communication, even using non-relay candidates.

**Comment by jamilbk** [comment]
@AndrewDryga Does the portal broadcast new TURN credentials to connected clients if a Relay joins?

**Comment by thomaseizinger** [comment]
> @AndrewDryga Does the portal broadcast new TURN credentials to connected clients if a Relay joins?

No but in snownet, we share an allocation across all connections and will update it upon every new connection that we make.

**Comment by ReactorScram** [comment]
hm I couldn't get it to replicate with those steps. I'll work on something else for now since #3671 is open

**Comment by jamilbk** [comment]
Yeah I could very well be wrong here. I'm adding some more tests to validate this and other hypotheses.
