### ISSUE TITLE
Auto-disconnect and connect based on client's Public IP address

### ISSUE THREAD

**Issue by spanishdexter** [CloudFire-LLC/cloudfire#3681]
**Is your feature request related to a problem? Please describe.**
Firezone is a great VPN solution, we had been testing 0.7, but stopped to wait for 1.0 when it's ready. But, I feel Firezone, with it's own branded client, instead of the usual wireguard client, could use an On-Premise network detection feature based on the WAN IP address the client is connecting to the Firezone controller from, to auto-disable the VPN. This is a feature that could prevent routing issues in some environments. Such as Firezone keeping the tunnel up to my corporate LAN from a laptop, when I'm already physically onsite at the office, on that LAN directly via ethernet or wifi. Having the client up in a scenario like that can cause some odd routing issues for the user on the laptop, since Windows is not smart enough to prefer the on-prem route over Firezone's route.

**Describe the solution you'd like**
It would be helpful to have the ability to auto-disable the Firezone defined routes or disconnect the VPN client when the FireZone controller detects the client is connecting to the Firezone network from an internet IP address known to the controller, in a blacklist that administrators can populate. The Firezone client on the laptop or device could receive a disconnect command from the Firezone controller in these scenario's and do a periodic check in with the controller server and/or when a network connection state change is detected in Windows (Event ID 10000 in Windows) to determine if the client is connecting from an internet IP address on this blacklist and then tell the client on the device to disconnect the tunnel if the IP is on the list. This mechanism can also connect the client automatically again if they are connecting from internet IP address NOT on the blacklist.

This new feature could allow a preference to use the already existing routing in the office LAN, and not use the routes that come from the Firezone tunnel if they are not needed since the servers or networks the user needs access to, are physically on site with them, on the same network. This allows the local physical router/firewall appliance on the LAN to handle traffic and access to devices, and when the user leaves the office with the laptop or device, let Firezone take over again and automatically re-connect the client to the WireGuard tunnel and continue using the routes coming from Firezone.

Also could be helpful to have the client also disconnect if communication with the Firezone server's/controller are lost, so the client is not left in a state where it's keeps thinking it's connected and continues to try to use a route that's not online.

**Describe alternatives you've considered**
Use of an event ID in Windows when there is a change in network adapter state to kick off a script that will perform a check similar to the one I described above using text files, ipinfo.io to get the WAN IP and powershell script to access a web server for the lists. And depending on the results, run a connect or disconnect command on the wireguard client in Windows.

**Additional context**
A GUI on the controller such as this can provide this feature. (I understand the screenshot is from 0.7).
![On Prem Detection List](https://github.com/firezone/firezone/assets/94242730/9e05aab1-67ff-4f29-9441-e1f54b4d9139)

**Comment by jamilbk** [comment]
Thanks for the feedback!

> Windows is not smart enough to prefer the on-prem route over Firezone's route.

The Firezone clients _are_ in fact smart enough however to connect directly to gateways over your LAN. They'll automatically discover the shortest path to your gateways, even if that pesky operating system tries to interfere.

The way this works is:

- When the Firezone tunnel comes up, it adds routes for all IP and CIDR resources you've defined so that they're routed into the tunnel
- When our connectivity library (`connlib`) sees a packet come into the tunnel, it runs a path searching algorithm to find the best gateway to connect to. This involves sending tiny probes out from all interfaces on both client device and gateway.
- When they discover each other, the WireGuard tunnel is established, encapsulating the original destination IP of your packet with the local LAN IP of the gateway. The benefit here is all connections are WireGuard-encrypted.
- The gateway performs the decapsulation and forwards the packet on to its intended destination

With this approach, all access to resources is logged and can be managed centrally in Firezone, regardless of the user's physical network location. Firezone was designed with this architecture to meet Zero Trust™® (apologies for the overused marketing term) requirements.

Based on the above, we likely won't prioritize building a network detection auto connect/disconnect feature in the clients soon as it would be a step backwards we feel for organizational security.

Does the above explanation make sense? Would that work for your use case?

**Comment by spanishdexter** [comment]
Thank you for responding! Yes, I am using to hearing about the Zero-Trust concept and buzzword from many of our vendors in my inbox at my workplace haha.

I suppose I'm too used to working an environment where the VPN is completely turned off when on-premise (we currently use SoftEther VPN at my workplace, the server software is configured to block our own office's public IP's from connecting to the VPN), so it intentionally takes the local route over our hardware firewalls (we use FortiGates, and control a lot of network security from those firewalls, we even use a SIEM, FortiAnalyzer with them). 

For myself and the IT team I work with, it helps to see exactly how our internal site-to-site tunnels and routes for VLANs are functioning on our network for troubleshooting purposes with our end users. Running VPN clients can skew results when doing a tracert command from the client machine or trying to solve a network issue with a user at one of our remote offices. 

I'm still getting used to most WireGuard based solutions completely taking a different approach than most VPN solutions. One of the reasons we looked at WireGuard based solutions like Firezone, is because of the ability to break through CGNAT. 

We have end users with ISPs at home that kill our SSLVPN based VPN's because of CGNAT. And CGNAT is becoming more prevalent. 

I understand an auto-disconnect or connect, will not be a feature anytime soon. 

But I do appreciate the response, and everything else Firezone can do, it looks promising, and I appreciate how secure the tunnel, client and server architecture is. Thanks again. 

I would love to use Firezone how you have designed it, but it sounds like in our network, it may not work unless I can convince my supervisor's that this is how most WireGuard solutions are designed, and it may require us to re-architecture our network to make best use of it.
