### ISSUE TITLE
Add opt-in toggle to enable diagnostic log collection

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3910]
While working through some compliance documentation for the App stores and customer requests, it seems fitting that we should allow users to disable the connlib log uploader.

Logs should still be written to disk as before, just disable the uploader.

Will require a checkbox in GUI clients and env var for CLI clients to set it.

**Comment by jamilbk** [comment]
This is blocking iOS App Store publishing. The solution here is to add a toggle switch, default "Off", in Advanced settings that enables or disables the upload feature.

**Comment by ReactorScram** [comment]
Since this is inside connlib and we don't support live setting changes, this will be passed through `Session::connect`, right?

**Comment by ReactorScram** [comment]
If log collection is off by default for all platforms, then we only need a manual way to turn it on through the GUI / env var, right?

Cause I was thinking, if it's on by default, an organization would probably want to disable it across all clients / gateways that they run, through MDM or some control plane policy. But for opt-in I'm guessing anyone who opts in won't mind doing it one-by-one.

**Comment by roop** [comment]
@jamilbk What would be the API to tell connlib whether connlib should upload logs or not? Like @ReactorScram said, should we pass an `isLogUploadEnabled` to `Session::connect`? Or maybe a separate API call, so that we can enable/disable log upload even while the tunnel is connected?

**Comment by jamilbk** [comment]
I was thinking of just passing it through the Session.connect.

Changing the setting in Advanced settings would sign the user out / warn of sign out just like the other settings

**Comment by thomaseizinger** [comment]
> Since this is inside connlib and we don't support live setting changes, this will be passed through `Session::connect`, right?

I'd be in favor of making this the first additional "command" that we can call on the `Session`: `Session::set_log_upload_active`. Internally, this means we will have to introduce a channel that sends a message to connlib's eventloop and enables / disables that state.

We will need this capability for https://github.com/firezone/firezone/issues/4028 so the scaffolding needs to happen sooner or later and doing it as part of the log upload seems to be easier then as part of `Session::update` which is a more complex change overall.

**Comment by thomaseizinger** [comment]
Another option would be to make this entirely app-controlled by saying: `Session::upload_logs`. Each client's state would then only activate / deactivate a platform specific timer and call that command on `Session`.

That would avoid having to pass more state through `Session::connect` and we would be able to get rid of one callback method at the same time because we would roll the log file as part of receiving the command to upload it.

**Comment by jamilbk** [comment]
> Each client's state would then only activate / deactivate a platform specific timer and call that command on Session.

Yeah, it simplifies connlib a bit, but adds more untested paths to the client apps which are already tricky to test.

Maybe this instead?r

- Merge all the config sent to connlib as a `SessionConfig` struct (Swift-Rust interop supports transparent structs, Kotlin we'll need to serialize to JSON)
- Inside the Config struct pass everything we have now + the `log_upload_interval`, except the callback_handler, e.g.

```
struct SessionConfig {
            api_url: String,
            token: String,
            device_id: String,
            device_name_override: Option<String>,
            os_version_override: Option<String>,
            log_dir: String,
            log_filter: String,
            log_upload_interval: Uint
}
```

By default, we make `log_upload_interval` set to `0` on iOS, which disables rollover / uploading. Later we can add a switch to allow helpful users to share logs with us.

Logs will still be written and exportable so that we can grab them on an ad-hoc basis for users hitting issues on iOS.

**Comment by thomaseizinger** [comment]
> Merge all the config sent to connlib as a `SessionConfig` struct (Swift-Rust interop supports transparent structs, Kotlin we'll need to serialize to JSON)

This just masks the problem by hiding many parameters behind one though. If anything, we should see the long list of parameters as a pain point to rework the design.

The callbacks are awkward to work with and make the control flow between clients and connlib really hard to understand so IMO they have to go.

> > Each client's state would then only activate / deactivate a platform specific timer and call that command on Session.
> 
> Yeah, it simplifies connlib a bit, but adds more untested paths to the client apps which are already tricky to test.

The log upload isn't automatically tested in connlib either due to the same constraints of requiring an instance of the portal backed by GCP :man_shrugging: 

Removing the callback makes things actually easier to test because we don't have to mock the `Callbacks`. Similarly, the clients can write a test that they spawn a timer when a certain UI toggle is on. That shouldn't be any different from testing that the correct boolean value gets passed to connlib if the UI toggle is on.

We can also have the timer inside connlib but then we need both:

- A parameter for the initial value of the timer
- A method to change the state of an existing session

**Comment by jamilbk** [comment]
> If anything, we should see the long list of parameters as a pain point to rework the design.

I'm not sure I follow this reasoning. The `api_url`, `token`, `device_id`, `device_name` are needed for the WebSocket. The `log_filter` and `log_upload` filter for logging during the session. The log parameters could conceivably be updated in the middle of a session perhaps, but this would be confusing to the user at the moment -- these are changed in the same "advanced settings" view as the API URLs, which we warn the user about with "This will disconnect your session. Do you want to proceed"?

So maybe it makes sense to have `LogConfig` and `ControlConfig` structs? But I'm not sure making these separate functions and then relying on the client to call them in a specific order makes things easier to follow / maintain.

> The callbacks are awkward to work with and make the control flow between clients and connlib really hard to understand so IMO they have to go.

I'm a bit confused -- what are you referring to by `callbacks` in this context? We have to use platform-native APIs for some things like updating routes, the UI and such.

> clients can write a test

Well, 3 tests -- one for each language. The harnesses aren't setup for this, and we don't have any experience across the team (yet) for writing these in Swift and Kotlin. Then there's the problem of we can't simulate an iPhone or Mac in CI (Android seems more promising). We'll have to solve it eventually, though.

**Comment by jamilbk** [comment]
Alternatively, we could just disable log collecting and rely on manual export + share on iOS to get around this issue for now, and revisit this later.

**Comment by thomaseizinger** [comment]
> > If anything, we should see the long list of parameters as a pain point to rework the design.
> 
> I'm not sure I follow this reasoning. The `api_url`, `token`, `device_id`, `device_name` are needed for the WebSocket. The `log_filter` and `log_upload` filter for logging during the session.

All the websocket parameters are only there to create a single URL. See https://github.com/firezone/firezone/pull/4048. Why don't we just make this URL in the clients? If we want to avoid duplicating code, we can easily expose another function next to `Session` that creates that URL and returns it again.

That decomposes the functionality into more cohesive chunks which is easier to work with.

> > The callbacks are awkward to work with and make the control flow between clients and connlib really hard to understand so IMO they have to go.
> 
> I'm a bit confused -- what are you referring to by `callbacks` in this context? We have to use platform-native APIs for some things like updating routes, the UI and such.

What I mean is: the use of callbacks to go between connlib and the clients is hard to understand, especially because they are fallible (also see https://github.com/firezone/firezone/issues/4064). Like I mentioned before, calling platform-native APIs should happen as a result of state changes[^1] in connlib which makes them declarative instead of connlib invoking things imperatively.

The reason we have a callback here is because we need to roll the log file which is actually not platform-specific so we can actually delete it. I'll do that on top of https://github.com/firezone/firezone/pull/3682.

> these are changed in the same "advanced settings" view as the API URLs, which we warn the user about with "This will disconnect your session. Do you want to proceed"?

If we don't need live changes then passing a single parameter is okay for now. Long-term, I don't think it will be maintainable to pass lots of configuration parameters into connlib. Instead, we should look for the smallest, common denominator that all platforms need and push everything that is platform-specific "upwards".

Another example of this is: Calling `protect` for the sockets on Android should happen within `connlib-client-android` and not `firezone-tunnel`. But for that, the initialization of `Sockets` needs to be moved up to where we call `Session`. Currently, that would create a lot of boilerplate but once https://github.com/firezone/firezone/pull/3682 is merged and we move `PhoenixChannel` into `firezone-tunnel`, `Session` will be such a thin wrapper that we can effectively delete it. At that point, all the platform-specific connlib crates can just initialize a `Tunnel` and there won't be any critical code duplication if `Tunnel` then requires `Sockets` to be passed in which allows `connlib-client-android` to call `protect` first whereas all other platforms don't care.

[^1]: How these state changes are sent across the FFI layer doesn't matter for this. It could be push (via a callback) or pull (client must explicitly call `next_update`).

**Comment by jamilbk** [comment]
> All the websocket parameters are only there to create a single URL. See https://github.com/firezone/firezone/pull/4048. Why don't we just make this URL in the clients?

This makes sense, thanks for clarifying.

> Another example of this is: Calling protect for the sockets on Android should happen within connlib-client-android and not firezone-tunnel. But for that, the initialization of Sockets needs to be moved up to where we call Session. Currently, that would create a lot of boilerplate but once https://github.com/firezone/firezone/pull/3682 is merged and we move PhoenixChannel into firezone-tunnel, Session will be such a thin wrapper that we can effectively delete it. At that point, all the platform-specific connlib crates can just initialize a Tunnel and there won't be any critical code duplication if Tunnel then requires Sockets to be passed in which allows connlib-client-android to call protect first whereas all other platforms don't care.

I see.

I agree with all of these points in principle. We can save them as future TODOs to make life nicer.

For the purposes of getting our first iOS app approval, I've opened #4065. IIRC we never intended for log uploads to hit GA due to the privacy implications. They were meant to more easily diagnose issues with beta users (who ended up just sending us logs anyway).

There are ways to check for whether we're in a beta (TestFlight / Firebase test) build, so maybe log uploads should only be enabled for those clients (and those who opt in with a release build) by default.

**Comment by thomaseizinger** [comment]
> We can save them as future TODOs to make life nicer.

Yeah, they've been in my head for a while but I've slowly starting writing them down as they become clearer!

> IIRC we never intended for log uploads to hit GA due to the privacy implications. They were meant to more easily diagnose issues with beta users (who ended up just sending us logs anyway).

Maybe we should just remove it entirely then?
