### ISSUE TITLE
Update Group label links to be context-aware

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#3962]
- When viewing a Resource, the Group label should link to the corresponding policy

**Comment by AndrewDryga** [comment]
Just to clarify this: Authorized Groups right now preload all groups via policies, what we actually want is to show the policy (and the group name it authorizes) so that use can click and quickly go to the policy that grants this access.

A better way to handle this might be to have a quick link to Policies with a filter by Resource ID, because there can be more than one policy granting access. So it depends on #3751

**Comment by jamilbk** [comment]
We'll probably have a better idea why the current functionality causes too much friction in a couple days. I suspect if the customer is doing this much clicking around to view relevant Policies, there's a deeper workflow here we're not aware of

**Comment by AndrewDryga** [comment]
I removed the authorized groups and added the policies table in #3751.
