### ISSUE TITLE
Enforce per-user|device rules

### ISSUE THREAD

**Issue by jeremyj** [CloudFire-LLC/cloudfire#423]
It would be nice if `Allowed IPs` could be enforced by firewall rules on a per-user or per-device level so they can't be overridden by a user. Right now it's possibile to modify the client configuration and gain access to more IPs than intended.

**Comment by jamilbk** [comment]
Currently under development as part of #259 ! Will link this issue to the relevant PR when it's ready.

Thanks for the feedback!

**Comment by jamilbk** [comment]
@princemaple Any thoughts on taking a stab at this one? It's somewhat involved but essentially boils down to keeping the FW ruleset synced with the `nftables` table -- happy to get on a call or add more context as guidance.

Edit: On second thought, we'll also need to track `source_ip` as part of the rule tuple in order to implement this on a per-device basis, so maybe it's better to hold off. I'll give it some more thought.

**Comment by princemaple** [comment]
If this is more than just comparing `allowed_ips` on `device` with `allowed_ips` on `site`, I'll need a call.

**Comment by jamilbk** [comment]
Hmm, let's table this for a bit. I'll be deep in this part of the codebase working on multi-interface support so I may just see how easy it is to add as I'm doing that work.

This one would essentially be adding a `source` modifier to the `rule` tuple in `fz_wall` that corresponds to either a user (list of devices' IPs) or a single device IP.

**Comment by jamilbk** [comment]
Per-user firewall rules should be coming in 0.5.0, due in a week or two.

**Comment by jeremyj** [comment]
Wow, this is great news. Thanks for the effort.

Jul 2, 2022 21:24:26 Jamil ***@***.***>:
