### ISSUE TITLE
Ensure client DNS happens as soon as possible

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4309]

**Comment by ReactorScram** [comment]
Yeah this was something that concerned me about the `set_interface_config` vs `on_tunnel_ready`, there really must be something to mean "You can start a query / request right now and it will eventually work". Otherwise we can get stuck with an old DNS response in the cache because the user thought Firezone was ready and it was only half-ready.

I'm pretty sure I did not visit speed.cloudflare.com before I updated and opened Firezone, but I don't have any logs from Firefox to prove that.

- macOS Sonoma 14.3.1
- Firezone Version 1.0.0 (1711374323)
- Network: USB-C hub with Ethernet plugged in, and Wi-Fi

Logs in our private Slack: https://firezonehq.slack.com/archives/C067DSY7TFX/p1711387570641589?thread_ts=1711385581.483049&cid=C067DSY7TFX

I think it happened around 16:45, I'll put a more precise time if I look at the logs later.

**Comment by ReactorScram** [comment]
In my specific case, Firefox was using DoH and ignoring the system DNS resolvers. So that's a KB issue (#4310), and the `tunnel_ready` callback might be unrelated
