### ISSUE TITLE
Why have an atomic value here? Since you already have `&mut self`

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4317]
Why have an atomic value here? Since you already have `&mut self`

_Originally posted by @conectado in https://github.com/firezone/firezone/pull/4296#discussion_r1538263988_

**Comment by thomaseizinger** [comment]
I should have probably written a more elaborate commit message on https://github.com/firezone/firezone/commit/e940c65eb7db88f15eed601abff1fb67d030fc19. I wanted `Heartbeat` to be able to generate its own request IDs because I've found the design of `set_id` to be pretty clunky. I am very much open to other designs if somebody wants to have a go at it :)
