### ISSUE TITLE
bug(macos Client): At startup the Welcome window flashes for a couple frames before closing

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#4339]
#### Describe the bug

The window flashes for a few frames.

#### To Reproduce

Close the macOS Client and re-open it. The Welcome window flashes because it's opened and immediately closed

#### Expected behavior

Expect the window to not open at all if it's not the first boot.

#### Screenshots / Logs

https://github.com/firezone/firezone/assets/13400041/6a5cdef7-f9bb-4afd-a97b-5df0ca8ad8c6

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Client
- _Firezone Version (e.g. 1.0.0 or N/A):_ Version 1.0.0 (1711524489)
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ macOS Sonoma
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ TestFlight

#### Additional context

In the Tauri Client I do it the opposite way, the window is hidden by default and I only show it when needed. Is that possible on macOS?

**Comment by jamilbk** [comment]
It's a bit more complex on Apple. We show that window based on a combination of the following states:

- VPN config approved / valid
- Notifications approved (iOS)
- First time launch

Is this the latest TestFlight build? Should be fixed in #4338 by initializing the TunnelStore with a tunnel status of `.disconnected` instead of `.invalid`.

After the tunnel store is initialized, it loops through its tunnel managers and loads the first one that matches, then updates the tunnel status, which is causing what you see.

**Comment by ReactorScram** [comment]
It's 1711524489 which is the latest TestFlight build that's in my email inbox.
I'll check again on the next TF release
