### ISSUE TITLE
Report "connected to Peer" status for each Gateway

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4738]
It would be helpful to know whether a Resource has:

- a Peer (Gateway) connected
- Peer not connected/attempted yet
- "Resource Offline" peer unavailable

These will be used to show status indicator dots in the Client UI for each resource.

**Comment by conectado** [comment]
I was planning to set this on the `set_resources` call.

There are still a few questions.

* When do we count a "resource" as connected? When we request and succeed on establishing a connection for that resource or when we have a connection for a gateway that is in the same gateway-group as that resource? In the latter case we might get a false positive, since we don't know until we try when implement dynamic policies.
* In the same line of questioning, when do we count a resource as offline? When we particularly tried to connect to a resource but got an offline response or when we get an offline response for any resource with the same gateway-group?
* For how long does a resource count as offline? until we retry connection or is it cleaned up at some point?

For now I'll go with the easiest to implement, which is only show status after trying connection for specific resources and only switch status when we get a response(important for the offline case!)

**Comment by conectado** [comment]
If the data-plane fails either, can't make a connection or the connection times-out should we count that as:
* Offline
* Unknown
* Or a new status?

I think a "Failed Connection" status might be good to debug for us but I feel it might make it hard for the user to understand the difference.

**Comment by jamilbk** [comment]
Hmm, I think the main purpose behind this issue was to make it clear to the user (possibly a power user) when it's not possible to connect to any Resources in the Site. I.e. to reflect the "Resource Offline" message from the portal (which isn't entirely accurate -- it's more like a "Site offline" error, right?).

If that's the case, we should be tying this status to the Site, and not Resource. I'll have to think more about how to reflect it in the UI, but what do you think of this approach:

- Active peer connection to Gateway in Site: Site online 
- "Resource offline" message -- Site offline. Keep status for the same time period as #4549 until it's reconfirmed by another access attempt, or changes to online from a successful access attempt
- No status -- "Site not connected" or similar

Would that work?

**Comment by conectado** [comment]
> Hmm, I think the main purpose behind this issue was to make it clear to the user (possibly a power user) when it's not possible to connect to any Resources in the Site. I.e. to reflect the "Resource Offline" message from the portal (which isn't entirely accurate -- it's more like a "Site offline" error, right?).
> 
> If that's the case, we should be tying this status to the Site, and not Resource. I'll have to think more about how to reflect it in the UI, but what do you think of this approach:
> 
>     * Active peer connection to Gateway in Site: Site online
> 
>     * "Resource offline" message -- Site offline. Keep status for the same time period as [Sleep connections after inactivity #4549](https://github.com/firezone/firezone/issues/4549) until it's reconfirmed by another access attempt, or changes to online from a successful access attempt
> 
>     * No status -- "Site not connected" or similar
> 
> 
> Would that work?

I think for most cases this works until we have multi-site resources
