### ISSUE TITLE
Policy Conditions

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#4743]
- [x] #4740 
- [x] #4741 
- [x] #4742 
- [ ] What should the Clients do when denied access to a Resource?

<img width="800" alt="Screenshot_2024-05-01_at_10_28_24_AM" src="https://github.com/firezone/firezone/assets/167144/08b6dfef-9815-4b19-bc53-2835d04f188c">

**Comment by AndrewDryga** [comment]
Related #4539

**Comment by AndrewDryga** [comment]
Two questions/design tradeoff decisions:

1. Do we show resources that the client can't access right now due to a condition violation? (Eg. "not from this country")? 

Yes, because having the "resources" list change all the time might be confusing. Especially when users are not looking at it that much - they can just use browser bookmarks and don't even understand what "resource" is.

2. Then we need to show an error when trying to access a resource and the condition is failed. How much details do we share? 

On the design call, we all agreed to share the condition type but not it's value, eg. "You can not access this resource from current country" but not "You need to be in US to access this resource".
