### ISSUE TITLE
`firezone-ctl reconfigure` sometimes cuts SSH connection on first run

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#478]
When `firezone-ctl reconfigure` is run on a fresh install, it sometimes causes the SSH connection to drop because new firewall rules are being inserted / loaded. This causes the script typically to fail at the database schema step.

**Comment by jamilbk** [comment]
Dupe of firezone/backlog#171

**Comment by jamilbk** [comment]
@conectado Would you be willing to take a stab at this one? It seems to hang during the db migrate step (see omnibus/cookbooks/recipes/phoenix.rb) which is weird because the migrations don't touch any network settings.

Note this only happens on a fresh install of Firezone.

My hunch is that a network change is causing the hang but the STDOUT from Chef is just not sync'd up properly. One quick thing to rule out would be to see if turning on ipv4/6 forwarding causes this (we do this in the network.rb recipe IIRC).

You'll want to reproduce first on a fresh VM (could be a local virtualbox VM you ssh into or an ec2 vm -- ask @gongjason for an AWS account).

You'll probably have to completely uninstall Firezone between tests (see scripts/uninstall.sh and the uninstall guide in docs).

If it's looking like a real PITA to triage the specific issue, or it looks like there's no clear fix, we'll have to come up with a workaround or perhaps isolate the recipe causing the issue and notify the user by printing a message along the lines of `warning: configuring network. This may cause your ssh connection to drop`.

**Comment by conectado** [comment]
Yeah! I have a VM I prepared to test #675 so I will try with that for now I think it will work.

**Comment by jamilbk** [comment]
@conectado awesome, sounds good. Also, on second thought, I think the migrations might actually call `load_app()` in apps/fz_http/release.ex, which *might* be starting up the fz_wall app which would initialize the fw tables. So that’s something to investigate as a culprit as well.

**Comment by conectado** [comment]
@jamilbk Just to make sure, I'm getting the following error consistently on a fresh install

```
...
Recipe: firezone::phoenix
...
        * template[/opt/firezone/sv/phoenix/control/t] action create (up to date)
        * link[/opt/firezone/init/phoenix] action create (up to date)
        * file[/opt/firezone/sv/phoenix/down] action nothing (skipped due to action :nothing)
        * directory[/opt/firezone/service] action create (up to date)
        * link[/opt/firezone/service/phoenix] action create (up to date)
        * ruby_block[wait for phoenix service socket] action run
          - execute the ruby block wait for phoenix service socket
client_loop: send disconnect: Broken pipe
```

I think I'm dealing with the actual bug since this happens in the `firezone::phoenix` recipe when required by the `firezone::app` (which afaict is the migration step) but just wanted to be completely sure I'm not having another problem with my ssh config, I wanted to confirm this is the bug.

**Comment by jamilbk** [comment]
@conectado Yep! That seems to be the bug. Is this on a vbox VM?

**Comment by conectado** [comment]
> @conectado Yep! That seems to be the bug. Is this on a vbox VM?

No, I'm using qemu, could easily create a vbox VM though if it helps for sharing it.

Also, I think I pinpointed the problem to the `firezone::phoenix` in fact if I change `cookbooks/attributes/default.rb` so that
```
default['firezone']['phoenix']['enabled'] =  false
```

Seems like the bug stops happening. 

So I think I can say that the problem is [here](https://github.com/firezone/firezone/blob/master/omnibus/cookbooks/firezone/recipes/phoenix.rb#L53-L69).

**Comment by conectado** [comment]
@jamilbk After more testing in the end I could determine that you were right and the problem is when adding the firewall rules, particularly I could isolate it to [here](https://github.com/firezone/firezone/blob/master/apps/fz_wall/lib/fz_wall/cli/live.ex#L50-L53) (At some point I thought that it was not inside the elixir application but it was a mistake I made when testing).

I'm quite sure it's the case since I made this script
```sh
#!/bin/sh

echo "Creating firezone table"
sudo nft create table inet firezone

echo "Adding chain forward"
sudo nft 'add chain inet firezone forward { type filter hook forward priority 0 ; policy accept ; }'

echo "Adding chain postrouting"
sudo nft 'add chain inet firezone postrouting { type nat hook postrouting priority 100 ; }'

echo "Adding postrouting rules"
sudo nft 'add rule inet firezone postrouting oifname enp1s0 masquerade random,persistent'
```
that triggers the bug, the bug is always triggered by the last line (the add rule) but only if it's the first time the rule is added during the current SSH session and the rule didn't exists when starting the SSH session. (So if you connect and the rule exists and you delete it and then recreate it, it's not triggered).

I will try to figure out why exactly it's happening.

**Comment by conectado** [comment]
Alright! I think I understand the problem and I have a solution!

The problem is that when the  rule:

```
sudo nft 'add rule inet firezone postrouting oifname enp1s0 masquerade random,persistent'
```
this rule applies to all connection including the existing ones outgoing from the host, that includes the SSH connection, so the rule changes the outgoing port of the ssh connection which cause it to fail.

To demonstrate it here is a capture of wireshark from the SSH server when adding the rule(manually):

![image](https://user-images.githubusercontent.com/3310803/172517596-41fc8d5b-c08b-4457-9b13-c85ad11bd6ee.png)

Check how it starts using the port 292 suddenly with an ack message to the port it was communicating with SSH.

So I propose we use a new rule to check that the state is not established making the rules like this:

```
table inet firezone {
	chain forward {
		type filter hook forward priority filter; policy accept;
	}

	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		ct state != established
		oifname "enp1s0" masquerade random,persistent
	}
}
```
I tested this manually and it works, the bug isn't triggered when adding the rule. And the masquerading seems to work when using UDP and TCP.

I will test this integrating into firezone instead of creating the rules manually and  see if it works and then create a PR.

**Comment by jamilbk** [comment]
@conectado This is awesome work. Thanks Gabi!

**Comment by conectado** [comment]
I'm still working on this and it turns out when this solution is implemented in elixir it doesn't work or not always. I tried with an elixir script and for some reason it needs a timer before adding the masquerade rule to work but even that doesn't work when included in the whole solution for firezone.

Also, reading the man pages for [nftables](https://www.netfilter.org/projects/nftables/manpage.html) in table 5 part of the Chains section it says about the nat chain type:

> Chains of this type perform Native Address Translation based on conntrack entries. Only the first packet of a connection actually traverses this chain - its rules usually define details of the created conntrack entry (NAT statements for instance).

So in an existing TCP connection, I'm referring to the SSH connection, the nat hook type should never take effect.

Furthermore, there are a lo of quirks, for example the `ct` entry that I added as a workaround works no matter the state I set, also if I add instead of the `ct` entry an entry to filter like `tcp sport != 22` the bug is triggered anyways(This wouldn't work as a workaround but I was testing).

So I'm starting to believe this is a bug in nftables so I will do some more tests, try to find a workaround that works consistently and file a bug with netfilter.

**Comment by jamilbk** [comment]
Hmmm very strange indeed. It seems weird it would be a bug in `nftables` since that's such a critical part of the kernel and this seems like a common scenario. 

Could it be another rule that gets loaded? Maybe it's worth verifying this bug shows up in the same way on an EC2?

**Comment by conectado** [comment]
> Hmmm very strange indeed. It seems weird it would be a bug in `nftables` since that's such a critical part of the kernel and this seems like a common scenario.
> 
> Could it be another rule that gets loaded? Maybe it's worth verifying this bug shows up in the same way on an EC2?

Good call, I will try that

**Comment by conectado** [comment]
> Hmmm very strange indeed. It seems weird it would be a bug in `nftables` since that's such a critical part of the kernel and this seems like a common scenario.
> 
> Could it be another rule that gets loaded? Maybe it's worth verifying this bug shows up in the same way on an EC2?

Reproduced in the ec2 instance using these steps:

1. SSH into the instance
2. Install nftables
3. Run this script:

```
#!/bin/sh

echo "Creating firezone table"
sudo nft create table inet test

echo "Adding chain postrouting"
sudo nft 'add chain inet test postrouting { type nat hook postrouting priority 100 ; }'

echo "Adding postrouting rules"
sudo nft 'add rule inet test postrouting oifname eth0 masquerade random,persistent'
```
Also I have the pcap capture of the connection and the same problem happens, the ssh connection changes port when the rule is created.

```
...
17:08:11.567356 IP [remote-instance-public-ip].ssh > [local-public-ip].56238: Flags [P.], seq 641:677, ack 428, win 464, options [nop,nop,TS val 3788537251 ecr 3603322913], length 36
17:08:11.575411 IP [remote-instance-public-ip].ssh > [local-public-ip].56238: Flags [P.], seq 677:737, ack 428, win 464, options [nop,nop,TS val 3788537259 ecr 3603322913], length 60
17:08:11.575530 IP [remote-instance-public-ip].ssh > [local-public-ip].56238: Flags [P.], seq 737:773, ack 428, win 464, options [nop,nop,TS val 3788537259 ecr 3603322913], length 36
17:08:11.583962 IP [remote-instance-public-ip].254 > [local-public-ip].56238: Flags [P.], seq 3709599856:3709599980, ack 810677479, win 464, options [nop,nop,TS val 3788537267 ecr 3603322913], length 124
17:08:11.720146 IP [local-public-ip].56238 > [remote-instance-public-ip].ssh: Flags [.], ack 485, win 501, options [nop,nop,TS val 3603323075 ecr 3788537241], length 0
17:08:11.725724 IP [local-public-ip].56238 > [remote-instance-public-ip].ssh: Flags [.], ack 581, win 501, options [nop,nop,TS val 3603323076 ecr 3788537242], length 0
17:08:11.732045 IP [local-public-ip].56238 > [remote-instance-public-ip].ssh: Flags [.], ack 677, win 501, options [nop,nop,TS val 3603323085 ecr 3788537251], length 0
17:08:11.736739 IP [local-public-ip].56238 > [remote-instance-public-ip].ssh: Flags [.], ack 737, win 501, options [nop,nop,TS val 3603323093 ecr 3788537259], length 0
17:08:11.741891 IP [local-public-ip].56238 > [remote-instance-public-ip].ssh: Flags [.], ack 773, win 501, options [nop,nop,TS val 3603323093 ecr 3788537259], length 0
17:08:12.131491 IP [remote-instance-public-ip].254 > [local-public-ip].56238: Flags [P.], seq 0:124, ack 1, win 464, options [nop,nop,TS val 3788537815 ecr 3603323093], length 124
17:08:12.515493 IP [remote-instance-public-ip].254 > [local-public-ip].56238: Flags [P.], seq 0:124, ack 1, win 464, options [nop,nop,TS val 3788538199 ecr 3603323093], length 124
17:08:13.283492 IP [remote-instance-public-ip].254 > [local-public-ip].56238: Flags [P.], seq 0:124, ack 1, win 464, options [nop,nop,TS val 3788538967 ecr 3603323093], length 124
17:08:14.787472 IP [remote-instance-public-ip].254 > [local-public-ip].56238: Flags [P.], seq 0:124, ack 1, win 464, options [nop,nop,TS val 3788540471 ecr 3603323093], length 124
17:08:17.955494 IP [remote-instance-public-ip].254 > [local-public-ip].56238: Flags [P.], seq 0:124, ack 1, win 464, options [nop,nop,TS val 3788543639 ecr 3603323093], length 124
```
(Modified it slightly to hide the public ips)

The only difference is that the connection just hangs when the problem happens but I'm pretty sure this is because my router must be filtering the `rst` package that I'm sending to the port `254` (or the aws firewall).

**Comment by jamilbk** [comment]
This should be fixed and will be rolled out in the next release.
