### ISSUE TITLE
Config filenames can sometimes be too long

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#503]
Network interface names have a max length of 15. Truncate the config filenames to this length so they can be seamlessly imported with `wg`.

**Comment by bcookatpcsd** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.net-naming-scheme.html

8< -- SNIP -- >8

`When [systemd-nspawn(1)](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#) derives the name for the host side of the network interface created with --network-veth from the container name it previously simply truncated the result at 15 characters if longer (since that's the maximum length for network interface names). From now on, for any interface name that would be longer than 15 characters the last 4 characters are set to a 24bit hash value of the full interface name. This way network interface name collisions between multiple similarly named containers (who only differ in container name suffix) should be less likely (but still possible, since the 24bit hash value is very small).
`

Possibly adding a wireguard interface via nmcli works differently and doesn't truncate.. 

Standard site with nmcli directions.  OS Independent.. 

https://www.cyberciti.biz/faq/how-to-import-wireguard-profile-using-nmcli-on-linux/

nmcli was actually complaining.. 

I was adding the interface (with a longer name) and got the error.. 

Normally it works: 

```
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc cake state DOWN group default qlen 8192
    link/ether b4:a9:fc:fb:5f:80 brd ff:ff:ff:ff:ff:ff
3: wlp0s20f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc cake state UP group default qlen 8192
    link/ether e0:d4:e8:56:78:b8 brd ff:ff:ff:ff:ff:ff
    inet 10.255.248.68/22 brd 10.255.251.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 175sec preferred_lft 175sec
    inet6 fe80::45b7:50ef:bc1b:b9cb/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: main-peanut: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc fq_codel state UNKNOWN group default qlen 2048
    link/none 
    inet 10.192.122.6/32 scope global noprefixroute main-peanut
       valid_lft forever preferred_lft forever
```

address 4: is the wireguard tunnel in this case.. 

(hope this helps..)

**Comment by jamilbk** [comment]
Thanks @bcookatpcsd this information is great.

Things have been crazy busy lately but I'll work on a fix for this soon. Appreciate your patience.
