### ISSUE TITLE
Support multimatch wildcards in DNS

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5056]
https://docs.rs/wildmatch/latest/wildmatch/

For the `?` operator, we may need to either repurpose that to match single characters, or come up with another way to support single-level matching.

If no customers are using that character we could just repurpose it.

**Comment by jamilbk** [comment]
@conectado I verified that this feature is to safe to implement as detailed in the description without affecting current customers.

Might be good to implement this along with #4789 ?

**Comment by jamilbk** [comment]
Moving to medium priority

**Comment by thomaseizinger** [comment]
We might want to add another input box to the config page here that allows customers to "test" their filter to ensure it matches the domains they want to match.

Perhaps it should be a list of domains they'd like to match with an indicator next to it whether it does.

**Comment by jamilbk** [comment]
@thomaseizinger That's not a bad idea. I'll need to think about how we display that in the portal. For a v1 it might be overkill.

Had another customer request this

**Comment by thomaseizinger** [comment]
I've started to work on this by implemented new test cases and was wondering what the exact behaviour is that we want here?

- Does `*.example.com` match all sub-domains including `example.com` itself?
- Do we allow mix and match of `*` and `?` placeholders?
	- Does `?.*.example.com` make any sense?
	- Does `*.?.example.com` make any sense?
		- If yes, does this match an arbitrary number of labels but enforce a single digit domain before? Like `foo.baz.bar.a.example.com`.
	- Can they be mixed _within_ a single subdomain?

It would be great to get some data on what customers would like to match. There are a lot of possibilities of how this can be implemented and I am not sure it will be useful otherwise.

**Comment by chrisbrookes** [comment]
Hi, just piping up with opinions as a soon-to-be-customer, based on what we'd like to do.

Match any on specific level only:
- `*.domain.com` - matches `www.domain.com`, does not match `foo.bar.domain.com`
- `app.*.domain.com` - matches `app.foo.domain.com`, not `app.foo.bar.domain.com`
- `app.*.*.domain.com` - matches `app.foo.bar.domain.com`

Match across multiple levels (using double star convention, just to demonstrate):
- `**.domain.com` - matches `www.domain.com` and `foo.bar.domain.com` and `app.foo.bar.domain.com`
- `app.**.domain.com` - matches `app.foo.domain.com` and `app.foo.bar.domain.com`

Single letter wildcard `?` I don't see us using, but can see it's utility in some cases.

**Comment by thomaseizinger** [comment]
Okay that is interesting, thank you! So `*` would be a wildcard for a single label / subdomain.

Would you expect `*.domain.com` to match `domain.com` itself too? Or strictly only sub-domains?

**Comment by jamilbk** [comment]
@thomaseizinger `**domain.com` could match that.

So:

- `?` - single char match
- `*` - wildcard glob up to subdomain barrier
- `**` - recursively match across subdomain barriers

 This is similar to shell globbing. Maybe it makes sense to apply other useful aspects of that here.

Note: we will need to migrate existing data and notify folks if going with the above, but I think we have a direct translation:

`?` becomes `*`
`*` becomes `**`


This is a breaking change for existing clients, so we may need to think through that a little more unfortunately.

**Comment by chrisbrookes** [comment]
Suggestion: Version the syntax? Add a dropdown for specifying.

- v1 is the old syntax and set to all current configs
- v2 is new syntax and default for new configs

Or run a batch update of all configs to convert to new syntax, with due warning obviously. Bit more dangerous.

**Comment by thomaseizinger** [comment]
> * `?` - single char match

Do we need that? In Shell-land, I can just add characters next to `*` to include things in the match. So for example:

`git*.company.com` would match `gitlab.company.com` and `github.company.com`

Do we really need single character matching? I think restricting `*` to a single label would have a similar effect.

Perhaps we can even ship that in a backwards-compatible way: Extend `?` to the above behaviour. Later transition the syntax and drop the `?` character entirely.

**Comment by jamilbk** [comment]
The use case for `?` I've seen is to match things like `sjc-01-vpn.cisco.com` where you can replace 01 with ?? and _not_ have it match `sjc-staging-vpn.cisco.com`.

I think the idea of glob patterns is a good analogy here and many users will already be familiar with those.

Do we get them relatively for free with the globbing lib?

**Comment by jamilbk** [comment]
Actually I think this change is backwards compatible -- `**` in existing clients should match what `*` does now.

**Comment by thomaseizinger** [comment]
> Do we get them relatively for free with the globbing lib?

It is not completely trivial but doable. Probably need to split domain name by dot and apply them as individual matchers.

The double star we'd have to implement ourselves but also shouldn't be too difficult.

> Actually I think this change is backwards compatible -- `**` in existing clients should match what `*` does now.

If we write a DB migration then yes.

- Migrate `*` to `**`
- Migrate `?` to `*`

**Comment by jamilbk** [comment]
> If we write a DB migration then yes.

I've checked, and we should be able to notify any affected users directly. The `?` to `*` migration is a breaking change, but I think the impact should be limited.

**Comment by conectado** [comment]
To make it sltightly more formal and confirm we're in the same page

Our `matches_domain: String, DomainName -> bool` function should be equivalent, in the sense of having the same results for the same inputs, to the following procedure:

For any string(the first parameter) composed of valid domain name characters and `*`, `?` do:

From left to right for each character(unicode-point) `c` and do the following replacement:

If `c` is `*`, and next characters is also `*` replace both with `.*`
If `c` is `*` and next characters is not `*` replace it with `[^\.]*` 
If `c` is `?` replace it with `.`
If `c` is `.` replace it with `\.`
Any other `c` keep as is

The resulting `String` from the preceding replacement use as a regex to match the `DomainName`, return `true` in case it matches and `false` otherwise.



With this I think all examples given in the will match as intended.

**Comment by conectado** [comment]
> > If we write a DB migration then yes.
> 
> I've checked, and we should be able to notify any affected users directly. The `?` to `*` migration is a breaking change, but I think the impact should be limited.

It's still a breaking change in the sense that clients and gateways on previous version will break, not panic but the matching for domains won't work as expected.

**Comment by jamilbk** [comment]
> the matching for domains won't work as expected.

We currently don't allow multiple `*` characters:

<img width="193" alt="Screenshot 2024-07-12 at 1 22 51 PM" src="https://github.com/user-attachments/assets/3a1b091b-fbb4-4df4-aa57-8d066e3d4aaf">

So we'll replace `*` with `**` -- I guess the client doesn't accept multiple `*` currently?

**Comment by conectado** [comment]
> > the matching for domains won't work as expected.
> 
> We currently don't allow multiple `*` characters:
> <img alt="Screenshot 2024-07-12 at 1 22 51 PM" width="193" src="https://private-user-images.githubusercontent.com/167144/348387571-3a1b091b-fbb4-4df4-aa57-8d066e3d4aaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTc5MTksIm5iZiI6MTcyMDgxNzYxOSwicGF0aCI6Ii8xNjcxNDQvMzQ4Mzg3NTcxLTNhMWIwOTFiLWZiYjQtNGRmNC1hYTU3LThkMDY2ZTNkNGFhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQyMDUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODRiY2E4MDU3MTIzOGI4YTU1ZWNiYjAyNGY4YTNlMTFjMDI2YTk5NDE1N2FlZmIzNDZlNjZhNzdkMzA2NTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D9duNqjqmq9YCZkH8Z_mnSrCC14MdM3RR2HTy7XzJhU">
> 
> So we'll replace `*` with `**` -- I guess the client doesn't accept multiple `*` currently?

We expect the `*` only to be at the start, so I thik any `*` other than the starting one will be interpreted literally, which is probably okay it will just never match (though it will look quite weird in the UI!(

But we are also changing the semantics of `*` and the current clients and gateways will interpret the current meaning which is the `**` so unless we make the portal make the conversion to the old format when checking the clients' and gateway's version.

**Comment by thomaseizinger** [comment]
> unless we make the portal make the conversion to the old format when checking the clients' and gateway's version.

That is tricky to support too in the portal, no? Instead of converting, we should maybe filter them and display a warning in the portal that newly defined resources will only work on clients with version > X?

**Comment by thomaseizinger** [comment]
> Suggestion: Version the syntax? Add a dropdown for specifying.
> 
>     * v1 is the old syntax and set to all current configs
> 
>     * v2 is new syntax and default for new configs

@chrisbrookes The issue with versioning is that old clients don't know about versions and thus will simply apply the old matching logic to the new pattern. To keep backwards compatibility, admins would have to supply two patterns (or we convert back to the old one).

**Comment by jamilbk** [comment]
@thomaseizinger Old clients will barf if they see an `address_v2` field in the Resource JSON, correct?

What it's looking like we'll need to do is:

- Add `address_v2` field to Resources
- Migrate existing `address` field for DNS resources to use the new format into the `address_v2` field
- We bump minor in Clients, Portal sends `address_v2` for Clients >= v1.2 and `address` otherwise

That should solve the issue I think? Since we'll need a to bump minor for the upcoming full-route release anyhow, we can launch these two features together.

**Comment by jamilbk** [comment]
The above would also need to be combined with @chrisbrookes' suggestion to allow defining either in the UI.

Alternatively, we could deviate from glob patterns slightly, and expand upon our current behavior with new characters. Long-term, that will be a worse experience for new users, so probably better to endure the pain now and then sunset the `address_v1` field when all clients have been upgraded.

**Comment by thomaseizinger** [comment]
> @thomaseizinger Old clients will barf if they see an `address_v2` field in the Resource JSON, correct?

Adding new fields is backwards-compatible! :)

Changing enums isn't backwards-compatible because it is essentially changing the semantics of a field from "these two values are allowed" to "these three values are allowed".

> Add `address_v2` field to Resources

It is semantically very similar but my suggestion would be to add a "version" field to the entire resource instead.

> Migrate existing `address` field for DNS resources to use the new format into the `address_v2` field

I don't think we need any migration if we do versioning. Starting with v2, the `address` field will simply be interpreted differently.

**Comment by jamilbk** [comment]
@thomaseizinger I think I like that approach. Maybe one small improvement: Instead of `v2`, we just require the version directly, e.g. `"min_required_version": "1.2"`.

This is starting to feel like we need to version our control plane API entirely, though. Otherwise this is going to get messy on the backend as we continue down this path.

We can have different versions of the WebSocket API handlers that match versions sent by `connlib`.

**Comment by thomaseizinger** [comment]
> Maybe one small improvement: Instead of `v2`, we just require the version directly, e.g. `"min_required_version": "1.2"`.

Where would this field be? In the resource? The backend alreasy knows which version we are from the initial WebSocket upgrade request.

> We can have different versions of the WebSocket API handlers that match versions sent by `connlib`.

Semantically, it is kind of the other way around though, isn't it? `connlib` wants a different version of the backend. Maybe it would be better to build a version selection that works based off a header in the WebSocket upgrade request? That is how GitHub does it: https://docs.github.com/en/rest/about-the-rest-api/api-versions?apiVersion=2022-11-28

> Otherwise this is going to get messy on the backend as we continue down this path.

Yeah very cognisant of that. I don't know the backend code so take this idea with a grain of salt:

- Introduce an API version header like GitHub has it (plus maybe a "development" header which is the latest version of everything)
- Based on the header, the backend assembles a set "message handler"s with certain behaviour. Basically, as the WebSocket GET request comes in, a process is spawned for it, right? That process would have a config, as to which other functions it should call for incoming messages. What might be tricky here is how to propagate this behaviour across multiple layers.
- As we want to change them, we can create a new module for the same behaviour in the backend (like handling init).
- Most notably, this is different from pairing gateways and clients together based on their version.

**Comment by jamilbk** [comment]
Yeah `address_v2` works. I was thinking to make it less confusing however (nothing is v2 in Firezone yet) maybe we just send the `enhanced_address: bool` field down since we need to add it to resources on the backend anyway. If `connlib` sees that, it uses the improved parsing logic. Otherwise, it uses the old parsing logic.

In the future we can remove that bool from Resources.

**Comment by thomaseizinger** [comment]
> Yeah `address_v2` works. I was thinking to make it less confusing however (nothing is v2 in Firezone yet) maybe we just send the `enhanced_address: bool` field down since we need to add it to resources on the backend anyway. If `connlib` sees that, it uses the improved parsing logic. Otherwise, it uses the old parsing logic.
> 
> In the future we can remove that bool from Resources.

When it comes to backwards-compatibility stuff, I like to think in making code easy to delete so any design that doesn't modify the payload of an individual resource is better in that regard. To achieve that, we could lean on a similar design as suggested in https://github.com/firezone/firezone/issues/5852#issuecomment-2224824175 and do:

```jsonc
{
    "event": "init",
    "payload": {
        "interface": { },
        "resources": [ ], // Current resources
        "dns_resources_v2": [ ] // DNS resources with different `address` semantics
    },
    "ref": null,
    "topic": "client"
}
```

1. This is fully backwards-compatible because old clients simply ignore additional fields in the payload.
2. I _think_ this may be easier to handle for the portal because it can unconditionally put all new DNS resources into a separate field, regardless of the client's version.
3. It is easier to handle in connlib because we can parse the "v2" resources into a separate struct and thus differentiate the semantics on the type-level.

**Comment by jamilbk** [comment]
We need this for the Gateway and `update_resources` broadcast too right?

**Comment by thomaseizinger** [comment]
> We need this for the Gateway and `update_resources` broadcast too right?

Ah yes. The gateway currently doesn't receive resources as part of `init`. I think we should change that and only reference a resource's ID in `request_connection` instead of sending the full resource. Updating resources will also need a new message yes.

What is more difficult for the portal to implement?

1. Always send both, `request_connection` and `request_connection_v2` to each gateway and - for defense in depth - only allow a response to one of them.
2. Conditionally send one or the other based on the version.

Technically, we should be able to get away with (1) because we won't ever release a gateway that responds to both. But somebody could build a gateway from source that does so we need to make sure responding to both doesn't crash anything in the portal.

**Comment by thomaseizinger** [comment]
So in summary, one potential path forward is:

1. Send resources to gateway upon `init` and also send resource updates to the gateways.
2. Introduce `request_connection_v2` which only references a resource ID and not the full resource.
3. Introduce `dns_v2_resources` fields in both `init` messages, containing only the DNS resources with new `address` matching semantics.
4. Introduce new `create_or_update_dns_v2_resource` message to both client and gateway.

**Comment by conectado** [comment]
> > We need this for the Gateway and `update_resources` broadcast too right?
> 
> Ah yes. The gateway currently doesn't receive resources as part of `init`. I think we should change that and only reference a resource's ID in `request_connection` instead of sending the full resource. Updating resources will also need a new message yes.
> 
> What is more difficult for the portal to implement?
> 
>     1. Always send both, `request_connection` and `request_connection_v2` to each gateway and - for defense in depth - only allow a response to one of them.
> 
>     2. Conditionally send one or the other based on the version.
> 
> 
> Technically, we should be able to get away with (1) because we won't ever release a gateway that responds to both. But somebody could build a gateway from source that does so we need to make sure responding to both doesn't crash anything in the portal.

But where would the gateway get the resource description?

**Comment by thomaseizinger** [comment]
> But where would the gateway get the resource description?

Same as the clients: Upon `init` and with update messages during runtime.

**Comment by jamilbk** [comment]
> Send resources to gateway upon init and also send resource updates to the gateways.

This is a fairly large departure from the on-demand way it works now. Consider that all gateways will need to receive all resources from the site they exist in.

And when a resource changes sites, we'll need to remove all the old resources from the old gateways over to the new site's gateways.

**Comment by conectado** [comment]
> > Send resources to gateway upon init and also send resource updates to the gateways.
> 
> This is a fairly large departure from the on-demand way it works now. Consider that all gateways will need to receive all resources from the site they exist in.
> 
> And when a resource changes sites, we'll need to remove all the old resources from the old gateways over to the new site's gateways.

Yeah, furthermore this affects completely how resources work right now and the whole access model, this needs very careful consideration.

**Comment by thomaseizinger** [comment]
> > Send resources to gateway upon init and also send resource updates to the gateways.
> 
> This is a fairly large departure from the on-demand way it works now. Consider that all gateways will need to receive all resources from the site they exist in.

Well, it is either that or we need to introduce multiple `request_connection` messages that are all identical modulo the resource they are referring to. It seems natural to have `request_connection` refer to resources by ID and update those separately.

> And when a resource changes sites, we'll need to remove all the old resources from the old gateways over to the new site's gateways.

The portal already has to have logic for sending a `request_connection` message to a gateway that is actually in charge of serving a particular resource. If a resource changes site, then all future `request_connection` messages will just go to a different gateway. So technically, it doesn't have to be removed if we are okay with a stale entry (how often do customer's move resources between sites?). Really, there isn't any difference to how we currently do things. The entry in our internal routing table for a particular resource will still be there because currently, we don't receive any updates about resources on the gateway.

**Comment by conectado** [comment]
> > > Send resources to gateway upon init and also send resource updates to the gateways.
> > 
> > 
> > This is a fairly large departure from the on-demand way it works now. Consider that all gateways will need to receive all resources from the site they exist in.
> 
> Well, it is either that or we need to introduce multiple `request_connection` messages that are all identical modulo the resource they are referring to. It seems natural to have `request_connection` refer to resources by ID and update those separately.
> 
> > And when a resource changes sites, we'll need to remove all the old resources from the old gateways over to the new site's gateways.
> 
> The portal already has to have logic for sending a `request_connection` message to a gateway that is actually in charge of serving a particular resource. If a resource changes site, then all future `request_connection` messages will just go to a different gateway. So technically, it doesn't have to be removed if we are okay with a stale entry (how often do customer's move resources between sites?). Really, there isn't any difference to how we currently do things. The entry in our internal routing table for a particular resource will still be there because currently, we don't receive any updates about resources on the gateway.

~~Well, right now gateways get the message `RejectAccess` when a client shouldn't have access to a resource they currently have access to. So when a resource moves sites, gateways shouldn't only receive `RejectAccess` it should also get an update of the resource.~~ Edit: the message the gateway should get is `ResourceUpdated` which they already receive.

This is some additional(or different) logic since that request needs to be sent not only to gateways with a client currently access the resource but to all gateways.

Otherwise users can abuse this and get access to resources behind gateways they shouldn't have anymore.

**Comment by thomaseizinger** [comment]
> Otherwise users can abuse this and get access to resources behind gateways they shouldn't have anymore.

How? Tracking possible resources != allowed resources per client.

The only difference I see here is that sending an update or remove message for a resource has the potential to clean up some memory on the gateway when a resource moves between sites. That would also fix itself upon the next reboot of the gateway.

I am not saying we shouldn't properly clean up the state here, just that it is not necessary for correctness and as with most forms of leaks, is fixed by a restart. My assumption would be that resources don't move between sites very often so it isn't a very important problem to solve right now.

**Comment by conectado** [comment]
> > Otherwise users can abuse this and get access to resources behind gateways they shouldn't have anymore.
> 
> How? Tracking possible resources != allowed resources per client.
> 
> The only difference I see here is that sending an update or remove message for a resource has the potential to clean up some memory on the gateway when a resource moves between sites. That would also fix itself upon the next reboot of the gateway.
> 
> I am not saying we shouldn't properly clean up the state here, just that it is not necessary for correctness and as with most forms of leaks, is fixed by a restart. My assumption would be that resources don't move between sites very often so it isn't a very important problem to solve right now.

Oh you're right, since the portal decides to allow/reject access.

The only change that we would need is to have the whole description sent as part of the `ResourceUpdate`.

**Comment by conectado** [comment]
> > > Otherwise users can abuse this and get access to resources behind gateways they shouldn't have anymore.
> > 
> > 
> > How? Tracking possible resources != allowed resources per client.
> > The only difference I see here is that sending an update or remove message for a resource has the potential to clean up some memory on the gateway when a resource moves between sites. That would also fix itself upon the next reboot of the gateway.
> > I am not saying we shouldn't properly clean up the state here, just that it is not necessary for correctness and as with most forms of leaks, is fixed by a restart. My assumption would be that resources don't move between sites very often so it isn't a very important problem to solve right now.
> 
> Oh you're right, since the portal decides to allow/reject access.
> 
> The only change that we would need is to have the whole description sent as part of the `ResourceUpdate`.

And for it to be sent to all gateways that have a resource instead of just the ones serving it.

**Comment by thomaseizinger** [comment]
> The only change that we would need is to have the whole description sent as part of the `ResourceUpdate`.

That is already the case, no?

https://github.com/firezone/firezone/blob/5b0aaa6f819cae23d1149ed079268ea3db555a54/rust/gateway/src/messages.rs#L115

**Comment by thomaseizinger** [comment]
> > Send resources to gateway upon init and also send resource updates to the gateways.
> 
> This is a fairly large departure from the on-demand way it works now. Consider that all gateways will need to receive all resources from the site they exist in.

I don't really see how it is conceptually very different. That logic must already exist in the portal because a gateway must get picked for a connection intent to a resource. Plus, there must already be a trigger to send an update message to all clients when a resource changes. Also sending an update to all relevant gateways doesn't appear much different conceptually?

Overall, I think this solution balances several trade-offs quite well:

- The `request_connection` message requires a reply from the gateway. Having multiple different messages that all require the same kind of reply is the bad kind of duplication. If anything changes about our connection setup that isn't resource related, we'd need to change it in N places, or worse, create N new messages if it isn't a backwards-compatible change. By referencing only the resource ID, we decouple this message from any future changes to the resources themselves.
- We already send resource updates to clients so this idea isn't novel but just aligns how we deal with resources changing during the runtime of a component. We already know how to do that. Doing it for the gateway as well seems like a low-risk change to me.
- I've already stated my points for why I'd prefer to move away from enums and instead flatten the JSON representation to use multiple fields. I don't care very strongly though if we want to instead instrument every enum such that `serde` ignores future additions of new variants.
- Adding new fields instead of a new resource variant however should simplify the portal because it doesn't need to worry about the version of the client that connects. These kind of compatibility codepaths are annoying to deal with so I think we should reduce them as much as possible.

Am I missing another requirement?

**Comment by jamilbk** [comment]
I'm not necessarily against the idea, but more trying to make the point it's another large refactor we would need to sink time and energy into.

I suppose the right decision depends on the density of resource utilization we expect across Gateways in a Site, and how long we expect Gateways to remain up.

Suppose we have 10 Gateways in a Site with 100 Resources. If we proactively "prime the cache" when Gateways start, we broadcast 1000 Resources to them right away. When `request_connection` happens, it's true we only need to send the `resource_id`, but we may have broadcasted (and continue to update) Resources to Gateways that may never see use.

If instead we broadcast Resources to a single designated Gateway chosen by the portal upon the `request_connection` message, bandwidth, DB, and CPU utilization could be much lower. If however, the same Resource is being accessed over and over again by the same Clients, then this data duplication may add up.

One strategy is in effect eager loading at the expense of possibly wasted updates to Gateways that may never be used. The other strategy is lazy loading which defers updates at the expense of possible duplicates there.

I can't say for certain which is the correct approach at this point. It feels like this is a solved problem in computer science however, and feels like a problem similar to the one LiveView solves for instance -- sending diffs of data only.

If that's the case, the optimal solution perhaps would be for Gateways and the Portal to maintain a sort of checksum of the Resources they have, and update this with only the needed changes in the `request_connection` message.

That's pretty complicated though and requires tracking more state on both sides. Just some food for thought.

We did some very crude thinking through this when we were planning the control plane API you can find [here](https://github.com/firezone/corp/issues/513#issue-1421117273).

**Comment by AndrewDryga** [comment]
What if we just accept a regex in the URL and avoid coming up with custom patterns completely?

**Comment by conectado** [comment]
> Suppose we have 10 Gateways in a Site with 100 Resources. If we proactively "prime the cache" when Gateways start, we broadcast 1000 Resources to them right away. When `request_connection` happens, it's true we only need to send the `resource_id`, but we may have broadcasted (and continue to update) Resources to Gateways that may never see use.

We only broadcast a 1000 resources at once if all the gateways start together, otherwise it's a 100 per-gateway starting. 

So it's very similar to Clients, I'd expect the table Client <> Resources to be bigger than Gateway <> Resources and we find broadcasting the resources to the clients acceptable.

**Comment by conectado** [comment]
> What if we just accept a regex in the URL and avoid coming up with custom patterns completely?

A user might exploit a regex pattern to DoS a gateway, this would make it too easy for admins to shoot themselves in the foot.

**Comment by thomaseizinger** [comment]
I started writing some unit tests in https://github.com/firezone/firezone/pull/5901/files#diff-4f8568b8a7fad832ca42223f3dac925b9a4d7889e0f743e2fcaaac081fedbc10R655.

cc @jamilbk @chrisbrookes Would you mind having a look at the test cases and let me know if those are what you had in mind?

**Comment by jamilbk** [comment]
@thomaseizinger Is this just waiting on required portal changes?

**Comment by thomaseizinger** [comment]
> @thomaseizinger Is this just waiting on required portal changes?

Yes. See https://github.com/firezone/firezone/pull/5901#issuecomment-2237726593.
