### ISSUE TITLE
Some enhancments and a minor issue

### ISSUE THREAD

**Issue by inclementweather** [CloudFire-LLC/cloudfire#510]
Just set up Firezone to test out and its really great!  I have some feedback/suggestions after trying this out for a while.

1.  Adding Mutual TLS support for the Nginx config be great.  I'm not keen on exposing a webpage to the world from a network I want to keep secure.  I suppose I could do this if I disabled the internal Nginx and ran my own?
2. The ability to promote a user to admin / having more than one admin.
3. The ability to disable the "add device" function on the logged in user page so they can just auth and connect. I don't want them to add a bunch of devices on their own. Not much of a security issue since they could export the config they have to some other device... but the page would be much simpler for non-tech users.
4. A nit-pick - telemetry on a security related service is not great.  It could at least be off by default.  

The minor issue I'm experiencing occurs when I log out of any account and try to log back in.  I just get a 403 Forbidden.  The logs don't indicate why though but if I clear my cache it lets me log in again.

Overall I really like this project.  Very nice work!

**Comment by jamilbk** [comment]
1. That's a good idea, I'll add it to our backlog. And yep, you can disable the bundled nginx and add your own if that works for you.
2. We don't have a UI form for this yet, but you can do it from the shell like so:

```
/opt/firezone/embedded/bin/psql -U firezone -h localhost -d firezone -p 15432 -c "UPDATE users SET role = 'admin' WHERE email = '[EMAIL]'"
```
3. Good idea! Will add to our backlog.
4. We suspect this may be the case. We do need *some* telemetry in order to know what to build (most users aren't helpful like and don't open GH issues). We'll keep this in mind. Perhaps we can have a transparency page showing what we collect (nothing ever goes a 3rd party) and how to turn it all off.


As for the minor issue you experienced, we've got this in our backlog and will be releasing a fix soon! Thanks for the report.

**Comment by inclementweather** [comment]
Appreciate the response.  I'll probably give this a limited test with a small number of people in the coming weeks.  If there's any other feedback from my team I'll pass it along.  Thanks!

**Comment by jamilbk** [comment]
@inclementweather

I've added the mTLS support to our backlog and opened #544 to track changing a user's role. Closing this. Thanks for the feedback!
