### ISSUE TITLE
Publish `relay`, `domain`, `api`, `web` images to ghcr.io

### ISSUE THREAD

**Issue by Intuinewin** [CloudFire-LLC/cloudfire#5447]
Hi, not really a feature request but a general question.

You recently split the versioning of clients, gateway and relay/portal components, but the release process of the last 2 components do not seem to appear in this refacto of the CI. I saw you deployed your production environment 2 days ago but no GH release or update of the containers in GHCR.

Are you still planning to do GH releases of portal components and relay?

And, if not, could you at least upload docker images to GHCR when you deploy your production environment?

**Comment by jamilbk** [comment]
Hi @Intuinewin -- yes we discussed internally and moved away from portal/relay versioning because it would essentially be meaningless -- we don't follow semantic versioning there (there is only 1 version we run/support - `latest`).

I can look into adding a CI step to publish the images with the Git SHA like we do for our infra.
