### ISSUE TITLE
UI constantly reloads when running behind reverse proxy

### ISSUE THREAD

**Issue by Ceelight** [CloudFire-LLC/cloudfire#545]
Hi!

I'm running firezone behind a nginx reverse proxy with ssl enabled, redirecting to firezone via http/80. ssl_force is off.

If I open the URL (like vpn.example.com) which points to the reverse proxy, after log in the browser (safari and chrome on macos) constantly reloads the page. Expected behaviour because it shouldn't run behind a reverse proxy?

Thanks!

**Comment by jamilbk** [comment]
Hey @Ceelight thanks for raising the issue. Are you using the bundled Firezone nginx or using your own?

This happens when the WebSocket can't connect -- for some reason either your nginx proxy isn't handling WebSocket connections properly, or perhaps there's an issue with passing the host headers to the phoenix upstream.

If you check your browser console log, you'll see more details as to what's going on with the WebSocket connection. Post here and we can go from there!

**Comment by jamilbk** [comment]
@Ceelight Going to close this issue due to inactivity -- if you're still experiencing, feel free to reopen. Thanks!
