### ISSUE TITLE
Tune Relay prod logging

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5490]
If this is expected maybe it should be an `info!`. If not, what could the issue be? The prod logs are filled with them.

<img width="655" alt="Screenshot 2024-06-21 at 3 38 26 PM" src="https://github.com/firezone/firezone/assets/167144/55d17e14-b12a-4541-b59a-12845394f642">

**Comment by thomaseizinger** [comment]
They are expected if the client hasn't sent a nonce but we should be able to detect that. I talked about this with @AndrewDryga in the past and I think we concluded that we want them so we could see a spike in case somebody tries to access our relays.

I should able to handle the none-nonce case more gracefully although I believe that is what we had in the past.

**Comment by thomaseizinger** [comment]
See https://github.com/firezone/firezone/pull/4700.

**Comment by AndrewDryga** [comment]
@thomaseizinger I think what we should do is have a separate log for situations where existing allocation can not be refreshed (because of invalid nonce) which can be logged as INFO, and when somebody tries to make a new allocation without a valid nonce for the first time (ie. brute-forcing in) and keep that as WARNING. Would that be easy to do?

**Comment by thomaseizinger** [comment]
One issue is that we currently aren't very smart about not re-sending multiple requests if we don't have a valid nonce. I think this can be fixed in `snownet` by maintaining a separate buffer in case we don't have a valid nonce. That should reduce the number of these logs.

I'll also make the logging smarter to not emit so many as `warn`.
