### ISSUE TITLE
List users online and connection history.

### ISSUE THREAD

**Issue by kapa6ac-6apa6ac** [CloudFire-LLC/cloudfire#564]
Hi! Thank you for your work. This is awesome! 
Can you please tell me how I can see which users are online now and their connection history. Is it possible to do this? Thank you.

**Comment by jamilbk** [comment]
Hey @kapa6ac-6apa6ac -- not directly, but there are a couple ways to possibly get the information you're after:

1. As of 0.3.8 you can view a device's latest handshakes (last activity). Since WireGuard is connectionless, it's a bit tricky to determine which devices are "online" vs "offline" with the standard WireGuard client. But if you set the PersistentKeepalive to, say, 25 seconds, then any devices with a latest_handshake > 25 seconds can be assumed offline.
2. We enable WireGuard debugging for the kernel module which does track peer (device) activity -- but nothing in the UI exposes this currently.

I'll leave this issue open to track UX improvements to (1) to make it more user-oriented vs device-oriented.

For (2) that's probably suited to be part of a larger audit logging feature we currently have in our roadmap.

**Comment by kapa6ac-6apa6ac** [comment]
Hi, @jamilbk
Thank you for your reply. I was just about to upgrade my server to 0.3.8 today. 
(1) - is a very good feature. Thank you very much for that! 
But how to look it up on the command line? Is there no way to use `wg show` or something like that?

I would like to program at a proper level to contribute to your project, but I am far from it, unfortunately.
Regards.

**Comment by jamilbk** [comment]
@kapa6ac-6apa6ac We use `wg show {interface-name} dump` to dump all the statistics for each connected peer and send this information to the UI every few seconds. If you're using the default interface name, try `wg show wg-firezone dump`.

**Comment by kapa6ac-6apa6ac** [comment]
@jamilbk 
Strangely, I get this response in my Debian 11 `-bash: wg: command not found`. Apparently a PATH entry is missing, but `wg` is not in any of these paths - `/bin/`, `/usr/bin/`, `/usr/sbin`. 
I seem to have missed something in the documentation.

Thank you!
Regards

**Comment by jamilbk** [comment]
@kapa6ac-6apa6ac Ah yes -- try this: `/opt/firezone/embedded/bin/wg` :-)

**Comment by kapa6ac-6apa6ac** [comment]
Yes, it works =)

Thanks again!
Regards

**Comment by jamilbk** [comment]
Connection history isn't implemented, but that's part of a larger auditing feature we'll be working on.
