### ISSUE TITLE
Allow overriding the server-side generated AllowedIPs for a device.

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#567]
This would allow topologies where a connected device may be set up to route packets to one of its connected networks (e.g. site to site).

**Comment by calt1** [comment]
Is there any hacky method to achieve this on the current version before it's officially implemented?

**Comment by prohand** [comment]
Hello,

Do you know when this feature will be available @jamilbk @AndrewDryga ?

Thanks

**Comment by jamilbk** [comment]
This area will be changing quite a lot in 0.8, so I'll add it to the 0.8 milestone to revisit then.

**Comment by prohand** [comment]
Hello, ok, thank you

Do you have an approximate release date for version 0.8?

Thanks

**Comment by jamilbk** [comment]
No ETA just yet, still working on it :-).

**Comment by prohand** [comment]
Ok, thank you

**Comment by helmut72** [comment]
This would be perfect for managing devices at home that doesn't allow installing Wireguard. A TCP tunnel isn't always possible because of a required app on a Client PC.

**Comment by xAiluros** [comment]
Have added my own hacky support for this -- DO NOT RUN on anything production-like or otherwise sensitive!!
https://github.com/xAiluros/firezone/tree/site-to-site

Requires variable in .env - example:
`WIREGUARD_IPV4_SITES=10.0.0.0/8`
 (this will route the net through wireguard device)

And then you can set (subnet of) network in device configs:
![image](https://user-images.githubusercontent.com/51412484/234895446-c92a29fa-da4b-47a6-b8a1-1f9966929d96.png)
I have only tried with a single connected IPv4 subnet to a device. This could then be successfully communicated to from another device.

Of course the client to which the site is connected, needs to have routing enabled (I only did 1 "test" from Linux client).
Not sure to what extent it works with the rules. Possibly saw some strange behavior. But playing around with the rules a bit I could get it setup fine for my lab environment.

Note: this is NOT TESTED properly at all!

**Comment by jamilbk** [comment]
As I understand, this is for site-site VPN which will be irrelevant in 1.0 with the introduction of Gateway instance groups.

You will be able to deploy multiple Firezone Gateways to your private networks, and use the Firezone clients to access those. NAT traversal will be performed automatically to achieve the best path for packets to route.
