### ISSUE TITLE
After editing a Resource, redirected to Sites, not Resource show

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5776]

**Comment by AndrewDryga** [comment]
Why do we want to do this? After you edit a resource you should be at the show page to see your changes applied. This is the pattern we have for all create/edit pages. Also, when you created a resource the show page is better because it gives a clear way to create a policy:

<img width="1423" alt="Screenshot 2024-07-10 at 10 05 38 AM" src="https://github.com/firezone/firezone/assets/1877644/27e78557-eb16-43f4-b766-f7c75f7aaf87">

**Comment by jamilbk** [comment]
I agree, that's why this is marked as a bug.

**Comment by jamilbk** [comment]
It's currently redirecting to Sites

**Comment by bmanifold** [comment]
Have we had customers complain about the current functionality?  

The reason I ask is that I thought we put the 'return to sites' functionality in purposefully.  If a users goal is to just create one new resource, then sending the user to the 'Resource Show' page is probably best, but if the users goal is to create a bunch of new resources at one time, then returning the user to the 'Resource Show' page after every create will likely get taxing, because finding your way from a 'Resource Show' page to the 'Site Index' page is not the most intuitive right now (and may get trickier when multi-site resources are introduced) since our bread crumbs are the usual way to find your way back to a 'parent', but the 'Resource Show' page will send you back to the 'Resource Index' page and while you can create another Resource from that index page, it's also potentially confusing/taxing, since you have to select the proper Site when creating the Resource.

So, all of this said, I'm just curious what our customers are actually saying/wanting.

**Comment by jamilbk** [comment]
@bmanifold I think you're right -- after creating a Resource we should be taken to the `sites` page.

What's currently happening however is:

- After `edit`ing a Resource, they're taken to `sites` show
- After `create`ing a Resource, they're taken to the `resources` show

So I think we just need to flip these two.
