### ISSUE TITLE
Ensure `reinit` process handles updated Resources

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5780]
Hit an issue just now where the Resource list in my client was stale and did not seem to be updated.

I think this happened because:

- The portal was being redeployed
- It takes 30s for the connection to the portal to drop in the Client, which would trigger a reconnect and new `init`
- I removed and added a Resource within this 30s period
- That update was forever lost, resulting in a Client with resource list menu that is stale and won't be updated until Resources or Policies change again.

Are Resources updated in the reinit?

**Comment by thomaseizinger** [comment]
> Are Resources updated in the reinit?

We just connect to the portal and use whatever it sends us after. I'd assume the portal always sends us the current state, just after receiving `init`?

I tempted to say that we don't receive an up to date message here because updating resources works just fine in all other cases?

Having a log with `wire::api=trace` would confirm this. Maybe we should set this as the default for local debugging everywhere? It means we will print the heartbeat every 30s though.

**Comment by jamilbk** [comment]
Got it, I'll see if I can repro!

**Comment by jamilbk** [comment]
Closing for now, unable to reproduce. Maybe this was related to #5899
