### ISSUE TITLE
Debug full-route on Windows

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5955]
refs #2667 

Still debugging packet loops/drops, can be triggered more by two interfaces and/or roaming.

- When adapter changes on windows, default route can be deleted
- Packet loops can occur:
  - Trying to send a packet with a specific source selects the interface with that address, otherwise packet is dropped.

- Possible prior art to check for:
  - OpenVPN client
  - Mullvad
  - SoftEther
  - ZeroTier
- Check for any communities for Windows kernel pointers
  - https://github.com/mhxion/awesome-discord-communities
  - Windows kernel mailing lists

**Comment by thomaseizinger** [comment]
With https://github.com/firezone/firezone/pull/5903 being ready for merge in the near future, we have full control over `Tun` and the when the routes are set up etc. It means we can stop polling the tunnel when we roam, ensure the routes are set up correctly and only then continue to send packets.

Would that solve your problem as well @conectado ?

**Comment by conectado** [comment]
Doing some small write up here as to what my understanding of the issue currently is. Though I might still have something wrong.

One issue is that as adapters change on the OS the default route for our adapter can be removed, and never re-added since `set_routes` compare routes and is a no-op if it didn't change.

Changing it to always add routes regardless if they changed or not seems to fix this issue so it's not a big problem, though we do need to detect the adapter change as we do now(I think we listen to a registry and dispatch a reconnect), there might be other ways to do this and we can explore it after we have a clear picture of the problems.

The other problem is that [route lookup on windows seems to be based on source address of the packet](https://learn.microsoft.com/en-us/previous-versions/technet-magazine/cc137807(v=msdn.10)?redirectedfrom=MSDN) and the routing table with the metric when there is no saddr.

This makes things works sometimes, since:
1. When connecting directly packets have the source explicitly set so no routing-loop
2. Normally we connect the portal websocket before the `0.0.0.0/0` is added(though sometimes we don't, it is a race condition between the ffi and the connection)
3. And even when roaming the portal connection can keep working through the gateway

Things break whenever a packet is sent and source address is not set while Firezone's default route is on.

This can happen for one of 2 reasons:
* Websocket reconnection
* Packets for Relays

**Comment by conectado** [comment]
> With #5903 being ready for merge in the near future, we have full control over `Tun` and the when the routes are set up etc. It means we can stop polling the tunnel when we roam, ensure the routes are set up correctly and only then continue to send packets.
> 
> Would that solve your problem as well @conectado ?

@thomaseizinger 

I think we can prevent some of the problems with that regarding websocket connections however.

This wouldn't solve this cases:
* Websocket reconnection during operation without roaming
* Any relay connection

Also we would need to hold up operation until we have sent the allocation packets, but that might not be so terrible.

However, I think if I'm right about what the problem, we can try to find the default route and always set that as the source for every packet.

**Comment by thomaseizinger** [comment]
> One issue is that as adapters change on the OS the default route for our adapter can be removed, and never re-added since `set_routes` compare routes and is a no-op if it didn't change.

We had a similar issue on Linux: https://github.com/firezone/firezone/pull/5392/files#diff-4cf1e6bdd8cc9fadf37adc00067279164808e15fef5da731e97777155bb6ec66R79

**Comment by conectado** [comment]
#6032 Seems very promising on fixing this :)

**Comment by jamilbk** [comment]
![giphy](https://github.com/user-attachments/assets/d1ab8a12-fd91-4a58-81fd-ca369171d10b)
