### ISSUE TITLE
Don't use every relay for every connection

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#6014]
So basically, what we do today is that upon startup / login to the portal, each client and gateway is given 2 relays to use. Each relay yields two remote addresses (one IPv4 and one IPv6) address. These are "candidates" that we use for testing connectivity in addition to our local interface.
Currently, the algorithm for making a new connection just uses all relays (i.e. 4 addresses) plus our local one (can be multiple too, depending on how many interfaces a gateway / client has). A connection is formed by making a NxM matrix of all these candidates and the best one is used. Best is defined as direct > relayed. We could in theory also add additional weights here.
The issue is that this creates a lot of network chatter when in most cases, a direct connection is what we end up making or we will connect over one of the relays. I am pretty sure that we will eventually run into scaling issues here, either locally on clients / gateways or with how traffic that gets routed via relays, simply due to the combinatoric explosion on how we need to test for connectivity.
The decision to use all relays for all connections is dated to a time when a) relays were scoped to a connection b) cutting a connection meant DNS wasn't working anymore. Both of these things are no longer true and I don't think we need this kind of redundancy anymore.
As a starting point, connlib could sample 1 relay from all its local ones to use for a connection. We don't need redundancy here. If a relay is non-functional we:
should detect that using infra monitoring and take it out of the fleet
will likely sample a different one on another connection attempt.
What I'd like to get buy-in on is the idea that connlib gets involved in which relays we use for a certain connection. The portal can still pre-select them geographically or via some other means but we should not expect all of them to be used for every connection. Ideally, we don't use any relay if we already know that we are behind a hole-punch friendly NAT. We can infer that by aggregating the STUN results from multiple relays (if we have the same server-reflexive address reported from all relays, hole-punching will work).

**Comment by thomaseizinger** [comment]
I think UX is the best tag here given the impact on battery life, bandwidth usage etc

**Comment by jamilbk** [comment]
I think this sounds fine. There isn't really any work for the portal here correct? Aside from perhaps sending all Relays to Clients and Gateways in the `init` message.

The only major change then is that `connlib` picks one of the Relays from its init Relays to use for connections. Since the portal will send a `reinit` when deploying, connlib can redo the selection process then, and we just need to ensure that any Relayed connections are smoothly migrated over to the new Relay to avoid packet loss.

> Ideally, we don't use any relay if we already know that we are behind a hole-punch friendly NAT. We can infer that by aggregating the STUN results from multiple relays (if we have the same server-reflexive address reported from all relays, hole-punching will work).

The problem is that we can't guarantee the NAT will behave the same way for every connection. So we can only know if we're behind a friendly NAT upon each connection attempt. For example, consider the case where a connection to one Gateway uses deterministic port mapping and a connection to another Gateway uses a randomized port mapping, or even a different NAT device altogether. It may be unlikely, but in this case forgoing the use of a Relay for the entire connlib session would prevent connections to the second Gateway.

**Comment by thomaseizinger** [comment]
> I think this sounds fine. There isn't really any work for the portal here correct? Aside from perhaps sending all Relays to Clients and Gateways in the `init` message.

Correct! I am not sure we need more relays to be sent to clients but even if, it is a somewhat orthogonal concern to this.

> The only major change then is that `connlib` picks one of the Relays from its init Relays to use for connections. Since the portal will send a `reinit` when deploying, connlib can redo the selection process then, and we just need to ensure that any Relayed connections are smoothly migrated over to the new Relay to avoid packet loss.

I am tempted to say, we don't need to "migrate" anything:

- If a connection is relayed, all other candidate pairs will have failed and the only active ones are via the relay.
- If a relay shuts down, we invalidate all its candidates locally.
- Invalidating the nominated candidate will instantly cut the connection (no 15s ICE timeout).
- The very next packet will attempt to establish a new one.

It is basically like roaming, which should not be noticable beyond a tiny delay of 1-2s. 

So much for the theory at least.
