### ISSUE TITLE
chore(bin-shared): `CommonArgs` appears to only be common to the Gateway

### ISSUE THREAD

**Issue by ReactorScram** [CloudFire-LLC/cloudfire#6025]
It says common to all Firezone apps but `git grep` only shows it in the Gateway.

We can probably add it back to the Headless Client, but the GUI Client will ignore it since the GUI manages tokens and API URLs its own way.

**Comment by thomaseizinger** [comment]
Nice find! I tend to err on the side of duplication for these because I am not a fan of "utils" or "shared" modules. The purist in me would want a separare crate for each concern. (anything "common" tends to become a dependency magnet). Maybe "bin-shared" should be split into `linux-tun` and `windows-tun`?

**Comment by ReactorScram** [comment]
Yeah I'm also in favor of duplication. It's like 3 fields that don't change often, I think we can just inline `CommonArgs` into Gateway's CLI
