### ISSUE TITLE
Enable/Disable Resources

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#6074]
https://github.com/firezone/firezone/issues/2667#issuecomment-2209392840

**Comment by conectado** [comment]
I'm still thinking of what's the best design for this.

Either the client could inform the disabled/enabled routes to connlib, or it could just save the state of disabled/enabled route and filter routes based on that.

However, I think it's better to let connlib decide the routes and have the client just pass the UI information to connlib.

The main reason for this, is that connlib only pass the routes to the clients and not what resources enabled those routes, so for overlapping internet resources it could be complicated for the client to ignore routes w/o making assumptions on how those routes are selected from the resources, which I think is better that we keep in connlib.

**Comment by jamilbk** [comment]
Test #4834 to see if full-route fixes it

**Comment by thomaseizinger** [comment]
> I'm still thinking of what's the best design for this.
> 
> Either the client could inform the disabled/enabled routes to connlib, or it could just save the state of disabled/enabled route and filter routes based on that.
> 
> However, I think it's better to let connlib decide the routes and have the client just pass the UI information to connlib.
> 
> The main reason for this, is that connlib only pass the routes to the clients and not what resources enabled those routes, so for overlapping internet resources it could be complicated for the client to ignore routes w/o making assumptions on how those routes are selected from the resources, which I think is better that we keep in connlib.

Also, doing it on the client would require us to implement this functionality multiple times.

I am in favor of introducing messages for enabling / disabling resources. Likely, we want the state to be ephemeral in connlib, so the client has to disable resources every time it boots up a new session.

**Comment by Intuinewin** [comment]
Hi, this issue is closed but I can't figure out how to enable/disable resources in the latest clients. Do I need to enable something in the portal?

I think this feature is very important. In our company, tech people often have access to prod and staging and it could be great for them to be able to disable prod resources if they are not using them in order to avoid mistakes.

I saw the PAM issue and I think it's a good first step but beeing able to disable a resource from the client is pretty important I think. Ofc, not all resources should be disableable and it should be configured through a policy or directly in the resource.

**Comment by jamilbk** [comment]
@Intuinewin So enable/disable is only supported for the Internet Resource -- we wanted to think more carefully about the use cases there before adding complexity that might already be handled by #6158. One of the use cases for that issue is specifically preventing prod access.
