### ISSUE TITLE
Support DNS over TCP

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#6140]
Currently, `connlib` simply drops TCP packets to sentinel DNS servers. This causes problems because for some large DNS queries, the TCP fallback is needed to reliably transport the response.

Most DNS clients have such a fallback implemented: If the DNS query fails over UDP, they try TCP. Us not supporting TCP causes problems such as #6134.

```[tasklist]
### Pre-work
- [ ] https://github.com/firezone/firezone/pull/6997
- [ ] https://github.com/firezone/firezone/pull/6999
- [ ] https://github.com/firezone/firezone/pull/7007
- [ ] https://github.com/firezone/firezone/pull/7018
- [ ] https://github.com/firezone/firezone/pull/7020
- [ ] https://github.com/firezone/firezone/pull/7022
- [ ] https://github.com/firezone/firezone/pull/7023
- [ ] https://github.com/firezone/firezone/pull/7025
- [ ] https://github.com/firezone/firezone/pull/7044
- [ ] https://github.com/firezone/firezone/pull/7041
- [ ] https://github.com/firezone/firezone/pull/7043
- [ ] https://github.com/firezone/firezone/pull/7062
- [ ] https://github.com/firezone/firezone/pull/7065
- [ ] https://github.com/firezone/firezone/pull/7066
- [ ] https://github.com/firezone/firezone/pull/7067
```

```[tasklist]
### Defintion of done
- [ ] https://github.com/firezone/firezone/pull/6944
- [x] Changelog entries
- [x] Docs PR?
- [x] Test on real MacOS device
- [x] Test on real Android
- [x] Test on Linux machine
- [x] Test on Windows
```

**Comment by jamilbk** [comment]
Possible cause of https://firezonehq.slack.com/archives/C077VKJGQ3W/p1726613711222829

**Comment by jamilbk** [comment]
Looks into FushicaOS - has a TCP implementation.

**Comment by thomaseizinger** [comment]
Link to Discord conversation with Fuchsia maintainers: https://discord.com/channels/835268677472485376/883122373484752936/1285741516387782728

- `netstack3` crate: https://cs.opensource.google/fuchsia/fuchsia/+/main:src/connectivity/network/netstack3/core/;l=1?q=Netstack3%2Fcore&ss=fuchsia%2Ffuchsia
- The main hurdle is that Fuchisa doesn't use `cargo` for its build system, meaning the code cannot be directly added as a cargo dependency.
- The follow patch-set includes a Python script which may be able to generate a valid `Cargo.toml` for the `netstack3` crates: https://fuchsia-review.googlesource.com/c/fuchsia/+/995502
- We should try the above script and see if it works for `netstack3`
- If not, we may have to write one by hand.
- If we use this code, we should work out a way of automating that so we can easily keep up with upstream.

**Comment by thomaseizinger** [comment]
We should also look at https://docs.rs/smoltcp, it may require some layers of indirection but likely still better than writing our own and maybe less hassle than using the Fuchsia stuff.

**Comment by jamilbk** [comment]
Possibly cause of #6768 but needs to be verified.

**Comment by thomaseizinger** [comment]
#6944 implements DNS over TCP. Do we need to update any docs for this?

**Comment by jamilbk** [comment]
Hmm I don't think so since it's not a user-facing change. Probably just the Changelog.

**Comment by thomaseizinger** [comment]
@ReactorScram Could you do me a favor an test the linked PR on Windows? Things to watch out for:

- Regular DNS resolution works with and without Internet resource for resources and non-resources
- DNS resolution of via a commandline tool for `2048.size.dns.netmeister.org` works (the response is too big for UDP so it should fall back to TCP and succeed)

**Comment by thomaseizinger** [comment]
Tests on MacOS and Android are positive!

**Comment by ReactorScram** [comment]
Looks good to me. I tested the CI build from your PR and the netmeister address works. Then I tested with 1.3.8 (current release) and it failed as expected.

The only thing that bugs me a little about Internet Resources is, since they don't get our 100.96.x.y IPs, I can't tell if a non-Resource is actually going through the tunnel. Without resorting to Wireshark.

Tested the x86_64 Windows MSI from this page https://github.com/firezone/firezone/actions/runs/11247920713#artifacts
`Version 1.3.9 (f751a5b)`

- **Internet Resource is disabled**
- Regular DNS works for a Resource (`curl -s -4 https://ifconfig.net` returns the Gateway IP)
- Regular DNS works for a non-Resource (`https://www.wikipedia.org/` loads in Firefox, nslookup returns 208.80.154.224)
- `nslookup 2048.size.dns.netmeister.org` hits our sentinel resolver and returns roughly 80 addresses
- **Enabling Internet Resource**
- Regular DNS works for a Resource (`curl -s -4 https://ifconfig.net` returns the Gateway IP)
- Regular DNS works for a non-Resource (**Unclear** - wikipedia.org loads in Firefox and resolves in nslookup, but it's still 208.80.154.224. That's because we're routing 0.0.0.0, right? So we don't need to assign our own IPs to non-Resources?)
- `nslookup 2048.size.dns.netmeister.org` hits our sentinel resolver and returns roughly 80 addresses

Running the same tests with `Version 1.3.8 (650e31c)`

- **Internet Resource is enabled**
- Regular DNS works for a Resource (`curl -s -4 https://ifconfig.net` returns the Gateway IP)
- Regular DNS works for a non-Resource (Wikipedia loads in Firefox and resolves in nslookup)
- `nslookup 2048.size.dns.netmeister.org` fails with `Unspecified error` (**expected**, since this is on 1.3.8)
- **Disabling Internet Resource**
- Regular DNS works for a Resource (`curl -s -4 https://ifconfig.net` returns the Gateway IP)
- Regular DNS works for a non-Resource (`https://www.wikipedia.org/` loads in Firefox, nslookup returns 208.80.154.224)
- `nslookup 2048.size.dns.netmeister.org` fails with `Unspecified error` (**expected**, since this is on 1.3.8)

**Comment by thomaseizinger** [comment]
> The only thing that bugs me a little about Internet Resources is, since they don't get our 100.96.x.y IPs, I can't tell if a non-Resource is actually going through the tunnel. Without resorting to Wireshark.

Any "what is my IP" website should return you the gateway IP. Or speed / ping test sites should return a very obviously increased ping becausd you relay everything through the gateway.

I don't really know of another way to check it :)

**Comment by thomaseizinger** [comment]
Thank you for the comprehensive testing!

**Comment by ReactorScram** [comment]
Ah, I forgot that trick. Re-tested just now and DuckDuckGo with `ip addr` does show the Gateway IP. Good

**Comment by thomaseizinger** [comment]
@ReactorScram Could you do another quick test for me using the latest version of the branch on a Windows device? 🙏

**Comment by ReactorScram** [comment]
It passed.

Tested PR #6944, `Version 1.3.10 (26057a5)` on bare-metal x86_64 Windows 11

- **Internet Resource is enabled**
- [x] `curl -s -4 https://ifconfig.net` returns the Gateway IP
- [x] `ip addr` in DuckDuckGo returns the Gateway IP
- [x] `nslookup 2048.size.dns.netmeister.org` hits our sentinel and returns a bunch of addresses
- **Disabling Internet Resource**
- [x] `curl -s -4 https://ifconfig.net` returns the Gateway IP
- [x] `ip addr` in DuckDuckGo returns the Client IP
- [x] `nslookup 2048.size.dns.netmeister.org` hits our sentinel and returns a bunch of addresses

I didn't test on 1.3.9 since the tests were already validated on 1.3.8.
