### ISSUE TITLE
Mac address binding of VPN profile

### ISSUE THREAD

**Issue by kutsav** [CloudFire-LLC/cloudfire#6429]
#### Is your feature request related to a problem? Please describe.
Right now there is no security against vpn config protection. The same vpn config file can be used in multiple systems without the admin knowing about it.

#### Describe the solution you'd like

In order to make VPN highly secure, there should be a provision that the VPN detects the MAC address of the laptop first time it is trying to connect and bind the user profile against that mac address, ensuring high security. If a user changes his device, then it should require admin approval to add/remove/replace the new mac address.

#### Describe alternatives you've considered
OpenVPN has this feature of mac address binding, but I want to work with a Wireguard based VPN and would love to have this feature in Firezone.

**Comment by jamilbk** [comment]
Hi @kutsav - what version of Firezone is this?

Firezone 1.0 does not use VPN config files whatsoever. The private keys stay in device memory and are rotated each session, completely eliminating this attack vector.

**Comment by kutsav** [comment]
This is for firezone version 0.7 self hosted.


Is this feature available in latest self hosted version as well?

**Comment by jamilbk** [comment]
Firezone 0.7 was end-of-life back in January. Unfortunately this won't work for that version because it requires our custom clients.

Going to close this issue as 0.7 is no longer supported. If you'd like to give 1.0 a try, it _is_ possible to self-host, but be warned that 1.0 is more complex due to all the new features (such as the one mentioned in this ticket).

We offer a free starter account if you'd like to try the cloud-managed version: https://app.firezone.dev/sign_up
