### ISSUE TITLE
OS Package Repository

### ISSUE THREAD

**Issue by gbe0** [CloudFire-LLC/cloudfire#668]
Currently, to upgrade Firezone you need to know there is a new release available. This most likely means subscribing to GitHub release notifications.

Instead, it would be useful if there is a package repository available for the various operating systems (eg. apt repo for Debian/Ubuntu, yum repo for RHEL and its derivatives). This will make the upgrade process much easier to manage as we can simply handle the upgrade as we would any other OS package. Also for those of us monitoring for available software upgrades on servers it is substantially easier.

For apt repositories, tools such as [reprepro](https://wiki.debian.org/DebianRepository/SetupWithReprepro) can be used to create/manage the relevant directory structure.

**Comment by jamilbk** [comment]
Thanks Chris for the suggestion. Unfortunately this may not be so straightforward with Omnibus since we bundle `nginx`, `postgresql`, and a couple dozen other utilities to ensure Firezone has a consistent environment to run within.

We have plans to clean this up and build native OS packages (see #378) that use the package manager's dependency tree instead of bundling all our dependencies with Omnibus. There's quite a bit of work involved here so it may be some time before we can get to it.

**Comment by gbe0** [comment]
To be clear my suggestion wouldn't need the native OS packages to be used for supporting services; rather I suggest the existing packages are in a repository. An example of other software with the same setup I am suggesting is GitLab - it uses Ombibus also with its own packaged supporting services. The main thing is when package updates come out the OS package manager is aware that there is a new release.

**Comment by jamilbk** [comment]
Good point, I misunderstood. I knew Gitlab uses Omnibus but did not know they have a package server for the Omnibus builds. In that case, this is more doable in the short term.

Thanks for the suggestion!

**Comment by jamilbk** [comment]
Thanks @gbe0 for getting us set up with cloudsmith.io! Packages can be found here: https://cloudsmith.io/~firezone/repos/firezone/packages/

Keeping this issue to track:

- [ ] Documentation on using this repo
- [ ] Upload release packages from CI
- [ ] Announcement in 0.5.0

**Comment by jamilbk** [comment]
@princemaple Think you could help with this one? Need:

- [x] CI action to push packages to cloudsmith.io on publish (I already have created the `CLOUDSMITH_API_KEY` secret), see https://github.com/cloudsmith-io/action). May need to retire last X packages due to space restraints.
- [ ] Documentation updates:
  - [ ] Add a section to the `Deploy` guide showing how to install Firezone from package repo (in addition to manual install, automatic install)
  - [ ] Add section to `Upgrade` guide on what to do for version upgrades from repo

**Comment by jamilbk** [comment]
I can help with the documentation part.

**Comment by jamilbk** [comment]
Refs #786

**Comment by jamilbk** [comment]
Coming in 0.5.0 :-).
