### ISSUE TITLE
Issues connecting to resources from within WSL

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6777]
Customer reports issues connecting to resources from within the WSL environment on Windows.

- [x] Investigate connecting to IP/CIDR resources from within WSL
- [x] Investigate connecting to DNS resources from within WSL

```[tasklist]
- [ ] Figure out how WSL generates resolv.conf and fix it
- [ ] Add our resolver to our tunnel interface
```

Hypotheses:

- DNS tunneling might be off in WSL? - No, Windows docs indicate it's on by default https://learn.microsoft.com/en-us/windows/wsl/troubleshooting
- Our DNS resolvers are not set to our interface? - Yes

**Comment by jamilbk** [comment]
Specifically this is for connecting to AWS document-db. Related: #6779

**Comment by conectado** [comment]
We do have known issues with WSL #3717

**Comment by ReactorScram** [comment]
DNS is not being controlled, edited details into the first comment

**Comment by ReactorScram** [comment]
DNS is not being controlled.

IP / CIDR Resources seem to work fine, `curl 10.0.32.100` succeeds in WSL.

DNS Resources don't work. `curl -s https://ifconfig.net` fails, returning the clearnet IP.

`/etc/resolv.conf` contains `nameserver 10.211.55.1`, which is the DNS stub for the Parallels VM I'm running Windows in. If I put `nameserver 100.100.111.1` in there, `curl -s https://ifconfig.net` succeeds.

`Get-DnsClientServerAddress -AddressFamily IPv4` doesn't show the Firezone stub resolver at all, just the Parallels resolver. So that's probably why WSL is picking it up.

**Comment by ReactorScram** [comment]
If I run `netsh interface ipv4 set dns name="Firezone" static 100.100.111.1`, then it adds our stub resolver to our interface.

Then I can restart WSL and it will put our resolver first in `/etc/resolv.conf`, and then the DNS Resource seems to work.

This isn't perfect but if we can find the registry equivalent of that netsh command (the command runs very slow) it can be integrated into Firezone.

**Comment by jamilbk** [comment]
Nice work triaging this!
