### ISSUE TITLE
DNSProxyProviders on macOS can interfere with DNS queries when Firezone is signed in

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#6783]
Related: https://firezonehq.slack.com/archives/C069H865MHP/p1726599863041099

It appears that the SentinelOne agent can affect DNS on the system to the point where queries do not get routed properly back to the application. Opening this issue to track further discourse / investigation if it becomes a priority.

**Comment by jamilbk** [comment]
This is also happening for Microsoft Defender, similarly only on some networks (in the customer's case, for the employee's home network).

Behavior was that queries get dropped for some specific domains (presumably the ones they have policies for in their Defender configuration). This was even happening when querying 1.1.1.1 directly, e.g. this was timing out:

```
dig @1.1.1.1 customer-domain.com
```

But this worked fine:

```
dig @1.1.1.1 google.com
```

In this customer's case, I had them add this domain as a DNS Resource so that Firezone would route it and _not_ forward to upstream, and that solved the issue completely for them.

So I can only surmise that something is broken when we either forward queries and/or reply to applications with the responses when there are DNSProxyProviders running on the system.

https://developer.apple.com/documentation/networkextension/dns_proxy_provider

**Comment by jamilbk** [comment]
This is going to be a fun one to troubleshoot, but setting as high priority because many (all?) enterprise customers are going to both have `macOS` machines and inevitably be using some XDR/EDR solution like Defender.

**Comment by thomaseizinger** [comment]
Related forum threads:

- https://forums.developer.apple.com/forums/thread/672688
- https://forums.developer.apple.com/forums/thread/717586

**Comment by jamilbk** [comment]
macOS has routing loop detection called NECP that might be interfering.

**Comment by bmanifold** [comment]
Do we have any info on the configuration of Microsoft Defender that the customer had setup?

I did a manual install of Microsoft Defender on my machine as well as trying to change a few settings in the Microsoft Defender admin site, but I'm not having any issues while using Firezone with MS Defender installed and onboarded, but I'm sure it's likely because I haven't configured something correctly.

**Comment by thomaseizinger** [comment]
Is a DNSProxyProvider from MS Defender active? Are there any settings regarding secure DNS?

**Comment by bmanifold** [comment]
There's nothing jumping out at me in the MS Defender Admin panel regarding 'secure DNS'.  The only thing close to it that I found was 'Web Content Filtering', but that seems to be around categories of content, rather than specific domains or IPs.  I did enable that in the admin panel.  I also set up something titled 'Indicators', which you could specify domain names and/or IP addresses, so I created a "block" rule for the domain `ifconfig.net`, but it didn't seem to get blocked when I went to it both with and without using Firezone.

Where would I check to see if any DNSProxyProvider is enabled?  When I look in my network settings under proxies, there's nothing directly related to DNS Proxy:

<img width="668" alt="Screenshot 2024-10-04 at 6 29 19 PM" src="https://github.com/user-attachments/assets/80663c9c-b7a6-41b9-be6b-5e13ce141268">

<img width="668" alt="Screenshot 2024-10-04 at 6 29 31 PM" src="https://github.com/user-attachments/assets/81a18e20-a5fb-440b-a232-4d72284bf455">

**Comment by bmanifold** [comment]
Ah, wait, I just tried again and I actually was blocked from loading `ifconfig.net`, so it must just take some time to sync the rules or something.  However, my DNS query succeeded:
```
❯ dig +short ifconfig.net
100.96.0.1
100.96.0.2
100.96.0.3
100.96.0.4
```

**Comment by thomaseizinger** [comment]
> Ah, wait, I just tried again and I actually was blocked from loading `ifconfig.net`, so it must just take some time to sync the rules or something. However, my DNS query succeeded:
> 
> ```
> ❯ dig +short ifconfig.net
> 100.96.0.1
> 100.96.0.2
> 100.96.0.3
> 100.96.0.4
> ```

I think DNS resources may have worked for the customer(s)? It was non-resources that got dropped / filtered somehow.

**Comment by bmanifold** [comment]
🤔 Hmmm....not sure.  I read the following comment as "customer couldn't resolve one of their resources, but resolving external resources worked...."

> Behavior was that queries get dropped for some specific domains (presumably the ones they have policies for in their > Defender configuration). This was even happening when querying 1.1.1.1 directly, e.g. this was timing out:
> ``` dig @1.1.1.1 customer-domain.com ```

> But this worked fine:
> ``` dig @1.1.1.1 google.com ```

Although, now that I say that, I realize the fix for them was to add that `customer-domain.com` to their resources in Firezone.

All that said, everything I've tried so far has resolved, with the exception of my local DNS resources on my local `.lan` domain, but that's because we've got our Firezone upstream DNS set to `1.0.0.3` and `1.1.1.3`, so there's no way for my local stuff to get resolved, because it never gets passed to my router/dns server.

**Comment by thomaseizinger** [comment]
> 🤔 Hmmm....not sure. I read the following comment as "customer couldn't resolve one of their resources, but resolving external resources worked...."

Okay, there may very well be multiple bugs / problems here 😅
I am fairl certain we also had the opposite problem with some customer.

I have a pretty decent plan on supporting TCP DNS now which also opens the door for DoH. Hopefully that will fix these problems although not being able to reproduce this is a bummer.

**Comment by jamilbk** [comment]
Hm sorry I don't have more details on the specific customer's setup. The DNSProxyProvider AFAIK won't show up as a thing in the Network section of system settings.

TCP DNS support probably won't affect this particular issue at all, but won't hurt!

**Comment by jamilbk** [comment]
All reports of this happening were on Intel Macs on macOS 15.0, which is known to have a bug regarding network extensions. #7546 

Closing this as unable to reproduce. We can reopen if it's still an issue.
