### ISSUE TITLE
Testing sending TCP & UDP packets through tunnel to ensure any form of port mapping works correctly

### ISSUE THREAD

**Issue by conectado** [CloudFire-LLC/cloudfire#7003]
It's crucial to test #4789 and improve filters coverage

**Comment by conectado** [comment]
@thomaseizinger I know you're working on testing TCP DNS queries in the tunnel proptest. IDK if we're going to have a lot of conflicts if I get started with this right now, let me know what you think!

**Comment by thomaseizinger** [comment]
> @thomaseizinger I know you're working on testing TCP DNS queries in the tunnel proptest. IDK if we're going to have a lot of conflicts if I get started with this right now, let me know what you think!

I haven't started on that yet and probably won't be today neither.

**Comment by thomaseizinger** [comment]
@conectado After having written #6997 and #7007 I think a good way of integrating this could be to write an `http-over-tcp` crate that we can use in the tests to have a transition that sends an HTTP request. I think that would also play along well with testing the filters because we can designate certain resources as HTTP servers.

Alternatively, we can copy only the `smoltcp` boilerplate from `dns-over-tcp` client and have a `SendTCPData` transition that sends some data which is always echoed back by the listening socket.

Thoughts?
