### ISSUE TITLE
Enhance (User-based) rules to include ports

### ISSUE THREAD

**Issue by arenk** [CloudFire-LLC/cloudfire#810]
First of all: great product so far! Also looking forward to user-based rules in 0.5.0.

Would there be any chance to include ports in the rules? E.g. in a scenario where Firezone sits in front of a K8s cluster with several services, the IP of the services is often the same (shared load balancer/ingress) - therefore limiting the potential to restrict access for certain users.

**Comment by jamilbk** [comment]
Certainly doable -- @conectado thoughts?

**Comment by conectado** [comment]
> Certainly doable -- @conectado thoughts?

Definetly possible, we could use [nft's maps](https://wiki.nftables.org/wiki-nftables/index.php/Maps) to create a relation between the destination ip and the port but I'm not sure if that would support CIDR or just individual IPs maybe if we go the other way around(mapping ports to destination IPs) CIDR works, maps do have the `interval` flag so I imagine that there's some way to make.

We need more research on how to best approach this and will need to create some additional rules, which means slower user deletion(since we have to scan for more rules). So maybe we should add this feature after overhauling the firewall system.

**Comment by jamilbk** [comment]
@arenk Would you want to add port specifier on CIDR range destinations or only for single-IP destinations?

@conectado Maybe that would simplify things.

**Comment by conectado** [comment]
> @arenk Would you want to add port specifier on CIDR range destinations or only for single-IP destinations?
> 
> @conectado Maybe that would simplify things.

Yeah I think so

**Comment by arenk** [comment]
@jamilbk @conectado Thanks for the fast response! For our use case, it would be completely sufficient to add port-specific rules to a single IP only (load balancer has a single IP running different services on different ports).

In some cases, we add port ranges to single IPs (e.g. 30200-30205), but I think this might be very specific to our service and it wouldn't be an issue to add multiple ip:port combinations in such a case.

**Comment by jamilbk** [comment]
@arenk Gotcha. This is going to require a bit of work, so we're going to push it to a patch release after 0.5.0 is out the door.

Thanks for your patience, and thanks for the feedback.

**Comment by arenk** [comment]
All good, I never expected that to be part of 0.5.0. It's great to hear it will be implemented at all 😉

**Comment by jamilbk** [comment]
@arenk So we've merged a rough version of this and are testing it. Will update this issue when we cut a new release with the changes.

See #874

**Comment by jamilbk** [comment]
Released in 0.5.4
