### ISSUE TITLE
End devices assigned the same IP with wireguard interface IP 

### ISSUE THREAD

**Issue by elhananjair** [CloudFire-LLC/cloudfire#918]
Hello, there I changed the default wireguard interface IP address from 10.3.2.1 to 10.3.2.2. After changing that, I tried to add a device and left the tunnel IP4 address input field as blank, and generated the config file, what I see is the device got the same IP 10.3.2.2, I was expecting 10.3.2.1 or 10.3.2.3.

**Comment by jamilbk** [comment]
Thanks for the report! The issue is likely caused by our insert SQL not considering the WireGuard server interface IP as unavailable here: https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/queries/inet.ex#L7

Will queue up for a fix. In the meantime, if create more devices that don’t have this IP conflict, do they work as intended?

**Comment by elhananjair** [comment]
> Thanks for the report! The issue is likely caused by our insert SQL not considering the WireGuard server interface IP as unavailable here: https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/queries/inet.ex#L7
> 
> Will queue up for a fix. In the meantime, if create more devices that don’t have this IP conflict, do they work as intended?

Tried once and it did not work for me. But am trying once again.
