### ISSUE TITLE
installed on a fresh system, but no ufw enabled?

### ISSUE THREAD

**Issue by jhjacobs81** [CloudFire-LLC/cloudfire#943]
From the website i gathered Firezone manages UFW as a firewall, but when i logged in i noticed ufw is not installed?

Do i need to install it manually, and if so, do i manually add all the firezone ports?

**Comment by gbe0** [comment]
Hi,

Firezone will manage nftables rules however they are not restricting access to the server itself rather it is for handling NAT and traffic restrictions to/from clients.

UFW is a firewall management option to handle the rules to the server itself (otherwise you can install firewalld or manually make firewall rules); there isn't a dependency on it as it would be presumed that users may want to use any firewall management tool.

A while  back I wrote a template for managing the rules manually, it is available here: https://wiki.gbe0.com/en/linux/firewalling-and-filtering/nftables/template-wireguard

Might be useful if you want an idea of what rules need to be managed.

**Comment by jhjacobs81** [comment]
well, i dont need to manage any rules if firezone does this for me ;-) 

so to recap: if i install firezone on a fresh vpn, i need not to worry about the firewall? I can safely assume its enabled and activated by default?

**Comment by jamilbk** [comment]
Hi @jhjacobs81 -- Firezone manages rules in the forward chain to function as an egress firewall. It currently does not manage any ingress rules for you.

You'll still want to install `ufw` if that's what you prefer to use. You'll want to allow `443/tcp`, `80/tcp`, `51820/udp` by default for the Firezone services. You'll also want to `sudo ufw default allow routed` to enable forwarding.

**Comment by jhjacobs81** [comment]
somehow our firewall rules got wiped.. i tried running the install script anew, but that doesnt fix it either :( restored a backup and that worked :) somehow the firezone rules got deleted :(

**Comment by jamilbk** [comment]
@jhjacobs81 Was this issue still relevant or can I close it out?

**Comment by jhjacobs81** [comment]
We can close it :) i couldnt get it to work well and moved on :(
